- packages/pn-personafisica-webapp/src/api/delegates/__test__/Delegates.api.test.ts
- packages/pn-personafisica-webapp/src/pages/components/Deleghe/delegationsColumns.tsx
- packages/pn-personafisica-webapp/src/redux/auth/__test__/reducers.test.ts
- packages/pn-personafisica-webapp/src/redux/delegation/actions.ts
- packages/pn-personafisica-webapp/src/utils/status.utility.ts
- extension of menu component
- eslint comment fix
Ref. Feature/pn 870
> feat: window menu per table(delegated - delegation) rows

- packages/pn-personafisica-webapp/src/pages/components/Deleghe/Delegates.tsx
- packages/pn-personafisica-webapp/src/pages/components/Deleghe/delegationsColumns.tsx
- Move modal action from Delegates to DelegationMenu
- Linting
> feat: add open modal action to UI

- packages/pn-personafisica-webapp/src/api/delegations/Delegations.api.ts
- packages/pn-personafisica-webapp/src/redux/delegation/actions.ts
- Add call to API to reject delegation request
- Add action to API call
> feat: add call to rejet delegation request

- packages/pn-personafisica-webapp/src/api/delegations/Delegations.api.ts
- packages/pn-personafisica-webapp/src/redux/newDelegation/actions.ts
- packages/pn-personafisica-webapp/src/redux/newDelegation/reducers.ts
- packages/pn-personafisica-webapp/src/redux/newDelegation/types.ts
- Add api call to create a new delegation
- Add redux state and action to create a new delegation
> feat: PN-878 add api call and action to create a new delegation

- packages/pn-personafisica-webapp/public/locales/it/profilo.json
- packages/pn-personafisica-webapp/src/navigation/routes.tsx
- packages/pn-personafisica-webapp/src/pages/Profile.page.tsx
- packages/pn-personafisica-webapp/src/pages/__test__/Profile.page.test.tsx
> feat: add profile page

- packages/pn-personafisica-webapp/public/locales/it/notifiche.json
- packages/pn-personafisica-webapp/src/component/DomicileBanner/DomicileBanner.tsx
- packages/pn-personafisica-webapp/src/component/DomicileBanner/__test__/DomicileBanner.test.tsx
- packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx
- packages/pn-personafisica-webapp/src/pages/Notifiche.page.tsx
- Adds Banner domicilio digitale
- Adds tests
> feat: PN-844 add banner aggiungi domicilio digitale

- packages/pn-pa-webapp/src/pages/components/Notifications/FilterNotificationsTable.tsx
- Change filters form style according to figma
- Remove overflow caused from filters form
Test suite runs correctly.
> PN-1266 fix overflow and align style with figma design

- packages/pn-pa-webapp/src/pages/Dashboard.page.tsx
- packages/pn-personafisica-webapp/src/component/Notifications/DesktopNotifications.tsx
- changed sortable values to false in notification tables in pa and persona fisica apps
tests run correctly
> feat: hide sort action from notifications table

- packages/pn-commons/src/components/TitleBox.tsx
- packages/pn-personafisica-webapp/public/locales/it/common.json
- packages/pn-personafisica-webapp/public/locales/it/profilo.json
- packages/pn-personafisica-webapp/public/locales/it/recapiti.json
- packages/pn-personafisica-webapp/src/pages/Contacts.page.tsx
- packages/pn-personafisica-webapp/src/pages/Profile.page.tsx
- packages/pn-personafisica-webapp/src/pages/__test__/Contacts.page.test.tsx
- packages/pn-personafisica-webapp/src/pages/__test__/Profile.page.test.tsx
feat: add alert into profile page containing a link to contacts
feat: add link to profile page into contacts page
feat: add JSX element as valid type for subtitle prop of TitleBox component
chore: change copy for contacts and profile pages
test: edit tests for profile and contacts pages
> feat: add alert into profile page containing a link to contacts

- packages/pn-pa-webapp/src/navigation/routes.tsx
- packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
- packages/pn-pa-webapp/src/pages/__test__/ApiKeys.page.test.tsx
feat: add ApiKeys.page component
> feat: add ApiKeys.page component

- packages/pn-personafisica-webapp/src/pages/NuovaDelega.page.tsx
> fix: courtesy page icon

- packages/pn-personafisica-webapp/src/component/Contacts/CourtesyContactItem.tsx
- packages/pn-personafisica-webapp/src/component/Contacts/CourtesyContacts.tsx
- packages/pn-personafisica-webapp/src/component/Contacts/__test__/CourtesyContactItem.test.tsx
- packages/pn-personafisica-webapp/src/utils/contacts.utility.ts
https://user-images.githubusercontent.com/100524063/174578619-3e1d34d2-8b28-46ae-b529-ae79f2bbfae4.mov
> feat: add auto fill prefix number

- packages/pn-commons/src/components/Header/Header.tsx
- packages/pn-commons/src/components/Layout/Layout.tsx
- packages/pn-pa-webapp/src/App.tsx
- Fixes ProductSwitch labels order (Area Riservata on top)
Tests run correctly
> fix: PN-1513 labels in product switch are now in the correct order

- packages/pn-personafisica-login/src/pages/login/Login.tsx
- packages/pn-personafisica-login/src/pages/login/__test__/Login.test.tsx
- packages/pn-personafisica-webapp/public/locales/it/common.json
- packages/pn-personafisica-webapp/src/pages/TermsOfService.page.tsx
feat: remove copy about privacy and tos from login page
feat: change copy about tos acceptance
> feat/PN-1761 Accettazione tos copy

- packages/pn-commons/src/utils/__test__/notification.utility.test.ts
- packages/pn-commons/src/utils/notification.utility.ts
Changed cancelled notification copy in pn-commons
> fix: copy cancelled notification

- packages/pn-commons/src/components/NotificationDetail/NotificationDetailDocuments.tsx
- packages/pn-personafisica-webapp/public/locales/it/notifiche.json
- packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx
- changes downloadable_acts text
- adds link to effected notification faq
> fix: change 120 gg disclaimer copy

- packages/pn-personafisica-webapp/public/locales/it/recapiti.json
- packages/pn-personafisica-webapp/src/component/Contacts/CourtesyContactItem.tsx
- packages/pn-personafisica-webapp/src/component/Contacts/CourtesyContactsList.tsx
- packages/pn-personafisica-webapp/src/utils/contacts.utility.ts
Adds block to delete action for phone and email default contacts if contacts of the same type are present
> feat: add block to delete phone and email contacts

- packages/pn-commons/.eslintignore
- packages/pn-commons/.eslintrc.js
- packages/pn-landing-webapp/.eslintignore
- packages/pn-landing-webapp/.eslintrc.js
- packages/pn-pa-webapp/.eslintignore
- packages/pn-pa-webapp/.eslintrc.js
- packages/pn-pa-webapp/src/pages/components/NewNotification/PreliminaryInformations.tsx
- packages/pn-pa-webapp/src/pages/components/Notifications/DesktopNotifications.tsx
- packages/pn-personafisica-login/.eslintignore
- packages/pn-personafisica-login/.eslintrc.js
- packages/pn-personafisica-webapp/.eslintignore
- packages/pn-personafisica-webapp/.eslintrc.js
- packages/pn-personafisica-webapp/src/component/Notifications/DesktopNotifications.tsx
Reverts pagopa/pn-frontend#310
> Revert "Pn 734 fe commit linter su pn frontend"

- README.md
- packages/pn-pa-webapp/buildspec.yaml
- packages/pn-personafisica-login/buildspec.yaml
- packages/pn-personafisica-login/src/components/Layout.tsx
- packages/pn-personafisica-webapp/buildspec.yaml
Change all all assistance email constants to notifichedigitali@assistenza.pagopa.it
> fix: change all assistance email

- packages/pn-landing-webapp/package.json
- packages/pn-pa-webapp/package.json
- packages/pn-personafisica-login/package.json
- packages/pn-personafisica-webapp/package.json
- yarn.lock
Upgrades mui-italia, brings fix to infoblock
> chore: upgrade mui-italia to latest

- packages/pn-landing-webapp/api/data/en.tsx
- packages/pn-landing-webapp/api/data/it.tsx
fix: change copy for landing site (PN-1917)
> fix: change copy for landing site (PN-1917)

- packages/pn-personafisica-login/src/pages/login/SpidSelect.tsx
- packages/pn-personafisica-login/src/pages/login/__test__/SpidSelect.test.tsx
Reverts pagopa/pn-frontend#351
> Revert "Changed method to open SPID login page"

- packages/pn-personafisica-login/src/navigation/routes.tsx
- packages/pn-personafisica-login/src/pages/login/Login.tsx
- packages/pn-personafisica-login/src/pages/login/__test__/Login.test.tsx
- packages/pn-personafisica-login/src/pages/redirect/Redirect.tsx
- packages/pn-personafisica-login/src/pages/redirect/__test__/Redirect.test.tsx
- packages/pn-personafisica-login/src/utils/constants.ts
- packages/pn-personafisica-login/src/utils/storage.ts
- packages/pn-personafisica-webapp/src/navigation/RequireAuth.tsx
- packages/pn-personafisica-webapp/src/navigation/VerifyUser.tsx
- packages/pn-personafisica-webapp/src/navigation/navigation.utility.ts
- change login redirect in personafisica app implementing current url
- add redirect with token and redirect url in login app
- add Redirect page and relative test
- fix login test according to new behaviour
all tests run correctly
> feat: PN-1754 implement relative path login

- packages/pn-pa-webapp/src/App.tsx
- packages/pn-pa-webapp/src/utils/mixpanel.ts
- packages/pn-personafisica-login/src/App.tsx
- packages/pn-personafisica-login/src/utils/mixpanel.ts
- packages/pn-personafisica-webapp/src/App.tsx
- packages/pn-personafisica-webapp/src/utils/mixpanel.ts
- changed target cookies values
- changed mixpanel import from named to default
> fix: change mixpanel imports and target cookies

- packages/pn-pa-webapp/src/api/auth/Auth.api.ts
- packages/pn-pa-webapp/src/api/auth/__test__/Auth.api.test.ts
- packages/pn-personafisica-webapp/src/api/auth/Auth.api.ts
- packages/pn-personafisica-webapp/src/api/auth/__test__/Auth.api.test.ts
- Change tokenExchange API call from get to post
Test run correctly
> fix: change tokenExchange from get to post

- .github/ISSUE_TEMPLATES/bug_report.md
- .github/ISSUE_TEMPLATES/feature_request.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Adds issue templates to pn-frontend
> feat: add issue templates

- package.json
- yarn.lock
Update lerna from 5.5.0 to 5.5.2
> chore: update lerna

- packages/pn-personafisica-webapp/public/locales/it/notifiche.json
- packages/pn-personafisica-webapp/public/locales/it/recapiti.json
- Change copy for activate service banners
Tests run correctly
> fix: change copy for activate service banner

- packages/pn-landing-webapp/src/layout/footer.constants.tsx
add link to accessibility page in landing app
> fix: add link to accessibility page

- packages/pn-landing-webapp/buildspec.yaml
- packages/pn-pa-webapp/buildspec.yaml
- packages/pn-personafisica-login/buildspec.yaml
- packages/pn-personafisica-webapp/buildspec.yaml
Hotfix environment configuration
For each buildspec.yaml it has been added the list of config params for hotfix environment.
Trigger a pipeline build for hotfix environment. Check that the pipeline ends with success. Deploy the artifacts.
> feat(pn-2398): added build list item for hotfix environment

- packages/pn-personafisica-login/src/locales/it/login.json
- packages/pn-personafisica-login/src/pages/login/Login.tsx
- packages/pn-personafisica-login/src/pages/login/__test__/Login.test.tsx
Modified text copy according to Figma. Also modified test too.
> fix: modified copy test in login page. Test edited to new copy text

- aws-cdn-templates/one-cdn.yaml
> Disbled cloudfront waf

- packages/pn-commons/src/components/Header/Header.tsx
- packages/pn-commons/src/components/Layout/Layout.tsx
- packages/pn-pa-webapp/src/pages/ToSAcceptance.page.tsx
- packages/pn-personafisica-webapp/public/locales/en/common.json
- packages/pn-personafisica-webapp/public/locales/it/common.json
- packages/pn-personafisica-webapp/src/App.tsx
- packages/pn-personafisica-webapp/src/pages/ToSAcceptance.page.tsx
Changes AcceptanceToS page design
- Changes AcceptanceToS component design
- Hides ProductHeader component if tos are not accepted
Login with the user leonardo in personafisica webapp, check that product header is not visible, check that spacing is aligned with [figma design](https://www.figma.com/file/HjyZhnoAKbzCbxkmQCGsZw/Piattaforma-Notifiche?node-id=14619%3A97392)
> Fix: PN-2510 grafica pagine accettazione tos

- packages/pn-commons/sonar-project.properties
- packages/pn-commons/sonarqube-scanner.js
- sonar_buildspec.yaml
Moved test pipeline from Amplify to CodeBuild
- Added sonar_buildspec.yaml in the root directory
- Added sonarqube-scanner file in each package
Do an empty push and check test pipeline
> node downgrade

- packages/pn-personafisica-login/src/pages/login/Login.tsx
- packages/pn-personafisica-login/src/pages/login/__tests__/Login.test.tsx
- packages/pn-personafisica-login/src/utils/storage.ts
Restores CIE button
- Restores CIE button
CIE button should now be visible in pn-personafisica-login
> fix: re-enable CIE button

- packages/pn-pa-webapp/src/pages/components/NewNotification/PreliminaryInformations.tsx
Changed the way how groups input in preliminary informations component is validated.
> Chore: modified groups input validation

- packages/pn-pa-webapp/cypress/e2e/NewNotificationAdministratorWithGroups.cy.ts
- packages/pn-pa-webapp/cypress/fixtures/groups/groups.json
- packages/pn-pa-webapp/cypress/fixtures/recipients/recipients.ts
- packages/pn-pa-webapp/cypress/global.d.ts
- packages/pn-pa-webapp/cypress/support/commands.ts
Cypress test new notification with administrator with groups
> Added E2E test for new notification - operator - with groups

- packages/pn-personafisica-login/tsconfig.json
PersonafisicaLogin pacakge doesn't build due to an error in ts compilation
- Changed tsconfig to manage dom typings
Run build for personafisica-login package and check that it ends successfully
> pn-2939 - updated tsconfig to manage dom typings

- packages/pn-commons/src/components/Pagination/CustomPagination.tsx
- packages/pn-commons/src/components/Pagination/__test__/CustomPagination.test.tsx
- packages/pn-pa-webapp/src/pages/__test__/Dashboard.page.test.tsx
- packages/pn-personafisica-webapp/src/pages/__test__/Notifiche.page.test.tsx
I deleted pageSize choose for 100,200,500 and fix test which including pageSize with 100 as 50
- delete pageSize choose for 100,200,500
click on button in the pagination and view on screen only 10,20,50 choose of page size
> refactor: delete pageSize 100,200,500 and fix test of pageSize 50

- packages/pn-personafisica-webapp/cypress.config.ts
- packages/pn-personafisica-webapp/cypress/e2e/NotificationDetail.cy.ts
- packages/pn-personafisica-webapp/cypress/e2e/NotificationFilters.cy.ts
Fix some cypress tests failing in ci (pf)
> test: tweak some cy tests failing in ci (pf)

- packages/pn-commons/package.json
- packages/pn-personafisica-webapp/src/component/NewNotificationBadge/NewNotificationBadge.tsx
- packages/pn-personafisica-webapp/src/component/NewNotificationBadge/__test__/NewNotificationBadge.test.tsx
- yarn.lock
This pr fixes a a11y issue with the "role" property previously assigned to NewNotificationBadge and adds back css-mediaquery dependency which was wrongly removed during last merge.
Run a11y tests and verify everything works smoothly
> fix: change role property in NewNotificationBadge to fix a11y issue

- packages/pn-commons/src/utils/user.utility.ts
- packages/pn-landing-webapp/src/layout/LandingLayout.tsx
- packages/pn-pa-webapp/package.json
- packages/pn-pa-webapp/src/redux/auth/actions.ts
- packages/pn-pa-webapp/src/redux/auth/reducers.ts
- packages/pn-personafisica-webapp/src/component/Contacts/DigitalContactsCodeVerification.context.tsx
- packages/pn-personafisica-webapp/src/navigation/navigation.utility.ts
- packages/pn-personafisica-webapp/src/redux/auth/__test__/initialState_ok.test.ts
- packages/pn-personafisica-webapp/src/redux/auth/actions.ts
- packages/pn-personafisica-webapp/src/redux/auth/reducers.ts
- packages/pn-personafisica-webapp/src/redux/auth/types.ts
- yarn.lock
Updates to aviod xss-attacks
- Yup strict validation before setting/getting user in/from sessionStorage
- Renamed props and setProps in modalProps and setModalProps
- Added noopener to rel attribute
- Removed unused moment
- Removed unused node-fetch
Check that all security issues are resolved
> Feat/pn 3091 - improvements against xss attacks

- packages/pn-pa-webapp/public/locales/it/notifiche.json
Changed Taxonomy id copy in the first step of the new notification flow
- Updated taxonomy-id copy into notifiche.json file
Go to new notification -> check the copy of the taxonomy id field
> New notification copy - fix/pn-4021

- packages/pn-commons/src/components/CustomDropdown.tsx
- packages/pn-personafisica-webapp/src/api/consents/Consents.api.ts
- packages/pn-personafisica-webapp/src/component/Contacts/SpecialContacts.tsx
- packages/pn-personagiuridica-webapp/src/component/Contacts/SpecialContacts.tsx
Reset form after special contact addition
- Reset form in SpecialContacts.tsx (pf and pg)
- Change value of the input when it changes from external in CustomDropdown.tsx
Go to "Recapiti" page -> go to "Altri recapiti" section -> add one contact -> check that the form is resetted and that you can add a new contact under the same party
> More contacts for the same party - fix/pn-3946

- packages/pn-pa-webapp/src/redux/auth/reducers.ts
- packages/pn-personafisica-webapp/src/redux/auth/reducers.ts
- packages/pn-personagiuridica-webapp/src/redux/auth/reducers.ts
New jti validation for pf and pg
- Updated auth/reducers.ts for pf and pg
Check that the login with pf is successful
> updated jti validation for pf and pg

- packages/pn-commons/src/components/NotificationDetail/NotificationDetailDocuments.tsx
Added indexed key component to avoid duplication.
- Added indexed key component to avoid duplication
Open a multi addresse notification and check the web browser console. Now the errors about React key duplication are gone.
> Chore: Added indexed key component to avoid duplication

- packages/pn-personafisica-login/src/utils/IDPS.ts
Added TeamSystem provider to IDPS.
- Added TeamSystem provider to IDPS
You should see TeamSystem provider in IDPS during login.
> Added TeamSystem provider to IDPS

- packages/pn-personafisica-login/src/utils/IDPS.ts
Added Etna provider to IDPS.
- Added Etna provider to IDPS
You should see Etna provider in IDPS during login
> Added Etna provider to IDPS

- packages/pn-pa-webapp/public/locales/it/common.json
- packages/pn-pa-webapp/src/utils/__test__/role.utility.test.ts
- packages/pn-pa-webapp/src/utils/role.utility.ts
Changed roles label to users in side menu
- Updated localization files
Login with pa and check new label
> changed Roles label to Users - pn-4429

- packages/pn-pa-webapp/src/pages/NewApiKey.page.tsx
Fixed bug while creating new api key with group(s).
- Removed some useless props from Autocomplete
- Fixed property to read and send to the API
Use account with user groups and create a new api key. Select one or more group. Now it works instead of getting error 500
> Fixed bug while creating new api key with group(s)

- packages/pn-pa-webapp/public/locales/it/notifiche.json
- packages/pn-pa-webapp/src/pages/NotificationDetail.page.tsx
Adds translations for getDownloadFilesMessage function
- Adds translations for getDownloadFilesMessage function
Check that translations for getDownloadFilesMessage function are retrieved correctly
> feat(PN-4403): adds translations for getDownloadFilesMessage function

- packages/pn-pa-webapp/src/pages/NotificationDetail.page.tsx
Fixes logic for hasDocumentsAvailable in pa-webapp
- fixes logic for hasDocumentsAvailable in pa-webapp
Documents should be available for not cancelled and viewed notification since less than 120 days
> fix(pn-4569): documents availability in pa-webapp

- aws-cdn-templates/dev/env-cdn.sh
added new safestorage link in csp config
> chore: added new safestorage link in csp config

- packages/pn-landing-webapp/.env
- packages/pn-pa-webapp/buildspec.yaml
Changed assistance link in pa-webapp and in landing page, in order to convey assistance requests from PA to correct email adress
- changed .env for landing page
- changed .buildspec end variable for pa-webapp
start pa-webapp and landing and check that assistance link open a mail pop-up with correct email
> chore: fixed assistance email link in landing webapp

- aws-cdn-templates/dev/env-cdn.sh
cambiata la CSP per l'upload degli allegati di una notifica
Creare una nuova notifica manualmetne
> fix: Allineamneto a nuovo nome del bucket

- packages/pn-pa-webapp/src/navigation/routes.const.ts
Fixed issue with GROUPS and also USERS routing.
- Removed useless tag from GROUPS routing
- Removed also useless tag from USERS routing too
The GROUPS link in side menu should correctly works by showing all groups in the first tab.
The USERS link in side menu should correctly works by showing users list.
> Fixed issue with GROUPS and also USERS routing

- packages/pn-pa-webapp/public/conf/env/config.test.json
- packages/pn-pa-webapp/public/conf/env/config.uat.json
- packages/pn-personafisica-login/public/conf/env/config.test.json
- packages/pn-personafisica-login/public/conf/env/config.uat.json
- packages/pn-personafisica-webapp/public/conf/env/config.test.json
- packages/pn-personafisica-webapp/public/conf/env/config.uat.json
- packages/pn-personagiuridica-webapp/public/conf/env/config.test.json
- packages/pn-personagiuridica-webapp/public/conf/env/config.uat.json
Added config uat and test files for the relative environments.
> chore: added all config file for uat and test envs

- packages/pn-personafisica-webapp/public/locales/it/recapiti.json
- packages/pn-personagiuridica-webapp/public/locales/it/recapiti.json
Modified title PEC box in contacts page.
- Title modified from "PEC" to "Recapito legale"
Open contacts page and look for PEC box section. You should not see PEC anymore but "Recapito legale" instead.
> chore: modified title PEC box in contacts page

- packages/pn-personafisica-webapp/src/component/Contacts/LegalContactsList.tsx
- packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json
- packages/pn-personagiuridica-webapp/src/component/DomicileBanner/DomicileBanner.tsx
add in locales pg, domicile_banner  for pec and change them
- create a new domicile for pec
- insert 3 element in messageindex for casual message in the page 
every refresh page you see change domicile banner message
> feature: add copy for domicile banner

- packages/pn-commons/src/utils/string.utility.ts
- packages/pn-pa-webapp/public/locales/it/common.json
- packages/pn-pa-webapp/src/pages/components/NewNotification/Attachments.tsx
- packages/pn-pa-webapp/src/pages/components/NewNotification/PreliminaryInformations.tsx
- packages/pn-pa-webapp/src/pages/components/NewNotification/Recipient.tsx
- packages/pn-pa-webapp/src/pages/components/NewNotification/validation.utility.ts
Added lenght validation to some input in new notification page.
Involved issues:
- PN-5310
- PN-5311
- PN-5312
- PN-5313
- PN-5314
- PN-5315
- PN-5316
- Validation lenghts added according to input from single issues
Try to go further length in inputs, you should see error validation.
> Added lenght validation to some input in new notification page

- packages/pn-commons/src/components/TitleBox.tsx
- packages/pn-personafisica-webapp/src/component/Contacts/CourtesyContacts.tsx
- packages/pn-personafisica-webapp/src/component/Contacts/IOContact.tsx
- packages/pn-personafisica-webapp/src/component/Contacts/InsertLegalContact.tsx
- packages/pn-personafisica-webapp/src/component/Contacts/LegalContactsList.tsx
- packages/pn-personafisica-webapp/src/pages/Contacts.page.tsx
- packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx
- packages/pn-personagiuridica-webapp/src/component/Contacts/CourtesyContacts.tsx
- packages/pn-personagiuridica-webapp/src/component/Contacts/InsertLegalContact.tsx
- packages/pn-personagiuridica-webapp/src/component/Contacts/LegalContactsList.tsx
- packages/pn-personagiuridica-webapp/src/pages/Contacts.page.tsx
insert a11y in contacts page 
- insert in every description of component `aria` attribute 
active voicOver in our MacOS and slide all page with tab button, of keyboard.
> fix: insert a11y in contacts component

- packages/pn-pa-webapp/public/locales/it/notifiche.json
- packages/pn-personafisica-webapp/public/locales/it/notifiche.json
- packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json
New copy for documents and other documents heading line.
All platforms: PA, PF and PG
> Chore: new copy for documents and other documents heading line

- packages/pn-personafisica-webapp/public/locales/it/recapiti.json
- packages/pn-personagiuridica-webapp/public/locales/it/recapiti.json
insert point to end of io message## List of changes proposed in this pull request
view on io message
> fix: inserti point to end of io message

- lerna.json
- packages/pn-pa-webapp/README.md
- packages/pn-pa-webapp/public/conf/env/config.prod.json
- packages/pn-personafisica-login/README.md
- packages/pn-personafisica-login/public/conf/env/config.hotfix.json
- packages/pn-personafisica-login/public/conf/env/config.prod.json
- packages/pn-personafisica-webapp/README.md
- packages/pn-personafisica-webapp/public/conf/env/config.prod.json
- packages/pn-personagiuridica-webapp/README.md
- packages/pn-personagiuridica-webapp/public/conf/env/config.dev.json
- packages/pn-personagiuridica-webapp/public/conf/env/config.prod.json
- packages/pn-personagiuridica-webapp/public/conf/env/config.test.json
- packages/pn-personagiuridica-webapp/public/conf/env/config.uat.json
Added config.prod.json for each webapp.
> chore: added config.json for prod environment with courtesy page on

- packages/pn-pa-webapp/public/conf/env/config.cert.json
- packages/pn-pa-webapp/public/conf/env/config.coll.json
- packages/pn-pa-webapp/public/conf/env/config.cypress.json
- packages/pn-pa-webapp/public/conf/env/config.dev.json
- packages/pn-pa-webapp/public/conf/env/config.hotfix.json
- packages/pn-pa-webapp/public/conf/env/config.prod.json
- packages/pn-pa-webapp/public/conf/env/config.svil.json
- packages/pn-pa-webapp/public/conf/env/config.test.json
- packages/pn-pa-webapp/public/conf/env/config.uat.json
- packages/pn-pa-webapp/public/locales/it/common.json
- packages/pn-pa-webapp/src/App.tsx
- packages/pn-pa-webapp/src/navigation/routes.tsx
- packages/pn-pa-webapp/src/services/configuration.service.ts
- packages/pn-personafisica-webapp/public/locales/it/common.json
- packages/pn-personafisica-webapp/src/App.tsx
- packages/pn-personafisica-webapp/src/navigation/routes.tsx
- packages/pn-personafisica-webapp/src/services/configuration.service.ts
- packages/pn-personagiuridica-webapp/public/locales/it/common.json
- packages/pn-personagiuridica-webapp/src/App.tsx
- packages/pn-personagiuridica-webapp/src/navigation/routes.tsx
- packages/pn-personagiuridica-webapp/src/services/configuration.service.ts
Changed text and link of 'non accessibile' page. Text is different for sender and recipients
- Changed text of non accessibile page
- Changed link of non accessibile page
For sender text start pa and navigate to /non-accessibile page to see the text. Click the link 'visita il sito dedicato' to see the link redirect.
For recipients text start pf and pg and navigate to /non-accessibile page to see the text. Click the link 'visita il sito dedicato' to see the link redirect
> refactor: changed text and link of non accessibile page

- packages/pn-pa-webapp/public/locales/it/apikeys.json
- packages/pn-pa-webapp/src/pages/NewApiKey.page.tsx
Fix size of title in new api key form and fix label's margins.
- Fix size of form title
- Fix label's margins
- Mapped form title in locales
Go to new api key and will see the new form title size and label's margins
> fix: sizes of new api key form

- packages/pn-commons/src/components/Prompt.tsx
Fixed styles in Prompt component.
- Managed padding styles
> Fixed styles in Prompt component

- packages/pn-commons/src/components/EmptyState.tsx
Added 4px of border radius to empty state component 
- Added border radius to empty state
Go to a table and search for a inexistent fiscal code and will appear the empty state component with border radius
> fix: added border radius to empty state

- packages/pn-commons/src/components/ApiError/ApiError.tsx
Include a summary of the changes.
- insert underline in ricarica link
see 'Ricarica' label underlined
> fix: insert underline in ricarica

- packages/pn-commons/src/utils/costants.tsx
- packages/pn-commons/src/utils/index.ts
Changed link of accessibility page on footer
- Changed link of accessibility page
On PA/PF/PG go to footer and click accessibility link
> refactor(PN-6579): changed link of accessibility page

- packages/pn-personafisica-webapp/public/locales/it/notifiche.json
new copy on empty state in pf 
- substitute copy on empty state
you see new copy on empty state in pf notification
> fix: modify copy pg

- packages/pn-personafisica-webapp/public/locales/it/recapiti.json
- packages/pn-personagiuridica-webapp/public/locales/it/recapiti.json
Fixed copy of pop-up after PEC insertion
- Fix copy
Insert a PEC and it will open a pop-up with correct text
> fix: fixed copy of pop-up after PEC insertion

- packages/pn-landing-webapp/api/data/it.tsx
fix typo in enti page for landing webapp
> fix typo in enti page for landing webapp

- packages/pn-pa-webapp/public/locales/it/apikeys.json
- packages/pn-pa-webapp/public/locales/it/common.json
- packages/pn-pa-webapp/public/locales/it/notifiche.json
- packages/pn-pa-webapp/src/pages/NewApiKey.page.tsx
- packages/pn-pa-webapp/src/pages/components/NewNotification/PreliminaryInformations.tsx
Various fixes on copy of notifications and delegations of PA
- Fix copy
- [PN-6078](https://pagopa.atlassian.net/browse/PN-6078) go to homepage of PA
- [PN-6225](https://pagopa.atlassian.net/browse/PN-6225) go to api keys list and click on menu
- [PN-6226](https://pagopa.atlassian.net/browse/PN-6226) click 'Visualizza codice' on menu of api key list
- [PN-6227](https://pagopa.atlassian.net/browse/PN-6227) create a new api key and exit without edit nothing
- [PN-6242](https://pagopa.atlassian.net/browse/PN-6242) create a new notification from a user without any groups 
- [PN-6243](https://pagopa.atlassian.net/browse/PN-6243) create a notification and on subject field insert some initial space to see the error
- [PN-6245](https://pagopa.atlassian.net/browse/PN-6245) create a new …
> fix: various fixes on copy of PA

- packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
- packages/pn-pa-webapp/src/pages/components/ApiKeys/DesktopApiKeys.tsx
align left status column
- change align in left 
see column status in api key on the left
> fix: align left status column

- packages/pn-pa-webapp/public/index.html
- packages/pn-pa-webapp/public/locales/it/common.json
- packages/pn-pa-webapp/src/navigation/RouteGuard.tsx
- packages/pn-pa-webapp/src/navigation/SessionGuard.tsx
- packages/pn-personafisica-login/public/index.html
- packages/pn-personafisica-webapp/public/index.html
- packages/pn-personafisica-webapp/public/locales/it/common.json
- packages/pn-personafisica-webapp/src/navigation/SessionGuard.tsx
- packages/pn-personagiuridica-webapp/public/index.html
- packages/pn-personagiuridica-webapp/public/locales/it/common.json
- packages/pn-personagiuridica-webapp/src/navigation/SessionGuard.tsx
fix on not accessible page copy
> fix: on not accessible page copy

- aws-cdn-templates/one-cdn.yaml
> PN-6856: updated limits for cdn alarms

- packages/pn-commons/src/utils/searchString.utility.ts
- packages/pn-personafisica-webapp/public/locales/it/common.json
- packages/pn-personafisica-webapp/src/component/Contacts/SpecialContacts.tsx
- packages/pn-personagiuridica-webapp/public/locales/it/common.json
- packages/pn-personagiuridica-webapp/src/component/Contacts/SpecialContacts.tsx
Fixed reset of autocomplete ente field in special contacts of PF and PG
- Fix autocomplete ente field
On PF and PG insert a special contacts and once you click the 'Associa' button the field ente should be empty
> fix: reset of ente field in special contacts of PG and PF

- packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
fix padding in dialog apikey
- change padding in dialog rendered
see more padding in all dialog of apikey page
> fix: fix padding in dialog apikey

- packages/pn-personagiuridica-webapp/src/pages/NuovaDelega.page.tsx
Added spacing between blocks
- Spacing between elements
Start PG and go to new delegation page. Divider should have vertical margin of 24px
> fix: added spacing between blocks in new delegation 

- packages/pn-personafisica-login/src/locales/it/login.json
- packages/pn-personafisica-login/src/pages/loginError/LoginError.tsx
- packages/pn-personafisica-login/src/pages/loginError/__tests__/LoginError.test.tsx
Buttons login spid and error handling
- Changed labels of login buttons 
- New error handling
Go to login PF and see the new labels. 
To see the error handling try to login with an IDP and then click "Annulla" button
> fix: buttons login spid and error handling

- aws-cdn-templates/one-cdn.yaml
Small fixed so pnpg CSP and cdn origins
> smal fixes to cdn for pnpg

- packages/pn-commons/src/utils/costants.tsx
fixed accessibility link for webapps
> updated accessibility link

- packages/pn-commons/src/components/AppStatus/AppStatusBar.tsx
- packages/pn-personafisica-webapp/src/pages/Contacts.page.tsx
- packages/pn-personagiuridica-webapp/src/pages/Contacts.page.tsx
add to voiceover status of app and link in contacts page
- add to voiceover status of app
-add to voiceover link in contacts page
with voiceover activated listen banner of status app and link of your personal data
> fix: add a11y

- packages/pn-commons/src/components/CustomMobileDialog/CustomMobileDialog.tsx
- packages/pn-commons/src/components/CustomMobileDialog/CustomMobileDialogAction.tsx
- packages/pn-pa-webapp/src/pages/components/Notifications/FilterNotifications.tsx
- packages/pn-pa-webapp/src/pages/components/Notifications/FilterNotificationsFormActions.tsx
- packages/pn-pa-webapp/src/pages/components/Notifications/FilterNotificationsFormBody.tsx
- packages/pn-personafisica-webapp/src/component/Notifications/FilterNotifications.tsx
- packages/pn-personafisica-webapp/src/component/Notifications/FilterNotificationsFormActions.tsx
- packages/pn-personafisica-webapp/src/component/Notifications/FilterNotificationsFormBody.tsx
- packages/pn-personafisica-webapp/src/component/Notifications/__test__/FilterNotifications.test.tsx
- packages/pn-personagiuridica-webapp/src/component/Notifications/FilterNotifications.tsx
- packages/pn-personagiuridica-webapp/src/component/Notifications/FilterNotificationsFormActions.tsx
- packages/pn-personagiuridica-webapp/src/component/Notifications/FilterNotificationsFormBody.tsx
- packages/pn-personagiuridica-webapp/src/component/Notifications/__test__/FilterNotifications.test.tsx
Validate IUN after submitting the notification filter form on PF and PG
- FIx validations mode of notifications filters
In PF and PG, try to insert an invalid IUN and click the 'apply' button. You should see the validation error
> fix: validation mode of notifications filter

- packages/pn-personafisica-webapp/public/locales/it/deleghe.json
- packages/pn-personafisica-webapp/src/pages/NuovaDelega.page.tsx
- packages/pn-personagiuridica-webapp/public/locales/it/deleghe.json
- packages/pn-personagiuridica-webapp/src/pages/NuovaDelega.page.tsx
- packages/pn-personagiuridica-webapp/src/pages/__test__/NuovaDelega.page.test.tsx
insert validation on enti selected
- modify validation in yup schema
- insert message error for enti not selected 
when you create a new delegation and not select at least one ente you shouldn't create a new delegation
> fix: insert validation on enti selected

- packages/pn-personagiuridica-webapp/src/redux/delegation/reducers.ts
PG - fixed pagination for the delegations list
- Manage nextPagesKey array stored in the redux slice
Login with LucioAnneoSeneca - LuAnSe SpA in dev environment - go to delegations and check if pagination works properly (delegations are about 600)
> deleghe pagination - pn-7130

- packages/pn-personafisica-webapp/public/locales/it/deleghe.json
- packages/pn-personagiuridica-webapp/public/locales/it/deleghe.json
Changed copy of succesfull delegation creation
- Changed copy
When creating a new delegation you should see the new message of successfull request
> fix: changed copy of successfull delegation creation

- packages/pn-landing-webapp/api/data/it/PA.tsx
- packages/pn-landing-webapp/api/data/it/PF.tsx
Rework copy of enti and cittadini sections on landing webapp
- Changed copy
Start landing and go to "Scopri come aderire" section of enti and on cittadini go to "APP IO" section
> fix: rework copy of landing webapp

- packages/pn-commons/src/navigation/AccessDenied.tsx
Added side padding to AccessDenied component.
- Set padding to 4
This fixes texts too close to most mobile devices display border.
> Added side padding

- packages/pn-commons/src/components/AppStatus/MobileDowntimeLog.tsx
Fixed alignment of card's chips on App Status page
- Set alignment of chips to left
Start PA and go to App Status page with mobile view
> fix: alignment of chip in AppStatus

- aws-cdn-templates/one-cdn.yaml
CSP blocks the logo's download of a PG. Added the rule into csp
- Updated one-cdn.yaml
> added pnpg path to csp - pn-7195

- packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
- packages/pn-pa-webapp/src/pages/components/ApiKeys/ApiKeyModal.tsx
Refactored API Keys modals.
- Using some Dialogs related components
> Pn 7124 ds bug UI pg dialog mobile pa mittente

- packages/pn-commons/src/components/Prompt.tsx
Fixed Prompt dialog in mobile.
- Fixed Prompt dialog texts and buttons
The prompt dialog use when you want cancel api key creation or notification should be correct now..
> Fixed Prompt dialog in mobile

- packages/pn-validator/src/Validator.ts
- packages/pn-validator/src/ValidatorBuilder.ts
- packages/pn-validator/src/__test__/Validator.test.ts
- packages/pn-validator/src/ruleValidators/ArrayRuleValidator.ts
- packages/pn-validator/src/ruleValidators/BooleanRuleValidator.ts
- packages/pn-validator/src/ruleValidators/CommonRuleValidator.ts
- packages/pn-validator/src/ruleValidators/DateRuleValidator.ts
- packages/pn-validator/src/ruleValidators/NumberRuleValidator.ts
- packages/pn-validator/src/ruleValidators/ObjectRuleValidator.ts
- packages/pn-validator/src/ruleValidators/StringRuleValidator.ts
- packages/pn-validator/src/rules/ForEachElement.ts
- packages/pn-validator/src/rules/IsObject.ts
- packages/pn-validator/src/types/ValidatorOptions.ts
- packages/pn-validator/src/utility/__test__/isMissingRules.test.ts
- packages/pn-validator/src/utility/isMissingRules.ts
Add ValidatorOptions interface and related tests
- Added a new interface ValidatorOptions to provide options for the Validator class.
- Updated the Validator constructor to accept the ValidatorOptions object.
- Implemented tests to ensure the options are working correctly in different scenarios.
It can be tested by implementing the new option or just by running the test.
> Add ValidatorOptions interface and related tests

- packages/pn-commons/__mocks__/ExternalRegistry.mock.ts
- packages/pn-commons/__mocks__/NotificationDetail.mock.ts
- packages/pn-commons/src/types/NotificationDetail.ts
- packages/pn-commons/src/utils/__test__/notification.utility.test.ts
- packages/pn-commons/src/utils/__test__/test-utils.ts
- packages/pn-commons/src/utils/notification.utility.ts
Implemented a mapper function that generates an array of useful information about payments
- Implemented function `populatePaymentHistory`
- Fixed and added tests about that function
> feat: impletended mapper function to generate payment information

- packages/pn-commons/src/components/AppMessage.tsx
- packages/pn-commons/src/components/FileUpload.tsx
- packages/pn-commons/src/components/NotificationDetail/NotificationDetailDocuments.tsx
- packages/pn-commons/src/components/NotificationDetail/NotificationDetailTable.tsx
- packages/pn-commons/src/components/NotificationDetail/NotificationDetailTimeline.tsx
- packages/pn-commons/src/components/NotificationDetail/NotificationDetailTimelineStep.tsx
- packages/pn-commons/src/components/Notifications/StatusTooltip.tsx
- packages/pn-commons/src/components/Pagination/CustomPagination.tsx
- packages/pn-commons/src/components/Prompt.tsx
- packages/pn-commons/src/components/SectionHeading.tsx
- packages/pn-commons/src/components/SnackBar/SnackBar.tsx
- packages/pn-pa-webapp/src/pages/NewApiKey.page.tsx
- packages/pn-pa-webapp/src/pages/NewNotification.page.tsx
- packages/pn-pa-webapp/src/pages/components/NewApiKey/SyncFeedbackApiKey.tsx
- packages/pn-pa-webapp/src/pages/components/NewNotification/SyncFeedback.tsx
- packages/pn-personafisica-webapp/src/component/Deleghe/ConfirmationModal.tsx
- packages/pn-personafisica-webapp/src/pages/NuovaDelega.page.tsx
- packages/pn-personagiuridica-webapp/src/pages/NuovaDelega.page.tsx
insert id in html on many file
- inser id
view on inspect file id missing in html
> feature: inser id in html for e2e test

- packages/pn-personafisica-login/public/locales/it/login.json
- packages/pn-personafisica-login/src/pages/login/SpidSelect.tsx
added namespace to spid select page to fix missing translation
> fix: added namespace to login page

- packages/pn-pa-webapp/src/pages/components/NewNotification/PreliminaryInformations.tsx
Hotfix for regression
- Moved InfoTooltip variable outside component PreliminaryInformations to prevent "Maximum update depth" error
> Chore: Hotfix for regression

- packages/pn-personafisica-webapp/public/locales/it/common.json
- packages/pn-personagiuridica-webapp/public/locales/it/common.json
Changed copy for ToS page.
- PF
- PG
> Changed copy for ToS page

- packages/pn-personagiuridica-webapp/public/locales/de/deleghe.json
- packages/pn-personagiuridica-webapp/public/locales/en/deleghe.json
- packages/pn-personagiuridica-webapp/public/locales/fr/deleghe.json
- packages/pn-personagiuridica-webapp/public/locales/it/deleghe.json
- packages/pn-personagiuridica-webapp/public/locales/sl/deleghe.json
- packages/pn-personagiuridica-webapp/src/pages/NuovaDelega.page.tsx
Added missing translation key.
- Added missing translation key in all PG languages
- Reordered imports of NuovaDelega.page.tsx
Login user without entities or edit file to give empty array then open entities dropdown. The message will correctly been shown.
> Added missing translation key, reodered imports

- packages/pn-commons/src/index.ts
- packages/pn-pa-webapp/src/pages/__test__/Dashboard.page.test.tsx
- packages/pn-pa-webapp/src/pages/__test__/NewApiKey.page.test.tsx
- packages/pn-pa-webapp/src/pages/components/NewNotification/__test__/PreliminaryInformations.test.tsx
- packages/pn-pa-webapp/src/pages/components/Notifications/__test__/FilterNotifications.a11y.test.tsx
- packages/pn-pa-webapp/src/pages/components/Notifications/__test__/FilterNotifications.test.tsx
- packages/pn-pa-webapp/src/pages/components/Notifications/__test__/MobileNotifications.test.tsx
The rework on pa tests causes errors in pf and pg tests
- Removed the exports in pn-commons index.ts file
- Updated the imports in pa tests
Run tests for all webapp and check that there aren't problems
> fixed errors due to export in pn-commons

- packages/pn-personagiuridica-webapp/src/utils/__test__/delegation.utility.test.ts
- packages/pn-personagiuridica-webapp/src/utils/delegation.utility.ts
Run pg tests and check that no one fails
> fix pg failing tests

- packages/pn-pa-webapp/public/conf/env/config.dev.json
- packages/pn-personafisica-webapp/public/conf/env/config.dev.json
- packages/pn-personagiuridica-webapp/public/conf/env/config.dev.json
fixed some endpoints for dev config (landing site, webapi and login)
> chore: fixed some endpoints for dev config

- packages/pn-personafisica-login/public/locales/en/common.json
- packages/pn-personafisica-webapp/public/locales/de/common.json
- packages/pn-personafisica-webapp/public/locales/en/common.json
- packages/pn-personafisica-webapp/public/locales/fr/common.json
- packages/pn-personafisica-webapp/public/locales/it/common.json
- packages/pn-personafisica-webapp/public/locales/sl/common.json
- packages/pn-personagiuridica-webapp/public/locales/de/common.json
- packages/pn-personagiuridica-webapp/public/locales/en/common.json
- packages/pn-personagiuridica-webapp/public/locales/fr/common.json
- packages/pn-personagiuridica-webapp/public/locales/it/common.json
- packages/pn-personagiuridica-webapp/public/locales/sl/common.json
Fixed typo "informaativa" in footer with "informativa"
> fix: fixed some typo in footer

- packages/pn-personafisica-webapp/public/locales/it/deleghe.json
- packages/pn-personagiuridica-webapp/public/locales/it/deleghe.json
change copy for delegation already exist for an ente
delegate same pf with same ente
> refactor: chagne copy

- packages/pn-commons/src/components/TitleBox.tsx
- packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx
- packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx
fix id in title box componente
- insert backtick with title prop used in this
> fix id in title box componente

- packages/pn-personafisica-webapp/src/component/Notifications/NotificationPayment.tsx
- packages/pn-personafisica-webapp/src/component/Notifications/__test__/NotificationPayment.test.tsx
- packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json
- packages/pn-personagiuridica-webapp/src/component/Notifications/NotificationPayment.tsx
- packages/pn-personagiuridica-webapp/src/component/Notifications/__test__/NotificationPayment.test.tsx
change copy for payment 
- change copy for payment
> fix : fix copy on payment and him test

- packages/pn-commons/src/components/NotificationDetail/NotificationPaymentPagoPAItem.tsx
- packages/pn-commons/src/components/NotificationDetail/NotificationPaymentRecipient.tsx
- packages/pn-commons/src/components/NotificationDetail/__test__/NotificationPaymentPagoPAItem.test.tsx
- packages/pn-commons/src/components/NotificationDetail/__test__/NotificationPaymentRecipient.test.tsx
- packages/pn-commons/src/types/index.ts
- packages/pn-commons/src/utils/notification.utility.ts
- packages/pn-personafisica-webapp/src/__mocks__/NotificationDetail.mock.ts
- packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx
- packages/pn-personafisica-webapp/src/redux/notification/__test__/reducers.test.ts
- packages/pn-personafisica-webapp/src/redux/notification/reducers.ts
- packages/pn-personagiuridica-webapp/src/__mocks__/NotificationDetail.mock.ts
- packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx
- packages/pn-personagiuridica-webapp/src/redux/notification/__test__/reducers.test.ts
- packages/pn-personagiuridica-webapp/src/redux/notification/reducers.ts
Payments handling when notification is cancelled
- Payments handling when notification is cancelled
> Payments with cancelled notification - PN-7507

- packages/pn-commons/src/utility/costants.tsx
update links to Società Trasparente and Modello231 in footer (file: /packages/pn-commons/src/utility/costants.tsx)
> fix(PN-8100): fixed links in footer for Società Trasparente and Modello231

- packages/pn-commons/src/utility/costants.tsx
- packages/pn-personafisica-webapp/public/locales/it/recapiti.json
Fixed copy in legal-contacts description in italian translation for pf
- Fixed copy in italian translation in recapiti.json for description in legal-contacts
> PN-8128: [FE] fixed copy destinatario sezione recapiti box recapito legale

- packages/pn-personafisica-login/src/utility/IDPS.ts
- packages/pn-personafisica-login/src/utility/__test__/IDPS.test.tsx
Added Intesi Group in IDP list.
- Added Intesi Group in IDP list
- Added new item in array test.
During SPID Login you should see another IDP named Intesi Group now.
> Pn 8255 fe aggiunta dell idp intesi group nella pagina di login

- packages/pn-pa-webapp/src/components/ApiKeys/DesktopApiKeys.tsx
- packages/pn-pa-webapp/src/components/Notifications/DesktopNotifications.tsx
- packages/pn-pa-webapp/src/components/Notifications/MobileNotifications.tsx
- packages/pn-personafisica-webapp/src/components/Deleghe/Delegates.tsx
- packages/pn-personafisica-webapp/src/components/Deleghe/MobileDelegates.tsx
- packages/pn-personafisica-webapp/src/components/Notifications/DesktopNotifications.tsx
- packages/pn-personafisica-webapp/src/components/Notifications/MobileNotifications.tsx
- packages/pn-personagiuridica-webapp/src/components/Deleghe/DelegatesByCompany.tsx
- packages/pn-personagiuridica-webapp/src/components/Deleghe/DelegationsOfTheCompany.tsx
- packages/pn-personagiuridica-webapp/src/components/Notifications/DesktopNotifications.tsx
- packages/pn-personagiuridica-webapp/src/components/Notifications/MobileNotifications.tsx
Fixed button font style inside EmptyState component.
- Added missing variant prop
In EmptyState with button links which had Arial font, now it will have the proper one.
> Fix EmptyState button font style

- packages/pn-pa-webapp/.env
- packages/pn-pa-webapp/public/conf/env/config.dev.json
- packages/pn-pa-webapp/public/conf/env/config.hotfix.json
- packages/pn-pa-webapp/public/conf/env/config.prod.json
- packages/pn-pa-webapp/public/conf/env/config.test.json
- packages/pn-pa-webapp/public/conf/env/config.uat.json
- packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
- packages/pn-pa-webapp/src/services/configuration.service.ts
Configurated apikey link to api in PA
- configurated apikey link to api in PA in config.json
Login in PA and go to "ApiKey" Section. Click on "invio notifiche" and on "accesso alle informazioni" to check links.
> feat(PN-8368): configurated apikey api link in PA in config.json

- packages/pn-pa-webapp/src/api/notifications/__test__/notifications.routes.test.ts
- packages/pn-pa-webapp/src/api/notifications/notifications.routes.ts
Fix api version
- Fix route and test
On PA try to cancel a notification
> fix: version of cancel notification api

- packages/pn-pa-webapp/public/locales/en/common.json
- packages/pn-pa-webapp/public/locales/en/notifiche.json
- packages/pn-personafisica-login/public/locales/en/common.json
- packages/pn-personafisica-webapp/public/locales/en/common.json
- packages/pn-personafisica-webapp/public/locales/en/deleghe.json
- packages/pn-personafisica-webapp/public/locales/en/notifiche.json
- packages/pn-personafisica-webapp/public/locales/en/profilo.json
- packages/pn-personagiuridica-webapp/public/locales/en/common.json
- packages/pn-personagiuridica-webapp/public/locales/en/deleghe.json
- packages/pn-personagiuridica-webapp/public/locales/en/notifiche.json
- packages/pn-personagiuridica-webapp/public/locales/en/profilo.json
Replaced tax code text with fiscal code.
- English translation strings replaced
- 
Just see for Fiscal Code everywhere. You should'n see Tax Code anymore.
> Replaced tax code text with fiscal code

- packages/pn-commons/src/components/PnDialog/PnDialogActions.tsx
- packages/pn-commons/src/components/PnDialog/__test__/PnDialogActions.test.tsx
- packages/pn-personafisica-webapp/src/components/Deleghe/ConfirmationModal.tsx
- packages/pn-personafisica-webapp/src/pages/__test__/Deleghe.page.test.tsx
Fixed issue with ConfirmationModal height.
The issue described was actually related to the height of the modal, there was missing padding bottom in the buttons. Also moved xs param to the container instead. This fixed the height of the modal.
> Fixed issue with ConfirmationModal height

- packages/pn-commons/src/components/NotificationDetail/NotificationPaymentRecipient.tsx
- packages/pn-personafisica-webapp/public/locales/it/notifiche.json
- packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json
Added copy for single payment notification
- Added copy
Go to a notification with single payment and see subtitle of box
> PN-8835 - Subtitle copy when having a single payment

- packages/pn-commons/src/utility/mixpanel.utility.ts
Removed loaded method from mixpanel init.
> Removed loaded method from mixpanel

- packages/pn-pa-webapp/src/__mocks__/User.mock.ts
- packages/pn-pa-webapp/src/api/external-registries/External-registries.api.ts
- packages/pn-pa-webapp/src/redux/auth/__test__/reducers.test.ts
Fix url when changing product from products switch of PA. 
- Added product id on url based on server response
On UAT with baldassarremazza (Comune di Milano) try to switch to Carta Giovani
> PN-9001 - Product id on url of product switch

- packages/pn-commons/src/components/NotificationDetail/NotificationPaymentRecipient.tsx
- packages/pn-commons/src/components/NotificationDetail/NotificationPaymentTitle.tsx
- packages/pn-commons/src/components/NotificationDetail/__test__/NotificationPaymentRecipient.test.tsx
Removed title when all payments are paid
- Hide title when all payments are paid
Go to a notification with all payments paid and check that there's no title. 
Es. DHKR-QEHM-YMNJ-202312-P-1 on UAT (PF / Ada)
> PN-8912 - Removed title when all payments are paid

- packages/pn-pa-webapp/public/locales/de/apikeys.json
- packages/pn-pa-webapp/public/locales/en/apikeys.json
- packages/pn-pa-webapp/public/locales/fr/apikeys.json
- packages/pn-pa-webapp/public/locales/it/apikeys.json
- packages/pn-pa-webapp/public/locales/sl/apikeys.json
- packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
Refactored Subtitle in API Keys page. The mini component has been removed since it was simplified.
- Component Subtitle removed and replaced with simple Trans component
- subtitle property in apikeys.json in any language has been converted from object to string
No visible differences should occurs.
> Refactored Subtitle

- packages/pn-commons/src/components/NotificationDetail/NotificationRelatedDowntimes.tsx
- packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx
Fixed issue with mixpanel event SEND_NOTIFICATION_DETAIL.
> Fixed issue with mixpanel event

- packages/pn-personafisica-login/src/utility/mixpanel.ts
- yarn.lock
Re-enabled mixpanel tracking for portale login
> chore: enabled mixpanel tracking for portale login

- packages/pn-pa-webapp/public/conf/env/config.dev.json
- packages/pn-pa-webapp/public/conf/env/config.hotfix.json
- packages/pn-pa-webapp/public/conf/env/config.prod.json
- packages/pn-pa-webapp/public/conf/env/config.test.json
- packages/pn-pa-webapp/public/conf/env/config.uat.json
replaced API_B2B_LINK value in config file for all PA environments
Check in each config file in /pn-pa-webapp/public/conf/env/ if the variable API_B2B_LINK has https://developer.pagopa.it/send/api#/ as value
> fix(PN-9659): replaced API_B2B_LINK value in config file 

- cra_buildspec.yaml
- sonar_buildspec.yaml
Updated nodejs version in codebuilders to 18.
Check that the pipelines works and the artifact is built properly
> chore: updated nodejs version in codebuilders

- CHANGELOG.md
- lerna.json
- packages/pn-commons/CHANGELOG.md
- packages/pn-commons/package.json
- packages/pn-pa-webapp/CHANGELOG.md
- packages/pn-pa-webapp/package.json
- packages/pn-personafisica-login/CHANGELOG.md
- packages/pn-personafisica-login/package.json
- packages/pn-personafisica-login/public/conf/env/config.prod.json
- packages/pn-personafisica-login/src/pages/login/SpidSelect.tsx
- packages/pn-personafisica-webapp/CHANGELOG.md
- packages/pn-personafisica-webapp/package.json
- packages/pn-personagiuridica-webapp/CHANGELOG.md
- packages/pn-personagiuridica-webapp/package.json
- packages/pn-validator/CHANGELOG.md
- packages/pn-validator/package.json
Reverts pagopa/pn-frontend#1136
> Revert "v2.3.1-RC.0"

- packages/pn-pa-webapp/src/index.css
- packages/pn-personafisica-login/src/index.css
- packages/pn-personafisica-webapp/src/index.css
- packages/pn-personagiuridica-webapp/src/index.css
fix line-height in Informativa privacy titles for PG/PF/PA
Start server as PF/PG/PA, _as mobile_ click on footer "Informativa privacy" and check inferior headings has legible line-height
> fix(PN-6685): fix line-height in Informativa privacy titles for PG/PF/PA

- packages/pn-pa-webapp/src/App.tsx
- update link assistenza when logged for PA with product id as query param
Login as PA, click on "assistenza" and check it redirect to help page
> fix(PN-10111): update link assistenza when logged for PA

- CHANGELOG.md
- lerna.json
- packages/pn-commons/CHANGELOG.md
- packages/pn-commons/package.json
- packages/pn-commons/src/components/CodeModal/CodeModal.tsx
- packages/pn-pa-webapp/CHANGELOG.md
- packages/pn-pa-webapp/package.json
- packages/pn-personafisica-login/CHANGELOG.md
- packages/pn-personafisica-login/package.json
- packages/pn-personafisica-webapp/CHANGELOG.md
- packages/pn-personafisica-webapp/package.json
- packages/pn-personafisica-webapp/public/locales/it/common.json
- packages/pn-personafisica-webapp/public/locales/it/recapiti.json
- packages/pn-personagiuridica-webapp/CHANGELOG.md
- packages/pn-personagiuridica-webapp/package.json
- packages/pn-personagiuridica-webapp/public/locales/it/common.json
- packages/pn-personagiuridica-webapp/public/locales/it/recapiti.json
- packages/pn-validator/CHANGELOG.md
- packages/pn-validator/package.json
> v2.4.1-RC.0

- packages/pn-commons/package.json
- packages/pn-pa-webapp/package.json
- packages/pn-personafisica-login/package.json
- packages/pn-personafisica-webapp/package.json
- packages/pn-personagiuridica-webapp/package.json
- yarn.lock
Upgrade mui-italia to 1.3.0 version
> chore(PN-8805): update mui-italia's version

- packages/pn-pa-webapp/src/components/NewApiKey/SyncFeedbackApiKey.tsx
reduce width of field for apikey code
- reduced field width
- added margin to box and button
Login as PA and go to apikeys page. Generate a new key and check code field fits in the window
> fix(PN-9023): reduce width of field for apikey code

- packages/pn-personafisica-login/src/pages/login/SpidSelect.tsx
- packages/pn-personafisica-login/src/pages/success/Success.tsx
- packages/pn-personafisica-webapp/src/App.tsx
Add traceId to SEND_TOAST_ERROR and moved SEND_LOGIN_METHOD after login success
> chore: add traceId to SEND_TOAST_ERROR and moved SEND_LOGIN_METHOD after login success

- packages/pn-pa-webapp/src/api/statistics/statistics.mock-3.ts
- packages/pn-pa-webapp/src/utility/StatisticsData/StatisticsDataFactory.ts
resolve type error cycling through every StatisticsData concrete class and calling the polymorph getData() method
> fix: Statistics type error

- packages/pn-pa-webapp/src/components/NewNotification/__test__/Attachments.test.tsx
- packages/pn-pa-webapp/src/redux/newNotification/__test__/reducers.test.ts
- packages/pn-pa-webapp/src/redux/newNotification/actions.ts
Removed useless request parameter that generates a Bad Request exception during preload api calling
- Updated newNotification/actions.ts file
- Updated tests
Try to create a new notification
> fixed preload request error - pn-10941

- packages/pn-commons/src/pages/AccessDenied.tsx
- packages/pn-personafisica-login/src/pages/login/Login.tsx
Add aria label and h1 on login page
- Add aria label and h1 on login page
Start PF and PG and read page with VoiceOver
> PN-11331 - Add aria label and h1 on login page

- packages/pn-commons/src/components/PnBreadcrumb.tsx
Add `aria-current` on breadcrumb
- Add `aria-current` on breadcrumb
PS. The issue [PN-11329](https://pagopa.atlassian.net/browse/PN-11329) has many problems, but they have already been resolved in other issues.
[PN-11329]: https://pagopa.atlassian.net/browse/PN-11329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PN-11329 - `aria-current` on breadcrumb

- packages/pn-pa-webapp/openapitools.json
- packages/pn-personafisica-webapp/openapitools.json
- packages/pn-personafisica-webapp/src/__mocks__/Contacts.mock.ts
- packages/pn-personafisica-webapp/src/components/Contacts/__test__/SpecialContacts.test.tsx
- packages/pn-personafisica-webapp/src/generated-client/digital-addresses/api.ts
- packages/pn-personafisica-webapp/src/models/contacts.ts
- packages/pn-personafisica-webapp/src/redux/contact/actions.ts
- packages/pn-personagiuridica-webapp/openapitools.json
- packages/pn-personagiuridica-webapp/src/__mocks__/Contacts.mock.ts
- packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/SpecialContacts.test.tsx
- packages/pn-personagiuridica-webapp/src/generated-client/digital-addresses/api.ts
- packages/pn-personagiuridica-webapp/src/models/contacts.ts
- packages/pn-personagiuridica-webapp/src/redux/contact/actions.ts
filter out these addresses that have codeValid set to false
- Added filter into contact action file (PF/PG)
- Updated auto generated clients
- Updated presentation layer model
Login with pf -> go to contacts page -> add a PEC and, when otp is requested, click on cancel -> refresh the page and check that the user can add another PEC -> try to add other contacts and check that everything is ok
Login with pg -> go to contacts page -> add a PEC and, when otp is requested, click on cancel -> refresh the page and check that the user can add another PEC -> try to add other contacts and check that everything is ok
> filter out these addresses that have codeValid set to false - pn-11554

- packages/pn-personafisica-webapp/src/validators/PersonValidator.ts
- packages/pn-validator/src/Validator.ts
- packages/pn-validator/src/ruleValidators/ObjectRuleValidator.ts
- packages/pn-validator/src/rules/InnerValidator.ts
- packages/pn-validator/src/types/TypeRules.ts
Fix validation on optional object
- Changed type for `isObject` property
> PN-8849 - Validation on optional object

- packages/pn-commons/package.json
- packages/pn-pa-webapp/package.json
- packages/pn-personafisica-login/package.json
- packages/pn-personafisica-webapp/package.json
- packages/pn-personafisica-webapp/src/components/Deleghe/DelegationsElements.tsx
- packages/pn-personagiuridica-webapp/package.json
- packages/pn-personagiuridica-webapp/src/components/Deleghe/DelegationsElements.tsx
- yarn.lock
Added min and max width to DelegationsElements for pf and pg
- Login as PF; create a delegation for selected institutions (be sure to have the longest institution as shown in table as in tooltip) and check institution name is wrapped when too long. 
- Login as PG; create a delegation for selected institutions (be sure to have the longest institution as shown in table as in tooltip) and check institution name is wrapped when too long.
> fix/PN-11618: Added min and max width to DelegationsElements for pf and pg

- packages/pn-commons/src/components/AppStatus/DowntimeLogDataSwitch.tsx
- packages/pn-commons/src/components/AppStatus/__test__/DesktopDowntimeLog.test.tsx
- packages/pn-commons/src/components/AppStatus/__test__/MobileDowntimeLog.test.tsx
Fix color of chips in AppStatus page of PF/PG/PA
- Add color property on Chip component
Start PF/PG/PA, go to app status page and verify that chips has the right color
> PN-12098 - AppStatus chips color

- packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx
- packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx
Apply translations on breadcrumb when change language from footer
- Add `i18n` on `useMemo` dependencies
Start PF/PG/PA and go to notification detail. Then, change language from Footer and verify that breadcrumb is properly translated
> PN-12097 - Translations on breadcrumb

- packages/pn-personafisica-webapp/src/components/Contacts/EditDigitalContact.tsx
- packages/pn-personafisica-webapp/src/components/Contacts/IOContact.tsx
- packages/pn-personafisica-webapp/src/components/Contacts/PecContactItem.tsx
- packages/pn-personagiuridica-webapp/src/components/Contacts/EditDigitalContact.tsx
- packages/pn-personagiuridica-webapp/src/components/Contacts/PecContactItem.tsx
Reowrked the layout of EditDigitalContact
- Upadated EditDigitalContact
Login with pf/pg -> go to Recapiti page -> check the layout
> reworked layout of EditDigitalContact - pn-12405

- packages/pn-personagiuridica-webapp/src/components/Notifications/GroupSelector.tsx
fix allignment  button with title of page when has in mobile phone
insert condition with mobile hook in margin x for button
> fix allignment

- aws-cdn-templates/one-cdn.yaml
In this pr change is required on the cdn for SelfCareHeaderPolicy and DefaultHeaderPolicy in the Content Security section on the frameAncestor value.
set ancestors null
> modify directive frame-ancestor

- packages/pn-pa-webapp/openapitools.json
- packages/pn-pa-webapp/src/components/Notifications/__test__/FilterNotifications.test.tsx
- packages/pn-personafisica-webapp/openapitools.json
- packages/pn-personafisica-webapp/src/components/Notifications/__test__/FilterNotifications.test.tsx
- packages/pn-personagiuridica-webapp/openapitools.json
- packages/pn-personagiuridica-webapp/src/components/Notifications/__test__/FilterNotifications.test.tsx
Updated bff dependencies to the last tag
- Updated openapi files (pa/pf/pg)
Move to pa/pf/pg -> run yarn generate -> run test -> check that everything is ok
> updated bff dependencies

- packages/pn-commons/src/utility/costants.tsx
Updated accessibility link with last version of Dichiarazione di accessibilità
Check that each webapp shows correct link in footer
> fix: update accessibility link with last version

- packages/pn-personagiuridica-webapp/public/conf/env/config.dev.json
- packages/pn-personagiuridica-webapp/public/conf/env/config.hotfix.json
- packages/pn-personagiuridica-webapp/public/conf/env/config.prod.json
- packages/pn-personagiuridica-webapp/public/conf/env/config.test.json
- packages/pn-personagiuridica-webapp/public/conf/env/config.uat.json
- packages/pn-personagiuridica-webapp/src/services/configuration.service.ts
Add `IS_B2B_ENABLED` configuration variable 
- Add `IS_B2B_ENABLED`
> PN-12777- Feature flag for B2B enabled on PG

- packages/pn-pa-webapp/openapitools.json
- packages/pn-personafisica-webapp/openapitools.json
- packages/pn-personagiuridica-webapp/openapitools.json
- packages/pn-personagiuridica-webapp/src/redux/contact/actions.ts
Updated bff dependencies
- Updated openapi tools files
- Migrated to new pg tos acceptance api
Generate clients (pa/pf/pg) - run tests - check that everything is ok
> updated bff dependencies - pn-12392

- packages/pn-personafisica-webapp/public/locales/it/recapiti.json
- packages/pn-personagiuridica-webapp/public/locales/it/recapiti.json
Update PEC disclaimer message
- Update localization files
> Hotfix v2.7.1 - Update PEC disclaimer message (PN-12893)

- packages/pn-commons/src/components/NotificationDetail/NotificationDetailTimelineStep.tsx
- packages/pn-commons/src/models/NotificationDetail.ts
- packages/pn-commons/src/utility/notification.utility.ts
- packages/pn-pa-webapp/openapitools.json
- packages/pn-pa-webapp/public/locales/it/notifiche.json
- packages/pn-pa-webapp/src/pages/NotificationDetail.page.tsx
- packages/pn-pa-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
- packages/pn-pa-webapp/src/redux/notification/__test__/reducers.test.ts
- packages/pn-pa-webapp/src/redux/notification/actions.ts
- packages/pn-personafisica-webapp/openapitools.json
- packages/pn-personafisica-webapp/public/locales/it/notifiche.json
- packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx
- packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
- packages/pn-personafisica-webapp/src/redux/notification/__test__/reducers.test.ts
- packages/pn-personafisica-webapp/src/redux/notification/actions.ts
- packages/pn-personagiuridica-webapp/openapitools.json
- packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json
- packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx
- packages/pn-personagiuridica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
- packages/pn-personagiuridica-webapp/src/redux/notification/__test__/reducers.test.ts
- packages/pn-personagiuridica-webapp/src/redux/notification/actions.ts
Show notification cancelled document in timeline 
- Add document in timeline
Start PF/PG/PA and go to a cancelled notification and verify that the document titled "Dichiarazione annullamento notifica" is available for download.
> PN-12922 - Show notification cancelled document in timeline 

- packages/pn-personagiuridica-webapp/src/pages/ApiIntegration.page.tsx
insert fix for virtual key which must not be seen if the public keys do not exist
- insert check for render virutal key
when you arrive in integration page and if not exist public key you don't view virtual key section
> Fix section on integration api - pn 12958

- packages/pn-pa-webapp/public/locales/it/notifiche.json
- packages/pn-personafisica-webapp/public/locales/it/notifiche.json
- packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json
change copy showed 
- change copy in notifiche.json
go in any user, search notification at least 6 months ago and download aarr
> FIX(PN-11392) : fix copy for download old AAR

- packages/pn-personafisica-webapp/src/components/Contacts/DefaultDigitalContact.tsx
- packages/pn-personafisica-webapp/src/components/Contacts/__test__/CourtesyContacts.test.tsx
- packages/pn-personafisica-webapp/src/components/Contacts/__test__/DefaultDigitalContact.test.tsx
- packages/pn-personafisica-webapp/src/components/Contacts/__test__/EmailContactItem.test.tsx
- packages/pn-personafisica-webapp/src/components/Contacts/__test__/LegalContacts.test.tsx
- packages/pn-personafisica-webapp/src/components/Contacts/__test__/PecContactItem.test.tsx
- packages/pn-personafisica-webapp/src/components/Contacts/__test__/SmsContactItem.test.tsx
- packages/pn-personagiuridica-webapp/src/components/Contacts/DefaultDigitalContact.tsx
- packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/CourtesyContacts.test.tsx
- packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/DefaultDigitalContact.test.tsx
- packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/EmailContactItem.test.tsx
- packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/LegalContacts.test.tsx
- packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/PecContactItem.test.tsx
- packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/SmsContactItem.test.tsx
This pull request contains the changes on DefaultDigitalContact component needed to meet the new design specifications expressed by the Contacts rework.
- DefaultDigitalContact.tsx
Run both PF and PG webapp and verify the involved component behave as expected. Try the new functionalities calling one of the component used inside the application (e.g. inside the Contacts page) using the new props also.
> refactor/13435: rework on DefaultDigitalContact component

- packages/pn-personagiuridica-webapp/src/components/IntegrazioneApi/VirtualKeys.tsx
- packages/pn-personagiuridica-webapp/src/utility/apikeys.utility.tsx
insert correct color for chip disabled
- insert default color
create case with disbaled virtual key in pg
> fix(PN-12958): insert default color for disabled chip

- packages/pn-personagiuridica-webapp/src/pages/ApiIntegration.page.tsx
Hide actions on virtual keys when public keys are removed
- Check issuer when there is no public key and some virtual keys
Login with an administrator (PG) -> create a public key and a virtual key -> block and remove the public key -> check that the actions on the virtual key are hidden
> pn-13028: hide actions when public key is removed

- packages/pn-personafisica-login/src/pages/loginError/LoginError.tsx
- packages/pn-personafisica-login/src/pages/loginError/__test__/LoginError.test.tsx
fix redirect for error login
- delete timeout
after try 4 times login with spid, navigate in error page and we will not redirect
> FIX(PN-13211) Gestione redirect automatico per errore

- packages/pn-commons/src/components/CustomDatePicker.tsx
insert close button for date picker
- insert action in action bar in datePicker and relative label
when open picker for date filter and click Chiudi inside dialog, dialog will close
> FIX(PN-13591) Handle Calendar for a11y

- packages/pn-pa-webapp/src/components/ApiKeys/ApiKeyDataSwitch.tsx
- packages/pn-pa-webapp/src/components/ApiKeys/DesktopApiKeys.tsx
- packages/pn-pa-webapp/src/components/ApiKeys/__test__/ApiKeyDataSwitch.test.tsx
- packages/pn-pa-webapp/src/pages/__test__/ApiKeys.page.test.tsx
Insert css style for insert triple dot in value of datatable of apikey
- insert css for tre dot of value
- insert css for responsive element
WIth Screen reader read apikey value in apikey table
> FIX(PN-13593) Screen Reader not read api key

- packages/pn-commons/src/components/NotificationDetail/NotificationPaymentPagoPAItem.tsx
- packages/pn-data-viz/src/PnEcharts.tsx
insert aria label for notification with payment and options for filter statistics
- insert aria label in check payment
- fix insert aria label for element
with screen reader go on notification with payment ad hear causale pagament of check payment and after this go on statistics page and hear correct label for check box
> Fix(PN-13213) Label per le radio button e checkbox

- packages/pn-commons/src/components/InactivityHandler.tsx
- packages/pn-commons/src/components/SessionModal.tsx
- packages/pn-commons/src/components/__test__/InactivityHandler.test.tsx
- packages/pn-pa-webapp/public/locales/it/common.json
- packages/pn-pa-webapp/src/navigation/SessionGuard.tsx
- packages/pn-personafisica-webapp/public/locales/it/common.json
- packages/pn-personafisica-webapp/src/navigation/SessionGuard.tsx
- packages/pn-personagiuridica-webapp/public/locales/it/common.json
- packages/pn-personagiuridica-webapp/src/navigation/SessionGuard.tsx
fix a11y with alert pre logout for inactivity
-insert timer with difference of original timeout
-insert another modal for request activity
Wait incativity timer, after enabled in configuration, and application should be request if you are active yet
> fix(PN-13214) Logout Inactivity

- packages/pn-pa-webapp/public/js/config.js
- packages/pn-pa-webapp/src/__test__/config.test.js
- packages/pn-personafisica-login/public/js/redirect.js
- packages/pn-personafisica-login/src/__test__/redirect.test.js
- packages/pn-personafisica-webapp/public/js/config.js
- packages/pn-personafisica-webapp/src/__test__/config.test.js
- packages/pn-personagiuridica-webapp/public/js/config.js
- packages/pn-personagiuridica-webapp/src/__test__/config.test.js
Include a summary of the changes.
Start app (ex: cittadini) and check in html header "meta robots" has "noindex"
> Fix/PN-13388: improve regex for redirect and robots header

- packages/pn-pa-webapp/src/redux/newNotification/reducers.ts
Cast paFee only if present
- Edit `newNotification` reducer 
On PF try to create a notification and on the 4 step select "Incluso nell'atto" as "Costo di notifica" or follow the steps described in JIRA
> PN-14157 - Cast paFee only if present

- packages/pn-pa-webapp/src/components/NewNotification/DebtPositionDetail.tsx
- packages/pn-pa-webapp/src/components/NewNotification/PaymentMethods.tsx
fix mobile version of paFee and Vat
Login as PA, go to create notification and check mobile version of paFee and Vat section is correctly shown.
> fix(PN-14167): fix mobile version of paFee and Vat

- packages/pn-pa-webapp/public/locales/it/notifiche.json
- packages/pn-pa-webapp/src/components/NewNotification/F24PaymentBox.tsx
- packages/pn-pa-webapp/src/components/NewNotification/PagoPaPaymentBox.tsx
fix copy as figma
Login as PA, check in create notification > payment section is present the type of file to upload json or pdf
> fix(PN-14145): fix copy as figma

- packages/pn-pa-webapp/src/components/Notifications/NotificationPaymentF24.tsx
fix text in f24 attached
- insetrt overflowWrap
VKMW-XEVW-NTVD-202503-X-1 ggiorgi user, comune di viggiu, test env
> fix(PN-14328) Testo Allegati f24 troppo lungo

- packages/pn-commons/src/components/Loading/LoadingOverlay.tsx
- packages/pn-commons/src/components/LoadingPage.tsx
- packages/pn-personagiuridica-webapp/src/components/LoadingPageWrapper/LoadingPageWrapper.tsx
insert a11y in loading logic
-insert aria-live and aria busy in container of loading
with voiceover actived hear loading
> fix(PN-11782) Fix su loading a11y 

- packages/pn-commons/package.json
- packages/pn-commons/src/utility/costants.tsx
- packages/pn-pa-webapp/package.json
- packages/pn-pa-webapp/src/components/NewNotification/F24PaymentBox.tsx
- packages/pn-pa-webapp/src/components/NewNotification/PagoPaPaymentBox.tsx
- packages/pn-pa-webapp/src/pages/ToSAcceptance.page.tsx
- packages/pn-personafisica-login/package.json
- packages/pn-personafisica-webapp/package.json
- packages/pn-personafisica-webapp/src/pages/ToSAcceptance.page.tsx
- packages/pn-personagiuridica-webapp/package.json
- packages/pn-personagiuridica-webapp/src/pages/ToSAcceptance.page.tsx
- yarn.lock
upgrade mui-italia to 1.6.1 version
Update Switch components in `TosAgreement` (PF-PG) and in `PagoPaPaymentBox` and `F24PaymentBox` (PA - when `applyCost` is set to true)
> chore: upgrade mui-italia to 1.6.1 version

- packages/pn-commons/src/utility/string.utility.ts
- packages/pn-pa-webapp/public/conf/config-dev.json
- packages/pn-personafisica-webapp/public/conf/config-dev.json
- packages/pn-personagiuridica-webapp/public/conf/config-dev.json
update link to downtime example link
- update link to downtime example link
- update regex for htmlUrl
Login as PG/PF/PA, go to "stato della piattaforma", set language of platform different from italian, click on "Consulta le traduzioni" and check new document is available.
> feat(PN-14823): update link to downtime example link and update regex for htmlUrl

- packages/pn-personafisica-login/public/conf/config-dev.json
- packages/pn-personafisica-login/src/pages/login/Login.tsx
- packages/pn-personafisica-login/src/pages/login/__test__/Login.test.tsx
- packages/pn-personafisica-login/src/services/configuration.service.ts
- packages/pn-personafisica-login/src/setupTests.tsx
Added feature flag for smart banner
- Add new IS_SMART_APP_BANNER_ENABLED configuration
- Use feature flag in Login.tsx
- Go to pf-login -> check that IS_SMART_APP_BANNER_ENABLED is true -> in mobile version check that smart banner is shown
- Go to pf-login -> check that IS_SMART_APP_BANNER_ENABLED is false -> in mobile version check that smart banner is hidden
> PN-14992: added feature flag for smart banner

- packages/pn-commons/src/components/CopyToClipboard.tsx
- packages/pn-commons/src/components/SnackBar/SnackBar.tsx
- packages/pn-pa-webapp/src/components/NewApiKey/__test__/SyncFeedbackApiKey.test.tsx
This PR includes some fixes for toast layout involving what described below
- choose the right font-family for technical data information
- Fix CopyToClipboard margins
- Fix close icon positioning and color
Follow the steps described in PN-15077 Jira attachment file to reproduce an error and verify the layout is as expected
> Fix: Fix toast layout

- packages/pn-commons/src/utility/AppError/GenericAppError/InternalServerAppError.ts
- packages/pn-commons/src/utility/AppError/GenericAppError/UnhandledAppError.ts
- packages/pn-commons/src/utility/AppError/GenericAppError/__test__/InternalServerAppError.test.ts
- packages/pn-commons/src/utility/AppError/GenericAppError/__test__/UnhandledAppError.test.ts
- packages/pn-commons/src/utility/AppError/UnknownAppError.ts
- packages/pn-commons/src/utility/AppError/__test__/UnknownAppError.test.ts
- packages/pn-pa-webapp/public/locales/it/common.json
- packages/pn-pa-webapp/public/locales/it/notifiche.json
- packages/pn-personafisica-webapp/public/locales/it/common.json
- packages/pn-personafisica-webapp/public/locales/it/notifiche.json
- packages/pn-personagiuridica-webapp/public/locales/it/common.json
- packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json
This PR includes the last changes to copy for errors involved into Error Tracement feature.
The new copy delivered by design team is available under "Gestione degli errori", a subpage of the SRS.
Reproduce the errors for PA, PG and PF following the netify configurations specified inside the attachment you can find on Jira PN-15077 task
> chore: change copy for some errors

- packages/pn-pa-webapp/public/locales/it/notifiche.json
Change copy for notification fee options shown during notification creation process
login on pa and check notification fee options have the correct copy
> chore(pn-15279): change copy for notification fee options

- packages/pn-personagiuridica-webapp/src/App.tsx
- packages/pn-personagiuridica-webapp/src/__test__/App.test.tsx
- packages/pn-personagiuridica-webapp/src/api/auth/Auth.api.ts
- packages/pn-personagiuridica-webapp/src/api/auth/auth.routes.ts
- packages/pn-personagiuridica-webapp/src/redux/auth/actions.ts
APi logout to invalidate token
- Call api /auth/logout
Login in PG and logout
> feat/PN-15326: PG call api logout before redirect

- packages/pn-commons/src/components/SnackBar/SnackBar.tsx
- packages/pn-commons/src/components/SnackBar/__test__/SnackBar.test.tsx
- packages/pn-commons/src/components/__test__/AppMessage.test.tsx
- packages/pn-commons/src/components/__test__/CopyToClipboard.test.tsx
- packages/pn-commons/src/redux/slices/__test__/appStateSlice.test.ts
- packages/pn-commons/src/utility/AppError/GenericAppError/__test__/InternalServerAppError.test.ts
- packages/pn-commons/src/utility/AppError/GenericAppError/__test__/UnhandledAppError.test.ts
- packages/pn-commons/src/utility/AppError/__test__/AppError.test.ts
- packages/pn-commons/src/utility/AppError/__test__/UnknownAppError.test.ts
- packages/pn-commons/src/utility/__test__/message.utillity.test.ts
- packages/pn-pa-webapp/src/utility/AppError/__test__/DeliveryFileInfoNotFoundAppError.test.ts
- packages/pn-pa-webapp/src/utility/AppError/__test__/DeliveryInvalidParameterGroupAppError.test.ts
- packages/pn-pa-webapp/src/utility/AppError/__test__/DeliveryNotificationWithoutPaymentAttachmentAppError.test.ts
- packages/pn-pa-webapp/src/utility/AppError/__test__/DeliveryPushFileNotFoundAppError.test.ts
- packages/pn-pa-webapp/src/utility/AppError/__test__/GenericInvalidParameterTaxonomyCodeAppError.test.ts
- packages/pn-pa-webapp/src/utility/AppError/__test__/InvalidBodyAppError.test.ts
- packages/pn-pa-webapp/src/utility/AppError/__test__/PAAppErrorFactory.test.ts
- packages/pn-personafisica-webapp/src/components/Support/ZendeskForm.tsx
- packages/pn-personafisica-webapp/src/components/Support/__test__/ZendeskForm.test.tsx
- packages/pn-personafisica-webapp/src/pages/__test__/Support.page.test.tsx
- packages/pn-personafisica-webapp/src/utility/AppError/__test__/DeliveryFileInfoNotFoundAppError.test.ts
- packages/pn-personafisica-webapp/src/utility/AppError/__test__/DeliveryNotificationWithoutPaymentAttachmentAppError.test.ts
- packages/pn-personafisica-webapp/src/utility/AppError/__test__/DeliveryPushFileNotFoundAppError.test.ts
- packages/pn-personafisica-webapp/src/utility/AppError/__test__/PFAppErrorFactory.test.ts
- packages/pn-personagiuridica-webapp/src/utility/AppError/__test__/DeliveryFileInfoNotFoundAppError.test.ts
- packages/pn-personagiuridica-webapp/src/utility/AppError/__test__/DeliveryNotificationWithoutPaymentAttachmentAppError.test.ts
- packages/pn-personagiuridica-webapp/src/utility/AppError/__test__/DeliveryPushFileNotFoundAppError.test.ts
- packages/pn-personagiuridica-webapp/src/utility/AppError/__test__/InvalidBodyAppError.test.ts
- packages/pn-personagiuridica-webapp/src/utility/AppError/__test__/PGAppErrorFactory.test.ts
This PR fixes already existing tests and add new tests relative to Error Tracement feature.
> test: fix existing tests and add new tests for sending errors to Zendesk

- packages/pn-personafisica-webapp/public/locales/it/recapiti.json
- packages/pn-personafisica-webapp/src/components/Contacts/PecContactWizard.tsx
- packages/pn-personagiuridica-webapp/public/locales/it/recapiti.json
- packages/pn-personagiuridica-webapp/src/components/Contacts/PecContactWizard.tsx
Refactor of the PEC activation component.
- Add error border to checkbox
- Add button in the PEC activation component
- Login as PF/PG
- Go to "recapiti" page
- Go to activate PEC as digital domicile
- Check button is present and you can't enable digital domicile if you don't flag the checkbox
> fix/PN-15404: update PEC activation flow

- packages/pn-personafisica-webapp/public/locales/it/recapiti.json
- packages/pn-personafisica-webapp/src/components/Contacts/IOContactWizard.tsx
- packages/pn-personafisica-webapp/src/components/Contacts/__test__/DigitalContactActivation.test.tsx
- packages/pn-personagiuridica-webapp/public/locales/it/common.json
- packages/pn-personagiuridica-webapp/public/locales/it/recapiti.json
- packages/pn-personagiuridica-webapp/src/components/Contacts/DigitalContactActivation.tsx
- packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/DigitalContactActivation.test.tsx
Update copy for PG and PF io modal
- update PG thank you page modal 
- update PF io disable modal
Login as PF, start dod activation with sercq, go back after io is enable, click on disable io and check modal has [right copy](https://www.figma.com/design/DlzvNQzkecy7L2ym40OTge/Domicilio-digitale---08-11?node-id=7678-39211&t=XKeYZd3FWj715Mr8-4)
Login as PG, 
- activate sercq and check thank you page [copy is right](https://www.figma.com/design/DlzvNQzkecy7L2ym40OTge/Domicilio-digitale---08-11?node-id=6994-42945&t=XKeYZd3FWj715Mr8-4)
- activate pec dod and check [typ](https://www.figma.com/design/DlzvNQzkecy7L2ym40OTge/Domicilio-digitale---08-11?node-id=6994-42922&t=XKeYZd3FWj715Mr8-4) is right
- migrate dod on pec and check [typ](https://www.figma.com/design/DlzvNQzkecy7L2ym40OTge/Domicilio- …
> fix/PN-15405: update copy

- packages/pn-pa-webapp/src/__test__/App.test.tsx
- packages/pn-personafisica-webapp/src/__test__/App.test.tsx
- packages/pn-personagiuridica-webapp/src/__test__/App.test.tsx
> TEST: fix test for logout API called
