packages/pn-personafisica-webapp/src/pages/Deleghe.page.tsx, packages/pn-personafisica-webapp/src/pages/components/Deleghe/Delegates.tsx, packages/pn-personafisica-webapp/src/pages/components/Deleghe/Delegators.tsx, packages/pn-personafisica-webapp/src/pages/components/Deleghe/delegationsColumns.tsx, packages/pn-personafisica-webapp/src/redux/delegation/actions.ts, packages/pn-personafisica-webapp/src/redux/delegation/reducers.ts, packages/pn-personafisica-webapp/src/redux/delegation/types.ts
- connect refuse delegation api call to UI
- reformat confirmation modal to both revocate and reject
=> feat: reformat confirmation modal , connect reject api call to UI

packages/pn-pa-webapp/src/index.css, packages/pn-personafisica-webapp/src/index.css
- Removes forced line-height for Typography elements in both apps
=> fix: remove 1.5 line-height for Typography-Root in both apps

packages/pn-personafisica-webapp/src/redux/delegation/__test__/reducers.test.ts, packages/pn-personafisica-webapp/src/redux/delegation/reducers.ts
- name doesn't get removed when closing the verification modal
=> fix: PN-1633 does not remove the name when closing verification modal

packages/pn-personafisica-webapp/src/pages/TermsOfService.page.tsx
fix: allow the user to access the application only if the ToS acceptance request is successfully sent
=> Fix/PN-1943 Salvataggio dei TOS va in errore e si consente comunque di accedere all'applicazione

packages/pn-personafisica-webapp/src/App.tsx
Ho semplicemente modificato la definizione di userActions (il menu in alto a destra) per pf-webapp, se l'utente non ha accettato le TOS non viene inclusa l'opzione che fa vedere il profilo (in italiano "i tuoi dati"), e cioè non si può accedere tramite click alla gestione di recapiti.
Basta entrare con un utente che non abbia accettato le TOS, ad es. garibaldi in ambiente DEV (ad oggi, 2022.10.04). Se si entra con un utente che abbia accettato le TOS (ad es. ada in ambiente DEV), si dovrebbe accedere a tutta la funzionalità, inclusa l'opzione di profilo nel menu in alto a destra.
=> PN-2281 - non si vede l'opzione di 'i tuoi dati' se non hai accettato le TOS

packages/pn-pa-webapp/src/pages/components/NewNotification/Attachments.tsx, packages/pn-pa-webapp/src/pages/components/NewNotification/PaymentMethods.tsx
Include a summary of the changes.
- new notification -> substitute an uploaded document (attachment or payment document)
Start notification creation workflow. At third step, upload one or more documents. Go to the next step, go back and substitute one of the uploaded documents. Verify that preload and upload apis are called.
=> substitute uploaded file #pn-2347

packages/pn-commons/src/utils/costants.tsx, packages/pn-landing-webapp/src/components/NavigationBar.tsx, packages/pn-landing-webapp/src/layout/footer.constants.tsx
Removes explicit index.html in link in landing webapp footer
- Start pn-landing-webapp
- click on 'Privacy Policy', 'Terms of Service', 'Cittadini', 'Aziende'  links
- urls should not end with index.html
=> fix: remove index.html ending from landing app links

packages/pn-pa-webapp/src/pages/components/NewNotification/PreliminaryInformations.tsx
In notification manual sending it has been fixed the condition on groups choice by user.
- An user with admin role has to be able to see the list of all the groups in its PA but should have the possibility to not choose a group when sending a notification
Access the PA backoffice with an admin user for a PA which has a list of groups and check that the groups dropdown in "Informazioni preliminari" is filled with the list of groups. Groups are not mandatory for admin role, therefore you should be able to continue to step 2 without choosing a group.
=> fix(pn-2198): added right validation rule for groups in manual sending

packages/pn-pa-webapp/src/redux/dashboard/actions.ts, packages/pn-personafisica-webapp/src/component/Notifications/FilterNotifications.tsx, packages/pn-personafisica-webapp/src/component/Notifications/__test__/FilterNotifications.test.tsx, packages/pn-personafisica-webapp/src/pages/Notifiche.page.tsx, packages/pn-personafisica-webapp/src/redux/dashboard/__test__/reducers.test.ts, packages/pn-personafisica-webapp/src/redux/dashboard/actions.ts, packages/pn-personafisica-webapp/src/redux/dashboard/reducers.ts
Fixed two main bugs that occur when filter notification list (pf):
- Filter button enabled when no filters are applied
- Multiple notification list api calls
- To resolve the first bug, I changed the condition under wihich the filter button is disabled
- To resolve the second bug, I removed nextPagesKey from array dependencies of the function fetchNotifications
First bug:
- log with pf -> check that filter button is disabled
- log with pf -> add filters -> remove filters by clicking the button -> check that filter button is disabled
- log with pf -> add filters but not confirm -> remove filters emptying inputs -> check that filter button is disabled
Second bug:
- log with pf -> open console -> apply and remove some filter -> check that the notification list api is colled once
=> bugs when filter notifications #pn-2433

packages/pn-validator/src/types/TypeRules.ts
Now pn-validator works with boolean and optional properties
- Modified TypeRules to manage this two cases
Create a class with boolean and optional properties. Create validator for this class and check that ide suggests correct rules for these properties
=> boolean and optional keys management

packages/pn-pa-webapp/public/locales/it/notifiche.json, packages/pn-pa-webapp/src/models/NewNotification.ts, packages/pn-pa-webapp/src/pages/components/NewNotification/PaymentMethods.tsx, packages/pn-pa-webapp/src/pages/components/NewNotification/PreliminaryInformations.tsx, packages/pn-pa-webapp/src/pages/components/NewNotification/__test__/PreliminaryInformations.test.tsx, packages/pn-pa-webapp/src/redux/newNotification/__test__/reducers.test.ts, packages/pn-pa-webapp/src/redux/newNotification/reducers.ts, packages/pn-pa-webapp/src/utils/notification.utility.ts
Now it is possible to create notification without payment
- Added choice "Nothing" under payment method in preliminary informations section
- Added an empty state in payment methods section, with a button to go back to preliminary informations section
- Log with m.messina - INAIL
- Go to new notification page
- Select "Nothing" choice under payment method in preliminary informations section
- Fill required informations
- Check that the notification i correctly created
=> notifications without payment

packages/pn-pa-webapp/src/pages/NotificationDetail.page.tsx
Added denomination data to recipients list
- Recipients list was previously liste by taxId only. Now it's by 'taxId + denomination'
Open a multi recipients notification detail and check for recipients list.
=> Pn 2483 dettaglio notifica multi destinatario assenza nome e cognome destinatario

packages/pn-pa-webapp/src/pages/components/NewNotification/Attachments.tsx, packages/pn-pa-webapp/src/pages/components/NewNotification/PaymentMethods.tsx, packages/pn-pa-webapp/src/pages/components/NewNotification/__test__/PaymentMethods.test.tsx
This pr fixes the following bugs:
- "Send" button not disabling after deleting an F24 payment file
- Error trying removing a tracked payment document and then going back to step "attachments"
- Attachment box not refreshing after removing the corresponding file (clicking the "x" icon)
- change yup validation schema in PaymentMethods component to set F24 payment document as mandatory when the correspondig option has been selected in step 1 of the notification creation procedure
- change removeFileHandler in PaymentMethods and Attachments components to use a single setFieldValue and fix the default data to store file info properly to fix errors removing a tracked payment document and attachment box not re-rendering properly
- test: fix PaymentMethods.test.tsx not working after changes
- …
=> fix: PN-2577 Multi recipients - resolve bugs related to payment files management

packages/pn-pa-webapp/public/locales/it/notifiche.json, packages/pn-pa-webapp/src/pages/components/NewNotification/Recipient.tsx, packages/pn-pa-webapp/src/pages/components/NewNotification/__test__/Recipient.test.tsx, packages/pn-pa-webapp/src/redux/newNotification/__test__/test-utils.ts, packages/pn-pa-webapp/src/utils/__test__/notification.utility.test.ts, packages/pn-pa-webapp/src/utils/notification.utility.ts
In Recipient component, now if the user uses the same combination of creditorTaxId and 
- Adds check on same Notice Code and Creditor Tax Id for multiple recipients
- Refactor duplicate map and filter inside a function getDuplicateValuesByKeys
- Fixes tests for Recipient, now checks correctly that continue button is disabled if multiple recipients share the same Tax Id or Notice Code + Creditor Tax Id, and not because of other errors
- Changes some MockValues to ensure tests run correctly
Send manual notification, in the recipients step, set the same combination of values in the "Codice fiscale ente creditore" and "Codice avviso" fields for 2 or more different recipients, an error should be displayed and the continue button should be disabled when all other fields are set correctly.
=> fix: pn-2487 adds multiple recipient with same notice code warning

packages/pn-pa-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-pa-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
Fixes error in payment amount format in notification detail for pn-pa-webapp
- Fixes error in payment amount format in NotificationDetail.page.tsx
- Changes tests accordingly for NotificationDetail.page.test.tsx
Check that payment amount is formatted from eurocents to euros (es. 1010 -> 10,10 €) for notification detail for pn-pa-webapp
Tested in SVIL env for notification [QKGT-RPXH-NJTY-202211-D-1](https://portale-pa.svil.pn.pagopa.it/dashboard/QKGT-RPXH-NJTY-202211-D-1/dettaglio)
=> fix: PN-2672 format payment amount from eurocents to euros

packages/pn-commons/src/components/AppStatus/MobileDowntimeLog.tsx, packages/pn-pa-webapp/public/locales/it/common.json, packages/pn-pa-webapp/src/pages/AppStatus.page.tsx
Fixes typo in AppStatus page for pn-pa-webapp
- Fixes typo in AppStatus page for pn-pa-webapp
AppStatus page should now display "ore" instead of "ora"
=> fix: PN-2745 typo in appstatus page ora to ore

packages/pn-commons/src/utils/__test__/string.utility.test.ts, packages/pn-commons/src/utils/index.ts, packages/pn-commons/src/utils/string.utility.ts, packages/pn-commons/tsconfig.json, packages/pn-pa-webapp/src/i18n.ts, packages/pn-pa-webapp/tsconfig.json, packages/pn-personafisica-webapp/src/i18n.ts, packages/pn-personafisica-webapp/tsconfig.json
Special character are escaped during translation (in our case char ' is translated to html code)
Introduced custom escape function to sanitize string when translating 
- Added a sanitize function into string.utility.ts in pn-commons package
- Configured i18next instance to accept the sanitize function in pa and pf packages
Run pf package and point to coll environment. Login with Giovanna D'Arco and search notification with iun ZNGK-GRAD-KYDE-202211-A-1. Go to the notification detail and check that in timeline Giovanna D'Arco is printed correctly
=> special chars sanitized during translation

packages/pn-commons/src/components/SideMenu/SideMenu.tsx, packages/pn-commons/src/components/SideMenu/SideMenuList.tsx, packages/pn-commons/src/components/SideMenu/SideMenuListItem.tsx, packages/pn-commons/src/components/SideMenu/__test__/test-utils.ts
When an user has some delegations, the side menu of the dashboard has the voice "Notifiche" that is expandable.
Before the fix, the menu was collapsed and so the user couldn't see which notifications he was seeing.
Now this behavior is fixed.
- Added parent property for those selected menu item that are children of another menu item
- Expand the menu voice, when the parent property is set
Pf -> log with an user with delegations and check that menù is opened and the voice "Le tue notifiche" is selected. Select on of the delegators, refresh and check that the menù is opened and the right menu voice is selected. Go to delegator notification detail, refresh and do the check explained above
=> side menu expanded when a sub menu voice is selected

packages/pn-pa-webapp/src/pages/components/NewNotification/Attachments.tsx, packages/pn-pa-webapp/src/pages/components/NewNotification/PaymentMethods.tsx, packages/pn-pa-webapp/src/pages/components/NewNotification/__test__/Attachments.test.tsx
New notification - reset document ref data when it is uploaded and after is changed by drag
- Changed part that manage file upload in Attachments.tsx and PaymentMethods.tsx files
Go to new notification, go to step 3 or 4, upload document and confirm. the file is uploaded (ref data is filled). Change the file by dragging new one without removing the old one. Reconfirm and check that the new file is uploaded and ref is filled with new data
=> pn-2855 - reset document ref data when it is uploaded by drag

packages/pn-pa-webapp/public/locales/it/appStatus.json
I changed the subtitle of the app status ("Stato della piattaforma") for the recipient ("persona fisica") webapp, according with the indication given in https://pagopa.atlassian.net/browse/PN-2747 .
Just changed the text in the corresponding entry of the Italian i18n file.
Enter both sender ("pubblica amministrazione") and recipient ("persona fisica") webapps, in each of them go to the "Stato della piattaforma" option, and check whether the subtitle (i.e. the text below the "Stato della piattaforma" title) coincides or not with the corresponding text specified in https://pagopa.atlassian.net/browse/PN-2747.
=> PN-2747 - changed subtitle of app status page for PA, keeps as before for PF

packages/pn-personafisica-webapp/cypress/e2e/Delegate.cy.ts, packages/pn-personafisica-webapp/cypress/e2e/NotificationFilters.cy.ts
changes made to default status of the 'notifiche' menu item from collapsed to expanded caused tests acting as delegate to stop working
=> test: fix cy tests not working after changes on 'notifiche' menu item

packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx
After payment, the user is redirected to the notification detail. Previously if the user clicked on the "Indietro" button he was redirected to the checkout page. Now is redirected to notifications list page
- Added goBackAction to breadcrumb in NotificationDetail.page.tsx
Go to pf -> login with ada -> navigate to third page and find a notification that must be paid -> pay the notification (check credit cards on confluence) -> return to notification detail -> click on "Indietro" button and check that the user is redirected to notifications list page
=> go back after payment #pn-3052

packages/pn-personagiuridica-webapp/Dangerfile.ts, packages/pn-personagiuridica-webapp/package.json, yarn.lock
Upgrades sonarqube-scanner and removes danger-plugin-digitalcitizenship from dependencies in personagiuridica-webapp
- Upgrades sonarqube-scanner in personagiuridica-webapp
- Removes danger-plugin-digitalcitizenship from dependencies in personagiuridica-webapp
It shouldn't affect apps behavior and pipelines, so yarn start build and test should work correctly, pipelines should run correctly too.
=> fix: upgrade sonarqube-scanner and remove danger

packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
Just change a literal from `apiKeys` to `apikeys`, to hopefully make the subtitles of the Api Keys FE to appear with the proper translation.
- Just-a-literal-changed.
Just enter into the API Key page in pa-webapp, check the subtitle. Should look like this
instead of this
=> Api keys FE - solve a typo to hopefully restore translation for the subtitle

packages/pn-personafisica-webapp/src/api/notifications/Notifications.api.ts, packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personafisica-webapp/src/redux/notification/actions.ts
Hot fix for AAR documents download in delegate PF
- Adds a missing parameter mandateId used to download AAR documents for delegate PF
Example: In PF login with user ada then list notifications of "Cristoforo Colombo" and search for iun EWJR-KEMD-NQKM-202301-K-1. You should be able to download AAR document now.
=> chore: Added missing parameter to fix download error in delegate PF

aws-cdn-templates/one-cdn.yaml
Fix PathPattern  values for cdn cache to also invalidate subdirs content and not first level files only.
Unfortunately this should be merged and deployed to verify it works properly. I followed the aws documentation available [here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html), where it talk about "subdirectories".
=> Fix: PN-2626 Caching policies

packages/pn-commons/src/types/NotificationDetail.ts, packages/pn-commons/src/utils/TimelineUtils/SendAnalogFeedbackStep.ts, packages/pn-commons/src/utils/__test__/notification.utility.test.ts, packages/pn-commons/src/utils/notification.utility.ts
Analog workflow failure management
- Changed status property in responseStatus property in SendPaperDetail model
- Replaced all the usages of status
- Login in with marcopolo -> search notification with iun XVZY-RUEM-MQVP-202301-N-1 -> check that in timeline there are the analog steps OK.
- Login in with marcopolo -> search notification with iun WKUT-RVDQ-XDXU-202302-Y-1 -> check that in timeline there are the analog steps KO.
=> analog workflow KO (pn-2985)

packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx
Changed breadcrumb redirect url in notification detail when user has delegations
- Changed breadcrumb redirect url in NotificationDetail.page.tsx (pf and pg)
Log with an user with delegations. Go to the detail of a delegate's notification. Click on back button and check that the user will be redirect to the correct page
=> back button redirecting in notification detail - pn-3997

packages/pn-pa-webapp/public/locales/it/common.json
Fixed copy about login button in PA.
- Modified common.json in PA
The button shown in PA before login should be "Accedi" now instead of "Procedi al login"
=> Fixed copy about login button in PA

packages/pn-personafisica-webapp/src/component/Contacts/DigitalContactElem.tsx, packages/pn-personagiuridica-webapp/src/component/Contacts/DigitalContactElem.tsx
Modified css style to make contacts to be word wrapped if necessary.
- Modified css style to make contacts to be word wrapped if necessary
- Both PF and PG
Go in contacts page, set mobile resolution and add a long email. The email is word wrapped now.
=> Modified css style to make contacts to be word wrapped if necessary

packages/pn-personafisica-webapp/public/locales/it/notifiche.json, packages/pn-personafisica-webapp/src/component/Notifications/NotificationPayment.tsx, packages/pn-personafisica-webapp/src/component/Notifications/__test__/NotificationPayment.test.tsx, packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json, packages/pn-personagiuridica-webapp/src/component/Notifications/NotificationPayment.tsx, packages/pn-personagiuridica-webapp/src/component/Notifications/__test__/NotificationPayment.test.tsx
Added IN PROGRESS status in NotificationPayment components.
- Added IN PROGRESS status in NotificationPayment components both PF and PG
- Added a new button which reloads payment status info
- Fixed both tests of the components above
- Modified translations
Open any notification where it have to pay so pay it. The new payment status should shows IN PROGRESS label and in the description there is a link button which reloads payment status info.
=> Added IN PROGRESS status in NotificationPayment components

packages/pn-personafisica-webapp/src/component/Deleghe/MobileDelegates.tsx, packages/pn-personafisica-webapp/src/component/Deleghe/MobileDelegators.tsx, packages/pn-personagiuridica-webapp/src/component/Deleghe/MobileDelegates.tsx, packages/pn-personagiuridica-webapp/src/component/Deleghe/MobileDelegators.tsx
Removed email view from mobile delegates and delegators.
- Removed from mobile delegators
- Removed from mobile dleegates
Find user with delegates or delegators (or create a new delegator) and switch on mobile. You shouldn't see email anymore.
=> Removed email view from mobile delegates and delegators

packages/pn-pa-webapp/public/locales/it/notifiche.json
Replaced texts in payment label in notification details PA.
- Replaced text for payment.subtitle-single in notifiche.json
- Replaced text for payment.subtitle-multiple in notifiche.json
With SVIL environment, use these iun codes
MONO - user baldassarremazza, Comune di Milano
YDUM-AEQX-KZNR-202303-Z-1 --> mono (Milano)
WMUQ-JUYJ-TLUN-202303-W-1 --> mono (Milano)
MULTI - user grossini, Comune di Palermo
GVYQ-WLPR-GPQE-202303-A-1 --> multi (Palermo)
RNRD-DPHU-VPRE-202303-H-1 --> multi (Palermo)
=> Replaced texts in payment label in notification details PA

packages/pn-commons/src/utils/costants.tsx
Updated the link for "Certificazioni" in the tall footer which appears in the inital page (the one with the "Accedi" button) in all the PN applications.
Enter either PA / PF / PG / Portale login, check the "Certificazioni" link.
=> PN-4694 - certifications link in footer updated

packages/pn-commons/src/components/Data/ItemsTable.tsx, packages/pn-commons/src/components/Data/__test__/ItemsTable.test.tsx, packages/pn-commons/src/types/ItemsTable.ts, packages/pn-commons/src/utils/__test__/styles.utility.test.tsx, packages/pn-commons/src/utils/index.ts, packages/pn-commons/src/utils/styles.utility.ts, packages/pn-pa-webapp/src/pages/components/Notifications/DesktopNotifications.tsx, packages/pn-pa-webapp/src/pages/components/Notifications/__test__/DesktopNotifications.test.tsx, packages/pn-personafisica-webapp/src/component/Notifications/DesktopNotifications.tsx, packages/pn-personafisica-webapp/src/component/Notifications/__test__/DesktopNotifications.test.tsx, packages/pn-personagiuridica-webapp/src/component/Notifications/DesktopNotifications.tsx, packages/pn-personagiuridica-webapp/src/component/Notifications/__test__/DesktopNotifications.test.tsx
Fix issue in ItemsTable where user was unable to navigate via keyboard.
Accessibility navigation with keyboard is possible by setting tabIndex={0} on HTML tags. However tabIndex alone is insufficient because any onClick event associated to tags like DIV, TABLE, TD or any of non-interaction HTML tags (example: BUTTON, INPUT, SELECT, etc.), won't trigger if you press space or enter. The natural solution is to wrap content with BUTTON tag where onClick event is present.
- Added new utility styles.utility.tsx to pn-commons. It contains a const with CSS properties for ButtonNaked compononent
- Wrapped any cell content with ButtonNaked component where onClick is defined.
Open notifications table from any app and use keyboard. Now you should be able to navigate and also select a notification by …
=> Fix issue in ItemsTable where user was unable to navigate via keyboard

packages/pn-commons/src/services/__test__/configuration.service.test.ts, packages/pn-commons/src/services/configuration.service.ts, packages/pn-commons/src/services/fetch.configuration.service.ts, packages/pn-commons/src/services/index.ts
Implement the tools needed to get the configuration from the file `public/conf/config.json` instead of env variables, so that we can move to a "build once - deploy many" scenario.
Created the `configuration.services.ts` file, which includes:
- a global (but not exported) variable to hold the read config
- a function `loadConfiguration<T>(validator)` (to be parametrized upon the type of the config for each PN app), which fetches the file, verifies the contents using the given validator (a validator created using `pn-validator` is expected), and stores it in the variable just mentioned. If the fetching fails, or the contents fail to pass the validation, then this function raises an exception.
- a function `getConfiguration<T>` which verifies that `loadConfiguration` have been called, and …
=> PN-4862 - take config from json - tooling

packages/pn-commons/src/utils/__test__/styles.utility.test.tsx, packages/pn-commons/src/utils/styles.utility.ts
Fixed issue which cause misalignment with ItemsTable component.
- Added textAlign: inherit to buttonNakedInheritStyle
- Set proper test for buttonNakedInheritStyle
You should not have the bug shown in [PN-5281](https://pagopa.atlassian.net/browse/PN-5281) images anymore.
[PN-5281]: https://pagopa.atlassian.net/browse/PN-5281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Pn 5281 fe sezione notifiche allineamento campi

packages/pn-personafisica-webapp/src/component/Contacts/DigitalContactsCodeVerification.context.tsx, packages/pn-personafisica-webapp/src/component/Contacts/__test__/CourtesyContactItem.test.tsx, packages/pn-personagiuridica-webapp/src/component/Contacts/DigitalContactsCodeVerification.context.tsx, packages/pn-personagiuridica-webapp/src/component/Contacts/__test__/CourtesyContactItem.test.tsx
Fixed contacts endpoint call before disclaimer acceptance.
- Disclaimer acceptance is before contacts endpoint call in DigitalContactsCodeVerification context
- Refactored some tests
Add new contacs and watch network section in dev tools in your browser. Now the endpoit is called after disclaimer acceptance.
=> Pn 5214 fe invio codice otp anticipato prima dellaccettazione del disclamer

packages/pn-personafisica-login/src/pages/login/Login.tsx, packages/pn-personafisica-login/src/pages/success/Success.tsx, packages/pn-personafisica-login/src/pages/success/__tests__/Success.test.tsx, packages/pn-personafisica-login/src/utils/constants.ts, packages/pn-personafisica-webapp/src/App.tsx, packages/pn-personafisica-webapp/src/navigation/AARGuard.tsx, packages/pn-personafisica-webapp/src/navigation/RouteGuard.tsx, packages/pn-personafisica-webapp/src/navigation/SessionGuard.tsx, packages/pn-personafisica-webapp/src/navigation/__test__/navigation.utility.test.ts, packages/pn-personafisica-webapp/src/navigation/navigation.utility.ts, packages/pn-personagiuridica-webapp/buildspec.yaml, packages/pn-personagiuridica-webapp/src/App.tsx, packages/pn-personagiuridica-webapp/src/api/notifications/Notifications.api.ts, packages/pn-personagiuridica-webapp/src/navigation/AARGuard.tsx, packages/pn-personagiuridica-webapp/src/navigation/RouteGuard.tsx, packages/pn-personagiuridica-webapp/src/navigation/SessionGuard.tsx, packages/pn-personagiuridica-webapp/src/navigation/__test__/navigation.utility.test.ts, packages/pn-personagiuridica-webapp/src/navigation/navigation.utility.ts, packages/pn-personagiuridica-webapp/src/utils/constants.ts
Now the login for pg is managed by selfcare portal and not by login webapp
- Disabled PG management in login webapp
- Removed type query param when pf webapp redirects to login webapp
- Managed new login and aar in pg webapp
- PF -> login with pf and check that the login works correctly
- PF -> use an aar link and check that it works correctly both for not logged user and logged one
- Login -> check that disambiguation page is never shown
- PG -> login with pg and check that the login works correctly
- PG -> logout with pg and check that we are redirected to selfcare portal and not login webapp
- PG -> use an aar link and check that it works correctly both for not logged user and logged one
=> Pg login from selfcare portal - pn-5157

packages/pn-commons/src/types/NotificationDetail.ts, packages/pn-commons/src/utils/TimelineUtils/SendDigitalProgressStep.ts, packages/pn-commons/src/utils/__test__/notification.utility.test.ts, packages/pn-commons/src/utils/__test__/parseNotificationDetail.multirecipient.test.ts, packages/pn-commons/src/utils/__test__/parseNotificationDetail.test.ts, packages/pn-commons/src/utils/__test__/test-utils.ts, packages/pn-commons/src/utils/notification.utility.ts, packages/pn-pa-webapp/cypress/fixtures/notifications/effective_date.json, packages/pn-pa-webapp/cypress/fixtures/notifications/old/notification-1.json, packages/pn-pa-webapp/cypress/fixtures/notifications/old/notification-2.json, packages/pn-pa-webapp/cypress/fixtures/notifications/old/notification-4.json, packages/pn-personafisica-webapp/cypress/fixtures/notifications/delegator/detail.json, packages/pn-personafisica-webapp/cypress/fixtures/notifications/effective_date.json, packages/pn-personafisica-webapp/cypress/fixtures/notifications/viewed.json, packages/pn-personagiuridica-webapp/cypress/fixtures/notifications/delegator/detail.json, packages/pn-personagiuridica-webapp/cypress/fixtures/notifications/effective_date.json, packages/pn-personagiuridica-webapp/cypress/fixtures/notifications/viewed.json
Adapts timeline data structures since the field `eventCode` present in the detail for timeline events of type `SEND_DIGITAL_DOMICILE` / `SEND_DIGITAL_PROGRESS` / `SEND_DIGITAL_FEEBACK` has been renamed to `deliveryDetailCode` in the response of the API request (included in `pn-delivery-push`) that yields the details of a single notification.
- Renamed `eventCode` as `deliveryDetailCode` in the `SendDigitalDetails`  interface, cfr. `packages\pn-commons/src/types/NotificationDetail.ts`. Also removed two attributes that are not currently included in the API response (`errors` and `downstreamId`).
- Changed the behavior of the timeline accordingly.
- Changed the notification details defined for several tests accordingly.
Enter any notification sent through digital workflow, e.g. …
=> PN-5497 - eventCode renamed as deliveryDetailCode in digital timeline events

packages/pn-personafisica-webapp/public/locales/it/notifiche.json, packages/pn-personafisica-webapp/src/component/Notifications/NotificationPayment.tsx, packages/pn-personafisica-webapp/src/component/Notifications/__test__/NotificationPayment.test.tsx, packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json, packages/pn-personagiuridica-webapp/src/component/Notifications/NotificationPayment.tsx, packages/pn-personagiuridica-webapp/src/component/Notifications/__test__/NotificationPayment.test.tsx
Removed references to different amount payment.
- Removed references to different amount payment from NotificationPayment component, both PF and PG
- Fixed tests, both PF and PG
- Removed unused strings from notifiche.json, both PF and PG
Find a notification with payment enabled. You shuldn't see payment different amount disclaimer anymore.
=> Removed references to different amount payment

packages/pn-commons/src/utils/__test__/styles.utility.test.tsx, packages/pn-commons/src/utils/styles.utility.ts
Fixed issue with misaligned elements in table.
- Changed display property in buttonNakedInheritStyle
- Extended test for buttonNakedInheritStyle
Open any notifications table (PF, PA or PG). You should see status label properly aligned now.
=> Pn 5840 fe portale mittente destinatario label degli stati non piu centrato

packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx
Missing prop `paymentHistory` in `NotificationPayment` component in `NotificationDetail.page` compoent was causing wrong payment status output in PG.
- Added missing `paymentHistory`  prop to notification detail page of PG
Login PG with user `DanteAlighieri` and entity `DivinaCommediaSrl`. Then find iun `TDXM-GPKQ-RVJZ-202305-H-1`. This notification was the failing one about payment status. Now it will correctly show as paid with summary data.
=> Added missing prop to notification detail page of PG

packages/pn-commons/src/components/TitleBox.tsx, packages/pn-commons/src/types/Notifications.ts, packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json, packages/pn-personagiuridica-webapp/src/api/notifications/notifications.routes.ts, packages/pn-personagiuridica-webapp/src/component/Notifications/DesktopNotifications.tsx, packages/pn-personagiuridica-webapp/src/component/Notifications/GroupSelector.tsx, packages/pn-personagiuridica-webapp/src/component/Notifications/__test__/GroupSelector.test.tsx, packages/pn-personagiuridica-webapp/src/pages/Notifiche.page.tsx, packages/pn-personagiuridica-webapp/src/pages/__test__/Notifiche.page.test.tsx, packages/pn-personagiuridica-webapp/src/redux/dashboard/reducers.ts
When we login with a PG user that is a group administrator, we can only see notifications for one group at a time. For this reason, a group switch has been added near the section title
- Added group selector
- Removed context menu from notification list, because we don't have the information about the group linked to the notification
Dev -> log with Dante Alighieri - VitaNova -> I see all the delegated notifications without group switch
Dev -> log with Giuseppe Ungaretti - VitaNova -> I see group switch
=> PG - Group selector for delegated notifications - pn-385 

packages/pn-personafisica-webapp/public/locales/it/notifiche.json, packages/pn-personafisica-webapp/src/component/Notifications/DesktopNotifications.tsx, packages/pn-personafisica-webapp/src/component/Notifications/MobileNotifications.tsx, packages/pn-personafisica-webapp/src/component/Notifications/__test__/DesktopNotifications.test.tsx
This PR regards the notification list page for PF, in particular empty (i.e. no notifications to show) case, when the logged user is acting as delegate of another PF or a PG. In such case, the content of the "empty state" banner changes, now it should just read "[delegator name] non ha ricevuto nessuna notifica." and the link to add contact information is not included. The contents of the "empty state" banner when the logged user accesses to its own notifications is unchanged.
Just changed the `EmptyStateProps` in both `DesktopNotifications` and `MobileNotifications` for the PF, modifying some of the attributes if no filters are set and the logged user accessas as a delegate.
Enter PF (not PG) with some user that is a delegate of other users, so that these delegators aren't recipient of …
=> PN-5818 - empty state delegate PF

packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json, packages/pn-personagiuridica-webapp/src/component/Notifications/DesktopNotifications.tsx, packages/pn-personagiuridica-webapp/src/component/Notifications/MobileNotifications.tsx, packages/pn-personagiuridica-webapp/src/component/Notifications/__test__/MobileNotifications.test.tsx
This PR regards the notification list page for PG, in particular empty (i.e. no notifications to show) case, when the logged user is acting as delegate of another PF or a PG. In such case, the content of the "empty state" banner changes, now it should just read "Non ci sono notifiche in delega a {{PG name}} da leggere." and the link to add contact information is not included. The contents of the "empty state" banner when the logged user accesses to its own notifications is unchanged.
Just changed the `EmptyStateProps` in both `DesktopNotifications` and `MobileNotifications` for the PG, modifying some of the attributes if no filters are set and the logged user accesses as a delegate.
Enter PG (not PF) with some user that is a delegate of other users, so that these delegators aren't …
=> PN-5877 - changed message for empty state for delegate access in PG

packages/pn-commons/src/utils/notification.utility.ts
When a recipient (either PF or PG) accesses the detail of a multirecipient notification, the timeline steps will be shown using the single-recipient version of the copy, thus not including name and taxId of the recipient.  
The behavior for sender (PA) access to multirecipient notifications is not changed, i.e. timeline steps are shown including name and taxId of the recipient for each step. 
Just changed `notification.utility.ts` in pn-commons, so that the multirecipient version is used only if the recipient array includes more than one full (i.e. including all the description rather than just the recipientType) element.
Access the detail of a multirecipient notification from both sender and receiver, appreciate the difference in the timeline step descriptions (specially for events …
=> PN-5911 - timeline - single-recipient descriptions in recipient access to multi-recipient notifications

packages/pn-pa-webapp/src/App.tsx, packages/pn-pa-webapp/src/__test__/App.test.tsx, packages/pn-pa-webapp/src/api/external-registries/External-registries.api.ts, packages/pn-pa-webapp/src/navigation/OrganizationPartyGuard.tsx, packages/pn-pa-webapp/src/navigation/__test__/routes.test.tsx, packages/pn-pa-webapp/src/navigation/routes.tsx, packages/pn-pa-webapp/src/pages/NewNotification.page.tsx, packages/pn-pa-webapp/src/pages/Statistics.page.tsx, packages/pn-pa-webapp/src/redux/auth/__test__/reducers.test.ts, packages/pn-pa-webapp/src/redux/auth/actions.ts, packages/pn-pa-webapp/src/redux/auth/reducers.ts, packages/pn-pa-webapp/src/redux/auth/types.ts
Refactored the way to retrieve organization data such the name.
- getOrganizationParty has been set to deprecated and no longer used
- OrganizationPartyGuard component has been set to deprecated and removed to the routes component
- Organization data is get from user.organization of userState now
- Fixed tests
You should still see the organization name in the Header component (right side).
=> Refactored the way to retrieve organization data such the name

packages/pn-landing-webapp/src/components/Tabs.tsx
Adds z-index to tabs element in landing for dropdown element
- Adds z-index to tabs element in landing for dropdown element
In landing website on route /perfezionamento, the dropdown should show over the image when overlapped
=> fix: adds z-index to tabs element in landing for dropdown element

packages/pn-landing-webapp/pages/perfezionamento.tsx, packages/pn-landing-webapp/src/components/HeadingTitle.tsx
Replaced transition effect with Fade in Perfezionamento landing page, added padding to heading title.
- Replaced Slide transition effect with Fade
- Fixed padding issue with HeadingTitle component in mobile.
Run landing webapp and go to /perfezionamento
Fade effect is the new transition effect. Switch to mobile and you'll see padding fixed in HeadingTitle component.
=> Replaced transition effect with Fade in Perfezionamento landing page, added padding to heading title

packages/pn-commons/src/components/CodeModal/CodeModal.tsx, packages/pn-commons/src/components/CodeModal/__test__/CodeModal.test.tsx, packages/pn-personafisica-webapp/src/component/Contacts/DigitalContactsCodeVerification.context.tsx, packages/pn-personafisica-webapp/src/component/Deleghe/Delegates.tsx, packages/pn-personafisica-webapp/src/component/Deleghe/MobileDelegates.tsx, packages/pn-personafisica-webapp/src/pages/Deleghe.page.tsx, packages/pn-personagiuridica-webapp/src/component/Contacts/DigitalContactsCodeVerification.context.tsx, packages/pn-personagiuridica-webapp/src/component/Deleghe/AcceptDelegationModal.tsx, packages/pn-personagiuridica-webapp/src/component/Deleghe/DelegationsElements.tsx
Code modal can't bee closed by clicking on backdrop or pressing esc key
- Updated CodeModal component
- Login with PG or PF -> go to contacts -> add new contact -> check that code modal can't be closed by clicking on backdrop or pressing esc key
- Do the same test for the "Visualizza codice" and "Accetta" for the mandates
=> prevent code modal closing on accidental click - pn-5891

packages/pn-commons/src/services/tracking.service.ts
Changes mixpanel import in tracking.service.ts to default one in pn-commons, this should solve the get_configuration error for mixpanel track function
- Changes mixpanel import in tracking.service.ts to default one
Check that the app outside development environment logs actions correctly
=> fix: changes mixpanel import in tracking.service.ts to default one

packages/pn-commons/src/components/Data/SmartFilter.tsx, packages/pn-personagiuridica-webapp/public/locales/it/deleghe.json, packages/pn-personagiuridica-webapp/src/api/delegations/Delegations.api.ts, packages/pn-personagiuridica-webapp/src/component/Deleghe/DelegationsOfTheCompany.tsx, packages/pn-personagiuridica-webapp/src/component/Deleghe/__test__/DelegationsOfTheCompany.test.tsx, packages/pn-personagiuridica-webapp/src/models/Deleghe.ts, packages/pn-personagiuridica-webapp/src/pages/Deleghe.page.tsx, packages/pn-personagiuridica-webapp/src/pages/__test__/Deleghe.page.test.tsx, packages/pn-personagiuridica-webapp/src/redux/delegation/__test__/reducers.test.ts, packages/pn-personagiuridica-webapp/src/redux/delegation/__test__/test.utils.ts, packages/pn-personagiuridica-webapp/src/redux/delegation/actions.ts, packages/pn-personagiuridica-webapp/src/redux/delegation/reducers.ts
In PG, delegation are now filterable by taxId
- Deprecated api that returns all the names of the delegators
- Replaced filter by name with filter by taxId
PG -> login with DanteAlighieri - DivinaCommedia -> go to "Deleghe a carico" -> filter by taxId and check that delegations are filtered correctly
=> PG - filter delegation by taxId - pn-5795

packages/pn-personagiuridica-webapp/src/App.tsx, packages/pn-personagiuridica-webapp/src/api/auth/Auth.api.ts, packages/pn-personagiuridica-webapp/src/component/DomicileBanner/DomicileBanner.tsx, packages/pn-personagiuridica-webapp/src/component/DomicileBanner/__test__/DomicileBanner.test.tsx, packages/pn-personagiuridica-webapp/src/navigation/SessionGuard.tsx, packages/pn-personagiuridica-webapp/src/navigation/routes.tsx, packages/pn-personagiuridica-webapp/src/pages/Deleghe.page.tsx, packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personagiuridica-webapp/src/pages/Notifiche.page.tsx, packages/pn-personagiuridica-webapp/src/redux/auth/__test__/reducers.test.ts, packages/pn-personagiuridica-webapp/src/redux/auth/__test__/test-users.ts, packages/pn-personagiuridica-webapp/src/redux/auth/reducers.ts, packages/pn-personagiuridica-webapp/src/redux/auth/types.ts
Now we manage the permissions also for the operator with groups.
- Changed isGroupAdmin flag with hasGroup
- Replaced isGroupAdmin flag with hasGroup in all components that used it
- Removed group check inside the DomicileBanner component
- PG -> login with an admin -> check that you can view notifications (delegated and not), you can manage mandates (from the PG and to PG) and you can manage contacts
- PG -> login with a group admin -> check that you can only view delegated notifications, you can manage mandates (to PG and only associated to user group) and you cannot manage contacts
- PG -> login with operator -> check that you can view notifications (delegated and not), you cannot manage mandates and you cannot manage contacts
-  PG -> login with group operator -> check that you can …
=> manage permissions for operator with groups - pn-6007

packages/pn-personafisica-login/src/pages/login/SpidSelect.tsx
Fixed issue where SPID selectors page is not correctly viewed with browser viewport which have height less than SPID selectors itself, including mobile.
- Replaced CSS property
Make height of browser less than SPID selectors or use mobile. SPID selectors are now correctly visible.
=> Fixed issue SPID selectors view in tiny viewports

packages/pn-commons/src/utils/notification.utility.ts
There was case where array order of recipients was different from AAR array order. Fix is made by using recIndex instead of map index.
- Replaced map index with recIndex property to get recipient data
Recipient denomination and tax IDs of AAR documents name should be fine, now.
=> Used recIndex to get proper index of recipient data

packages/pn-pa-webapp/src/pages/components/Notifications/FilterNotificationsFormBody.tsx
Fixed non clickable dropdown arrow in notification filters PA.
- Removed unnecessary padding right
You shuld be able to click status dropdown arrow filter in PA notifications.
=> Fixed non clickable dropdown arrow in notification filters PA

packages/pn-pa-webapp/src/pages/components/NewApiKey/SyncFeedbackApiKey.tsx
Fix height of input in API key success page
- height of input in API key success page
Generate a new API key and will see the input with right height
=> fix: height of input in API key success page

packages/pn-commons/src/utils/__test__/notification.utility.test.ts, packages/pn-commons/src/utils/notification.utility.ts
Modified chip color for viewed status.
- Use "success" color (green) for viewed notification
- Fixed tests
Open a PA user and look for viewed notification in list. The chip color is now green.
=> Modified chip color for viewed status

packages/pn-personagiuridica-webapp/src/pages/Deleghe.page.tsx, packages/pn-personagiuridica-webapp/src/pages/__test__/Deleghe.page.test.tsx
invert tab panel for render delegation 
- invert tab panel
when you click on deleghe page you see for the first "Deleghe a carico dell'impresa"
=> fix: invert tab panel for rendere delegation

packages/pn-personagiuridica-webapp/src/component/Deleghe/DelegationsElements.tsx
Change name in revocation modal from user name to organization name
Check that in the delegation revocate modal the organization name is shown instead of the user name
=> fix: change name in revocation modal from user name to organization name

packages/pn-pa-webapp/public/locales/it/common.json, packages/pn-personagiuridica-webapp/public/locales/it/common.json
Changes copy 'Referente amministrativo' to 'Amministratore'
Check that in the partyswitch component (top-right) the role label shows 'Amministratore' instead of 'Referente amministrativo' for mittente and persona giuridica apps
=> fix: change copy 'Referente amministrativo' to 'Amministratore'

packages/pn-personagiuridica-webapp/public/locales/it/common.json
Just changed the platform name for PG to "SEND - Servizio Notifiche Digitali".
- Modified the corresponding entry in the `common.json` file for PG.
Just enter PG, the title at top left should read as indicated.
=> PN-6745 - fix/change platform name for PG

packages/pn-pa-webapp/public/locales/it/notifiche.json, packages/pn-personafisica-webapp/public/locales/it/notifiche.json, packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json
Change the title for the SEND_ANALOG_FEEDBACK events detected as KO.
Changed the corresponding entries in the `notifiche.json` file for PF / PG / PA.
Enter the detail of an analog-flow notification for which the shipping failed.
Examples in TEST: 
- IUN WKUZ-VLKN-KVYD-202306-X-1 - comune di Palermo - cristoforocolombo.
- IUN MAZG-EYTL-JKGR-202306-D-1 - comune di Palermo - leonardo
=> fix/PN-6715 - changed send-analog-error title in PA / PF / PG

packages/pn-commons/src/components/NotificationDetail/NotificationPaidDetail.tsx
Removed unnecessary character from notification paid detail
- Removed character
Go to a paid notification and you'll not see unnecessary characters under 'type of recipient'
=> fix: removed unnecessary character from notification paid detail

packages/pn-personagiuridica-webapp/src/component/Deleghe/DelegationsOfTheCompany.tsx
A group administrator cannot modify/revoke a delegation
- Removed action menù in DelegationsOfTheCompany.tsx
- DanteAlighieri -> Convivio Spa -> "Deleghe a carico dell'impresa" -> check that the action menù is visible
- EugenioMontale -> Convivio Spa -> "Deleghe a carico dell'impresa" -> check that the action menù is NOT visible
=> hide menu when user is a group administrator - pn-6847

packages/pn-commons/src/types/NotificationDetail.ts, packages/pn-commons/src/utils/__test__/notification.utility.test.ts, packages/pn-commons/src/utils/__test__/test-utils.ts, packages/pn-commons/src/utils/notification.utility.ts
Implemented a little modification on how timeline events are sorted to be shown in the notification detail, so that whenever the timestamp of two events is identical, the one having a least index in the list of events included in the notification-detail API response is considered as precedent (so is shown *below* in the FE timeline).
- Added the index taken the API response, to the FE representation of each timeline event.
- Changed the sorting function defined in `notification.utility.ts`, to use the indexes for comparison if the timestamps are identical.
- Added a specific test.
- Fixed the test which analyses the whole notification FE representation, adding the timeline event indexes to the "witness" notification structure used for comparison.
Enter a notification having two timeline …
=> Fix/PN-6869 - simultaneous timeline events

packages/pn-commons/src/utils/costants.tsx
Fixed the links 'Certificazioni' and 'Sicurezza delle Informazioni' present in the third column in the footer for the initial page (the page that leads to the login) for the PA / PF / PG apps. Now clicking these links lead to the right URLs.
Landing page had already the right links prior to this PR.
Just changed the pointers in the `costants.tsx` file (SIC) in `pn-commons`.
Enter the initial page for PA / PF / PG, click the indicated links in the footer; see image below. You should be directed to pages inside the PagoPA site referring to the subject mentioned in each link.
=> fix/PN-7032 - fixed links 'Certificazioni' and 'Sicurezza delle Informazioni' in footer

packages/pn-personafisica-webapp/src/pages/NuovaDelega.page.tsx, packages/pn-personagiuridica-webapp/src/pages/NuovaDelega.page.tsx
This PR implements a fix for the action of deleting the end-of-delegation date in the new delegation ("Nuova delega") form.  
- Before this PR, the date was reset to 01/01/1970.  
- After this PR, the date contents actually get empty.
Just retouched how the value of the end-of-delegation date is defined in `NuovaDelega.page.tsx`.
Just access to the creation of a new delegation in both PF and PG, clean the contents of the end-of-delegation ("Termine delega") field. The field should actually be empty. That's all.
=> fix/PN-7063 - date in new delegation clears when user deletes the content

packages/pn-commons/src/components/CodeModal/CodeModal.tsx, packages/pn-commons/src/components/DisclaimerModal.tsx, packages/pn-personafisica-webapp/src/component/Contacts/DigitalContactElem.tsx, packages/pn-personafisica-webapp/src/component/Deleghe/ConfirmationModal.tsx, packages/pn-personafisica-webapp/src/component/Deleghe/__test__/ConfirmationModal.test.tsx, packages/pn-personagiuridica-webapp/src/component/Contacts/DigitalContactElem.tsx, packages/pn-personagiuridica-webapp/src/component/Deleghe/ConfirmationModal.tsx, packages/pn-personagiuridica-webapp/src/component/Deleghe/__test__/ConfirmationModal.test.tsx
Fixed mobile modal buttons and tests.
- Fixed flex-direction in mobile modals view
- Fixed tests
For example login in PF and revoke or make a delegation. In desktop buttons sequece is "Cancel" -> "Submit". In mobile should be now as "Submit" -> "Cancel"
=> Fixed mobile modal buttons and tests

packages/pn-pa-webapp/src/pages/components/Notifications/MobileNotifications.tsx
Hide groups if empty on mobile notifications
- Edit mobile notifications
On a PA go to notifications mobile and you should not see the group labels if groups are empty
=> fix: hide groups if empty on mobile notifications

packages/pn-commons/src/components/PnBreadcrumb.tsx, packages/pn-pa-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx
Removed icons from breadcrumb of notification detail. Fixed also mobile alignment of breadcrumb
- Removed icon from breadcrum
- Fixed mobile alignment
Go to notification detail of PA, PF and PG and breadcrumb shouldn't have the email icon. On mobile it should be inline
=> fix: removed email icon from breadcrumb and fixed mobile alignment

packages/pn-commons/src/components/NotificationDetail/NotificationDetailTable.tsx, packages/pn-commons/src/components/NotificationDetail/NotificationDetailTimeline.tsx, packages/pn-pa-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-pa-webapp/src/pages/components/Notifications/MobileNotifications.tsx, packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx
Fixed alignment of notification detail table on mobile view. Now, on mobile, the flex direction is set to column.
Also removed some padding bottom from notification timeline box.  There's still some padding because of Timeline MUI Italia component that must be fixed.
- Fixed alignment of notification detail table
On PA/PF/PG go to a notification detail and set to mobile view.
=> fix: alignment of notification detail table on mobile

packages/pn-personafisica-webapp/src/component/Contacts/CourtesyContacts.tsx, packages/pn-personafisica-webapp/src/component/Contacts/IOContact.tsx, packages/pn-personafisica-webapp/src/component/Contacts/InsertLegalContact.tsx, packages/pn-personafisica-webapp/src/component/Contacts/LegalContactsList.tsx, packages/pn-personafisica-webapp/src/component/Contacts/__test__/IOContact.test.tsx, packages/pn-personagiuridica-webapp/src/component/Contacts/CourtesyContacts.tsx, packages/pn-personagiuridica-webapp/src/component/Contacts/InsertLegalContact.tsx, packages/pn-personagiuridica-webapp/src/component/Contacts/LegalContactsList.tsx
Fixed issue with voice over in Windows 11 where when the user switches to the contact pages (both PF and PG), the voice over automatically talk about banners inside the page.
- Changed roles for Alert component from "alert" to "banner"
- Fixed a test
The voice over should not automatically talk about banners in contacts page now.
=> Fixed issue with voice over in Windows 11

packages/pn-pa-webapp/src/navigation/SessionGuard.tsx, packages/pn-personafisica-webapp/src/App.tsx, packages/pn-personafisica-webapp/src/navigation/SessionGuard.tsx, packages/pn-personafisica-webapp/src/navigation/routes.tsx, packages/pn-personagiuridica-webapp/src/navigation/SessionGuard.tsx
Added skeleton also when validating selfcare token to avoid a no feedback case
- Added skeleton in SessionGuard component (pf/pg/pa)
Use emulator or wait for the pr being merged. Clear the browser's cache, navigate to the app and check that during page loading, there aren't no-feedback cases (i.e. white page without skeleton or loading)
=> Loading feedback in mobile devices - Fix/pn 7076

packages/pn-commons/src/components/NotificationDetail/NotificationDetailTimeline.tsx
Changed transition direction for mobile timeline details.
- Drawer anchor set from "left" to "bottom" as required
Just enter in any webapp via mobile and open timeline detail. The drawer will appear from bottom now.
=> Change transition direction for mobile timeline details

packages/pn-commons/src/components/AppStatus/AppStatusRender.tsx
Added some aria-label to AppStatus page 
- Added aria-labels
On PF/PA/PG go to "Stato della piattaforma" with 'VoiceOver' on MacOS and with 'Assistente Vocale' on Windows and go to "Ultimo aggiornamento" label and table's title
=> fix: accessibility of AppStatus page

packages/pn-commons/src/components/FileUpload.tsx, packages/pn-commons/src/components/__test__/FileUpload.test.tsx, packages/pn-commons/src/utils/__test__/file.utility.test.ts, packages/pn-commons/src/utils/file.utility.ts, packages/pn-pa-webapp/public/locales/it/common.json
Added file size limit to FileUploader component with default value as 200MB.
- Added new optional parameter to FileUploader fileSizeLimit with default value
- Added new test
In PA you have to upload a > 200MB file and test the error message.
=> Added file size limit to FileUploader component

packages/pn-pa-webapp/src/App.tsx, packages/pn-pa-webapp/src/index.tsx, packages/pn-personafisica-webapp/src/App.tsx, packages/pn-personafisica-webapp/src/index.tsx, packages/pn-personagiuridica-webapp/src/App.tsx, packages/pn-personagiuridica-webapp/src/index.tsx
The axios interceptor was set many times, once for each re-render of the main `App` component, in all of PA / PF / PG apps. This led to wrong behavior.  
The goal of this PR is to fix this initialization action so that it runs exactly once when the webapp is loaded.
- Moved the code that sets the action interceptor from the `App` component to the `index.tsx` file, along with other one-time initialization actions (those which were moved from previously static code, cfr. https://github.com/pagopa/pn-frontend/pull/674).
Just open either app, it should run normally.
For more details, you can check that the interceptors are added exactly once by adding an additional interceptor that sends something to console for a specific API call, this is an example for PA.
``` …
```
=> PN-7557 - Shifted Axios interceptor init from App to index.tsx in PA / PF / PG

packages/pn-commons/src/components/CustomTooltip.tsx, packages/pn-commons/src/components/__test__/CustomTooltip.test.tsx
Fixed clipping statuses tooltips.
- Removed disablePortal option
- Reordered imports, for test too.
How to replicate the bug: resize window heigh to make visible only one row then do the hover to status chip. The tooltip should be correctly visible now.
=> Fixed clipping statuses tooltips

packages/pn-commons/src/hooks/useRewriteLinks.ts, packages/pn-commons/src/utils/__test__/dom.utility.test.tsx, packages/pn-commons/src/utils/dom.utility.ts, packages/pn-commons/src/utils/index.ts, packages/pn-pa-webapp/src/pages/PrivacyPolicy.page.tsx, packages/pn-personafisica-webapp/src/pages/PrivacyPolicy.page.tsx, packages/pn-personagiuridica-webapp/src/pages/PrivacyPolicy.page.tsx
Refactored links replace in Privacy pages.
- Removed setTimeout() to useRewriteLinks hook
- Added DOM utility that waits for element to be in the DOM
- And tests
Open any Privacy Page. The side menu links should still redirect to page anchors.
=> Refactored links replace in Privacy pages

packages/pn-pa-webapp/package.json, packages/pn-validator/src/ruleValidators/BooleanRuleValidator.ts, packages/pn-validator/src/ruleValidators/StringRuleValidator.ts, packages/pn-validator/src/rules/IsBoolean.ts, packages/pn-validator/src/rules/IsEqual.ts, packages/pn-validator/src/rules/IsOneOf.ts, packages/pn-validator/src/types/CommonRules.ts, packages/pn-validator/src/types/TypeRules.ts
This PR aims to fix a weird issue that causes all the tests in PA to fails in certain computers and OSs and it happens only in PA. In this case is on Windows 11 x64. The replacemente is simple. It's just another way to check for files with extensions .ts or .tsx
- package.json for PA
Check if builds and tests are ok.
=> Replaced regex for testPathIgnorePattern parameter in PA

packages/pn-commons/src/utils/string.utility.ts, packages/pn-pa-webapp/src/pages/components/NewNotification/Recipient.tsx, packages/pn-pa-webapp/src/pages/components/NewNotification/__test__/Recipient.test.tsx
Added regex validation for zip input field in recipients step.
- Added zip regex to dataRegex in string.utility.ts
- Reworked validation in recipient.tsx
- Reworked validation test in recipient.test.tsx and meanwhile fixed a bug for municipality validation test
Try to add forbidden character in zip field such "20100&". An error should appear.
=> Added regex validation for zip input field

packages/pn-commons/src/hooks/useDownloadDocument.ts
Fix Popup blocker on safari
- Open link on the same window
Try to click a link. You should see the attachment on the same window
=> Avoid popup block on ios opening the attachment on the same window

packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
used Trans component to show bold text in Api Keys's modals
- Modified modals content on Api Keys page
On PA go to Api Keys page and try to Rotate, block, delete, or activate an api key. You should see the api key name with bold weight
=> PN-8056 - used Trans component to show bold text in Api Keys's modals

packages/pn-commons/src/components/NotificationDetail/NotificationPaymentRecipient.tsx, packages/pn-commons/src/components/PnBreadcrumb.tsx, packages/pn-pa-webapp/public/conf/env/config.dev.json, packages/pn-personafisica-webapp/public/conf/env/config.dev.json, packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx, packages/pn-personagiuridica-webapp/public/conf/env/config.dev.json, packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personagiuridica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
Added link to FAQ for multi payment notification and on cancelled notification box. 
Also fixed some wrong urls of landing site in configuration files.
- Added link to FAQ
- Fix Landing site url on DEV
Start PF or PG and go to a notification with payments and click on "Come mai" link. Also go to a cancelled notification and click on "Scopri di più" link
=> PN-8243 - FAQ on multi-payment notification

packages/pn-commons/src/components/CodeModal/CodeModal.tsx
Fixed wrong label path translation.
- Fixed wrong label path translation from 'code_copied' to 'deleghe.code_copied'
Translation of tooltip when copy code should be fine now.
=> Chore: Fixed wrong label path translation

packages/pn-commons/src/utility/__test__/notification.utility.test.ts, packages/pn-commons/src/utility/notification.utility.ts, packages/pn-pa-webapp/src/__mocks__/Notifications.mock.ts, packages/pn-pa-webapp/src/api/notifications/Notifications.api.ts, packages/pn-pa-webapp/src/components/Notifications/DesktopNotifications.tsx, packages/pn-pa-webapp/src/components/Notifications/MobileNotifications.tsx, packages/pn-pa-webapp/src/components/Notifications/NotificationDetailTableSender.tsx, packages/pn-personafisica-webapp/src/__mocks__/Notifications.mock.ts, packages/pn-personafisica-webapp/src/api/notifications/Notifications.api.ts, packages/pn-personafisica-webapp/src/components/Notifications/DesktopNotifications.tsx, packages/pn-personafisica-webapp/src/components/Notifications/MobileNotifications.tsx, packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx, packages/pn-personagiuridica-webapp/src/__mocks__/Notifications.mock.ts, packages/pn-personagiuridica-webapp/src/api/notifications/Notifications.api.ts, packages/pn-personagiuridica-webapp/src/components/Notifications/DesktopNotifications.tsx, packages/pn-personagiuridica-webapp/src/components/Notifications/MobileNotifications.tsx, packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personagiuridica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
Moved formatDate from api parsing to tables components. This allows the today label to be properly updated when switch language
- Done for PA, PG and PF
- Reworked mocks for tests
Enter a webapp with current day notifications. Switch language to whatever you want. Now the "Oggi" should be translated.
=> Fixed issue with today label date

packages/pn-personafisica-webapp/public/locales/en/deleghe.json, packages/pn-personagiuridica-webapp/public/locales/en/deleghe.json
replaced translation string for Active in delegation page.
- deleghe.json for PF and PG
Enter PF or PG and go in delegations page, look for active one then switch in English language. It should be labeled as 'active' and not in 'activated'
=> Chore: replaced translation string for Active in delegation page

packages/pn-personafisica-webapp/public/locales/en/notifiche.json, packages/pn-personagiuridica-webapp/public/locales/en/notifiche.json
replaced strings traslation for subtitle in notification detail page.
- notifiche.json for PF and PG replaced occurrences of "payment alerts" in "payment notices"
Check subtitle in notification detail page.
=> Chore: replaced strings traslation for subtitle in notification detail page

packages/pn-commons/src/utility/costants.tsx, packages/pn-pa-webapp/public/locales/de/common.json, packages/pn-pa-webapp/public/locales/en/common.json, packages/pn-pa-webapp/public/locales/fr/common.json, packages/pn-pa-webapp/public/locales/it/common.json, packages/pn-pa-webapp/public/locales/sl/common.json
Fixed missing translation for Privacy Policy in footer.
- Fixed Constants file
- Added missing translation in common.json of PA
Translation of Privacy Policy in Footer should be ok now.
=> Fixed missing translation for Privacy Policy in footer

packages/pn-pa-webapp/src/components/Notifications/NotificationPaymentF24.tsx
Fix overflow of F24 file name on notification payment box of sender
- Added box with flexWrap to avoid overflow of items
NZKT-TQMQ-TWQW-202310-K-1 from Comune di Palermo in TEST. F24 items should not overflow the container
=> PN-8735 - Fix overflow of f24 items on notification payment box of PA

packages/pn-pa-webapp/src/components/NewNotification/NewNotificationCard.tsx
Added mobile support for NewNotificationCard component in the same way as done with modals.
- Modified NewNotificationCard component
Enter PA, create new notification in mobile mode. You should see previous and submit buttons in column view.
=> Added mobile support for NewNotificationCard buttons

README.md, bin/cleanup.mjs, package.json
Added a script that enables recursive removal of node modules, compatible with all operating systems.
- added a new script for recursive `node_modules` removal into `/bin` folder.
- updated the command `clean` in order to execute the script.
- removed commands: `clean:win` and `clean:nx`.
The script has been tested and validated on various platforms, including Windows and Linux.
Run the script from the root project directory with the comand `yarn clean`. It will scan for and remove `node_modules` both in the root directory and within nested packages.
=> chore: added a script into bin folder to remove node_modules recursively

packages/pn-pa-webapp/src/__mocks__/NewNotification.mock.ts, packages/pn-pa-webapp/src/components/NewNotification/__test__/Recipient.test.tsx, packages/pn-pa-webapp/src/utility/__test__/validation.utility.test.ts, packages/pn-pa-webapp/src/utility/validation.utility.ts
Added taxId validation according to PF or PG recipient.
This means that you cannot add physical person taxId in PG or viceversa add legal person taxId in PF
- Reworked taxIdDependingOnRecipientType function
- Added / edited tests
Enter PA and start new notification, then enter recipients step. Set as legal person and try to add a physical person taxId. An error should appear.
=> Added taxId validation according to PF or PG recipient

packages/pn-pa-webapp/src/components/Notifications/NotificationDetailTableSender.tsx, packages/pn-pa-webapp/src/components/Notifications/__test__/NotificationDetailTableSender.test.tsx
Cancel notification button is only shown when the user have administrator role.
- Added check via useHasPermissions hook
- Added new test
Enter PA as operator. You shouldn't see cancel notification button in notification detail.
=> Cancel notification button shown as administrator role only

aws-cdn-templates/one-cdn.yaml, packages/pn-personagiuridica-webapp/src/App.tsx
The behavior of the support link in PG has been modified for logged-in users.
- Added the link `${SELFCARE_BASE_URL}/assistenza` to `handleAssistanceClick()` once the user is logged in.
- Added on CDN config file `/assistenza`.
Simply run `yarn start` for PG and check if the assistance link redirects to a different path after logging in.
=> PN-8797-fe-pg-nel-portale-pg-sostituire-lemail-di-assistenza-nellheader-con-il-link-assistenza

packages/pn-pa-webapp/src/App.tsx
The behavior of the support link in PA has been modified for logged-in users.
- Added the link `${SELFCARE_BASE_URL}/assistenza` to `handleAssistanceClick()` once the user is logged in.
Simply run `yarn start` for PA and check if the assistance link redirects to a different path after logging in.
=> PN-8811-fe-pa-nel-portale-pa-sostituire-lemail-di-assistenza-nellheader-con-il-link-assistenza

packages/pn-commons/src/__mocks__/ExternalRegistry.mock.ts, packages/pn-commons/src/__mocks__/NotificationDetail.mock.ts, packages/pn-commons/src/components/NotificationDetail/NotificationPaymentRecipient.tsx, packages/pn-commons/src/components/NotificationDetail/NotificationPaymentTitle.tsx, packages/pn-commons/src/components/NotificationDetail/__test__/NotificationPaymentRecipient.test.tsx, packages/pn-commons/src/components/NotificationDetail/__test__/NotificationPaymentTitle.test.tsx, packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx, packages/pn-personagiuridica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
Sometimes the payment attachment (no F24) is included in the act and not in the payment. So when the user select a payment, the button to download the attachment must be shown/hidden based on this condition.
We also added a delay of 1 second after the selection, before the payment is enabled
- Updated NotificationPaymentRecipient to manage the logic described above
- Created NotificationPaymentTitle component to have a cleaner code
- Updated the tests
- Reworked the NotificationPaymentRecipient component to reduce the complexity
- Login with pf on dev (colombo) -> search the notification AGYX-HKJK-WGTD-202311-T-1 -> select one payment and check that the button to download the attachment is shown/hidden correctly
- Login with pf on dev (ada) -> search the notification …
=> Payments whit no attachment - pn-8869

packages/pn-pa-webapp/public/locales/de/notifiche.json, packages/pn-pa-webapp/public/locales/en/notifiche.json, packages/pn-pa-webapp/public/locales/fr/notifiche.json, packages/pn-pa-webapp/public/locales/it/notifiche.json, packages/pn-pa-webapp/public/locales/sl/notifiche.json, packages/pn-personafisica-webapp/public/locales/de/notifiche.json, packages/pn-personafisica-webapp/public/locales/en/notifiche.json, packages/pn-personafisica-webapp/public/locales/fr/notifiche.json, packages/pn-personafisica-webapp/public/locales/it/notifiche.json, packages/pn-personafisica-webapp/public/locales/sl/notifiche.json, packages/pn-personagiuridica-webapp/public/locales/de/notifiche.json, packages/pn-personagiuridica-webapp/public/locales/en/notifiche.json, packages/pn-personagiuridica-webapp/public/locales/fr/notifiche.json, packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json, packages/pn-personagiuridica-webapp/public/locales/sl/notifiche.json
Added the copy for a new kind of analog workflow attachment, namely 23I. Done for all languages (this was easy since the copy is identical to that of an already existing analog workflow attachment kind, i.e. AR), and for PA / PF / PG.
Just added the needed elements in the different `notifiche.json` files.
Unfortunately there is yet no timeline element including an attachment of kind 23I. So in order to properly test the added copies, we have to do some mocking.
This is what I did for PG in `Notifications.api.ts` 
``` 
getReceivedNotification: (
iun: string,
mandateId?: string
): Promise<NotificationDetailForRecipient> =>
apiClient.get<NotificationDetail>(NOTIFICATION_DETAIL(iun, mandateId)).then((response) => {
if (response.data) {
// added from here
if (iun === …
```
=> Added copy for new analog-workflow-attachment-kind 23I

packages/pn-personafisica-webapp/public/locales/it/deleghe.json, packages/pn-personagiuridica-webapp/public/locales/it/deleghe.json
Removed the note about of the limit of 7 days to accept a delegation, for both PF and PG.
Just changed the corresponding entries in the `deleghe.json` files in PF and PG, erasing the note about the limit that was added through previous PRs.
*Note*: this note was present only for the messages in Italian language.
Enter either PF or PG, go to "Deleghe". The message which used to include the removed note are present in two points, see below. In neither case the text "Il codice è valido per 7 giorni dalla creazione della richiesta di delega." should be present.
(1) 
In the form for a new delegation.
(2)
In the modal that appears when the option "Mostra codice" appears in the contextual menu for a pending ("In attesa di conferma") delegation
And here's the modal
The following is an example of …
=> Removed note about limit of 7 days to accept a delegation

packages/pn-personafisica-login/src/App.tsx, packages/pn-personafisica-login/src/utility/mixpanel.ts
Disabled the generation of mixpanel events in the login portal.
Just modified the `trackEventByType` to make it a no-op.
Enter the login portal, you should see in the dev tools console that no events related to mixpanel (issued by `tracking.service`) should be shown.
=> Disabled mixpanel in login portal

packages/pn-pa-webapp/src/components/ApiKeys/ApiKeyDataSwitch.tsx, packages/pn-pa-webapp/src/components/ApiKeys/__test__/ApiKeyDataSwitch.test.tsx
Added checks for empty groups in API Keys. It hide copy to clipboard button under status column and also hide view groups id item in contex menu when there are no groups.
- Edited ApiKeysDataSwitch
- Added new tests
Login PA with user without groups (example: grossini, comune di Sappada, DEV). Copy to Clipboard button and view groups id should not be visible.
=> Added checks for empty groups in API Keys

packages/pn-personagiuridica-webapp/src/components/Deleghe/DelegationsElements.tsx
Modal wich edits delegators groups won't close when you click Confirm. The PR aims to fix it.
- Fixed issue with non closing modal on edit groups in delegators
- Fixed also issue when context menu won't close when you click "Edit"
Modal should close correctly now.
=> Fixed issue with non closing modal on edit groups

packages/pn-personafisica-webapp/src/pages/PrivacyPolicy.page.tsx
Fix logout from privacy policy page 
- Removed awaitForElement
On PF go to privacy policy page ("Informativa privacy" link on footer) and try to logout from header
=> PN-9541 - Logout from Privacy Policy page

packages/pn-personafisica-webapp/src/App.tsx, packages/pn-personagiuridica-webapp/src/App.tsx
As decided, logging out from the ToS and PP pages should not redirect the user to the login page but instead keep them on those pages as non-logged in
- Edited handleUserLogout function
On PF/PG try to go on PP or ToS page and click on logout button. You should remain on that page
=> PN-9541 - Logout from ToS and PP page

packages/pn-pa-webapp/src/api/notifications/__test__/notifications.routes.test.ts, packages/pn-pa-webapp/src/api/notifications/notifications.routes.ts, packages/pn-personafisica-webapp/src/api/notifications/__test__/notifications.routes.test.ts, packages/pn-personafisica-webapp/src/api/notifications/notifications.routes.ts, packages/pn-personagiuridica-webapp/src/api/notifications/__test__/notifications.routes.test.ts, packages/pn-personagiuridica-webapp/src/api/notifications/notifications.routes.ts
Changed API version from 2.1 to 2.3 for notification detail and notification request for PA, PF, PG
Access as PA sender and:
- try to read a notification (single recipient, cancelled, with payments)
- try to create a new notification
Access as PF or PG:
- try to read a notification (single recipient, cancelled, with payments, as delegate)
=> feat: added new version segment for notification detail and creation API

packages/pn-commons/src/models/NotificationDetail.ts, packages/pn-commons/src/models/PaymentCache.ts, packages/pn-personafisica-webapp/src/redux/notification/actions.ts, packages/pn-personagiuridica-webapp/src/redux/notification/actions.ts
Added `eventTimestamp` to paymentCache validation schema. This property came from timeline.
- Changed validation schema
- Changed return statement on redux 
When opening a notification you should't see warning about cache validation. 
To test the return, you should pay a notice and when you return on SEND you should see the notice updated
=> chore: fixes on payment caching

packages/pn-commons/src/__mocks__/NotificationDetail.mock.ts, packages/pn-commons/src/models/NotificationDetail.ts, packages/pn-commons/src/utility/__test__/notification.utility.test.ts, packages/pn-commons/src/utility/index.ts, packages/pn-commons/src/utility/notification.utility.ts, packages/pn-pa-webapp/public/locales/it/notifiche.json, packages/pn-pa-webapp/src/__mocks__/NotificationDetail.mock.ts, packages/pn-pa-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-pa-webapp/src/pages/__test__/NotificationDetail.page.test.tsx, packages/pn-personafisica-webapp/public/locales/it/notifiche.json, packages/pn-personafisica-webapp/src/__mocks__/NotificationDetail.mock.ts, packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx, packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json, packages/pn-personagiuridica-webapp/src/__mocks__/NotificationDetail.mock.ts, packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personagiuridica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
Implemented alert in notificationDetail for alternative-RADD for pg/pf/pa when documents are withdrawn by recipients.
- added radd property in NotificationDetail.ts
- populated radd property in notification.utility.ts
- added Alert component with title in DOCUMENTI ALLEGATI box in pg/pf/pa
- Login as PF, go to notification a notification (es. VHYJ-LJWY-QWEG-202402-E-1 in Cristoforo Colombo from Comune di Palermo) and check DOCUMENTI ALLEGATI box has the success alert
- Login as PG, go to a notification and check DOCUMENTI ALLEGATI box has the success alert
- Login as PA, go to notification (es. THYR-YRDN-ULPE-202402-E-1 Convivio Spa from Comune di Palermo) and check DOCUMENTI ALLEGATI box has the success alert
=> feat/PN-9684: implemented alert in notificationDetail for alternative-RADD

packages/pn-personafisica-login/src/pages/login/SpidSelect.tsx
In login page for PF the list of IDPs name should be read correctly by voiceover.
- Added aria-label with IDP name to list of IDPs
Go to login page and read the list of IDPs using voiceover: should read the name of the IDP instead of pulsante
=> fix: added aria-label to button with IDP name

packages/pn-pa-webapp/src/__mocks__/NotificationDetail.mock.ts, packages/pn-pa-webapp/src/components/Notifications/NotificationPaymentPagoPa.tsx, packages/pn-pa-webapp/src/components/Notifications/__test__/NotificationPaymentPagoPa.test.tsx
Remove link to pagopa bill when attachment is not available in notification detail
Login as PA, open a notification (_AYTV-LVQL-QVJW-202403-W-1_ can be used in Comune di Palermo) and check link "Avviso PagoPA" is not there.
=> fix(PN-10232): remove link to pagopa bill when  not available attachment

packages/pn-personafisica-webapp/src/pages/NuovaDelega.page.tsx, packages/pn-personagiuridica-webapp/src/pages/NuovaDelega.page.tsx
Reduce spaces between fields in NuovaDelega page
- added condition to margin top and flex property in case of mobile/desktop in box for choosing PersonaFisica
- added condition to margin top and flex property in case of mobile/desktop in box for choosing PersonaGiuridica
_As mobile_ login as PF, go to Deleghe section and go to Aggiungi nuova delega page. Check in new page the distance between Cognome and Codice fiscale and Ragione Sociale and Codice fiscale is normal.
_As mobile_ login as PG go to Deleghe section and go to Aggiungi nuova delega page. Check in new page the distance between Cognome and Codice fiscale and Ragione Sociale and Codice fiscale is normal.
=> fix(PN-9711): reduce spaces between fields in NuovaDelega page

packages/pn-personagiuridica-webapp/src/App.tsx, packages/pn-personagiuridica-webapp/src/pages/Deleghe.page.tsx
- add useEffect in Deleghe component
- update to DELEGHE the route of item in SideMenu component
Login as PG, go to Deleghe page. Click on "Delegati dall'impresa" tab, then click on "Deleghe" in side menu. Check if page is updated to "Deleghe a carico dell'impresa"
=> fix(PN-10122): add useEffect to update value for active tab in Deleghe

packages/pn-pa-webapp/src/components/NewNotification/Attachments.tsx, packages/pn-pa-webapp/src/components/NewNotification/__test__/Attachments.test.tsx
Clear attachment name on remove document in order to re-enable CTA "Invia".
- Clear field
Try to create a new notification. Upload a new attachment and then delete it. You should see the field "Nome dell'atto" cleared.
=> PN-9835 - Clear name of attachment on remove document

packages/pn-pa-webapp/src/index.css, packages/pn-personafisica-login/src/index.css, packages/pn-personafisica-webapp/src/index.css, packages/pn-personagiuridica-webapp/src/index.css
Remove the outline from the cookie banner
- Edited CSS 
Edit the `config.json` file and remove "-test" at the end of the `OT_DOMAIN_ID` key. Then, start PF, PA, PG, and check that the cookie banner has no outline.
=> PN-6578 - Remove the outline from the cookie banner

packages/pn-commons/src/components/AppStatus/AppStatusBar.tsx, packages/pn-commons/src/components/AppStatus/AppStatusRender.tsx, packages/pn-commons/src/components/TitleBox.tsx, packages/pn-personafisica-webapp/src/components/Contacts/CourtesyContacts.tsx, packages/pn-personafisica-webapp/src/components/Contacts/IOContact.tsx, packages/pn-personafisica-webapp/src/components/Contacts/LegalContactsList.tsx, packages/pn-personafisica-webapp/src/pages/Contacts.page.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/CourtesyContacts.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/LegalContactsList.tsx, packages/pn-personagiuridica-webapp/src/pages/Contacts.page.tsx
Make the "Li trovi qui" link focusable and clickable with the `Enter` key. Also, removed `tabIndex` from all titles, subtitles and info box as only interactive elements should be focusable.
- Replaced `Link` with `ButtonNaked` components to enable `onClick` with the `Enter` key.
- Removed some `tabIndex` properties from text elements and info box
On the Contacts page of PF and PG, try to navigate using the `Tab` key. You should only be able to navigate through interactive elements. Replicate the test on the `AppStatus` page as well.
=> PN-11288 - Focusable elements on contacts page

packages/pn-pa-webapp/src/components/Statistics/FilterStatistics.tsx
This code fixes some bugs that were causing date filter not to properly reset to its initial value when the user specifies an invalid date right after the page reload (initial state).
This bug was also leading to not apply the immediately subsequent filter choice.
- change FilterStatistics component logic to solve issues including:
1.   filter reset
2.   set a new value right after point 1
Prerequisite: a IS_STATISTICS_ENABLE env var should be defined and set to true
- using a previous version of the app (branch develop) replicate the user interaction available on the corresponding Jira task and go on following what described in the first comment of the same task for another issue connected with the one reported. Then test the component behaviour after applying the changes contained in …
=> fix/PN-11517 - not resetting the filter to its initial value

packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
The link on the ApiKeys page does not open in a new tab.
- added `target='_blank'` to ensure the link opens in a new browser tab
Run PA and verify the link opens a new tab.
=> PN-10685-fe-pa-link-invio-notifiche-e-accesso-alle-informazioni-non-rimanda-a-uno-nuovo-tab-sul-browser

packages/pn-commons/src/components/Illustrations/IllusStatistics.tsx
This PR fixes a bug causing the IllusStatistics component not to scale down and the subsequent overflowing beyond its container limits on low resolution screens.
- set max-width and max-height css properties inside the IllusStatistics component to its container size
Prerequisite: IS_STATISTICS_ENABLE env var should be defined and set to true
- Start pa-webapp
- navigate to Statistics page and apply a date filter which causes no data to be available into at least one of the page components or login using a PA which has less than 100 notifications in order to force the empty state
- Reduce the screen resolution and verify the image in question is reduced accordingly
=> fix/PN-11520 - IllusStatistics component not scaling reducing screen resolution

packages/pn-pa-webapp/src/components/Statistics/FilterStatistics.tsx
This PR resolves two layout bugs on the Sender Dashboard that were causing the elements belonging to the date filter
1. break their mutual alignement
2. getting too close one each other
reducing the windows horizontal resolution.
Prerequisite: IS_STATISTICS_ENABLED env var should be declared and set to true in pa config.json
- Login into PA webapp and navigate to Sender Dashboard
- using the 'device mode' visualization on the browser verify what follows:
-   reducing the window width the quick filters move above the datepickers before their alignment breaks
-   there's a certain margin between every element of the component
=> Fix/PN-11513-11519 - Filter elements not aligned and too close one each other

packages/pn-pa-webapp/src/models/Statistics.ts
This code resolves an error on DeliveryMode model which was causing the FE to crash.
- changes DigitalErrorTypes.INVALID_PEC value to meet openapi specs
Follow the steps to reproduce the error, available on the task description, and verify the application works fine.
=> fix/PN-11775 - resolve model error causing pa-webapp to crash

packages/pn-commons/src/components/Data/SmartTable/SmartFilter.tsx
Close SmartFilter mobile modal on submit 
- Add ref to SmartFilter component
On PG Mobile, try to filter the company's delegations. Upon clicking submit, the modal should close.
=> PN-10628 - Close SmartFilter mobile modal on submit 

packages/pn-pa-webapp/src/components/Statistics/FilterStatistics.tsx, packages/pn-pa-webapp/src/models/Statistics.ts
This PR changes the default value for sender dashboard filter to 12 months and rearrange quick choices in descending order
- Go to Sender Dashboard and verify quick choices are in a descending order and the filter is set to "12 months" by default
- Make some changes, reset the filter and verify the value is set set again to default
=> fix/PN-11562 - change default value and order for sender dashboard quick filters

packages/pn-validator/src/ValidatorBuilder.ts, packages/pn-validator/src/__test__/ValidatorBuilder.test.ts, packages/pn-validator/src/ruleValidators/CommonRuleValidator.ts, packages/pn-validator/src/ruleValidators/__test__/ArrayRuleValidator.test.ts, packages/pn-validator/src/ruleValidators/__test__/CommonRuleValidator.test.ts, packages/pn-validator/src/ruleValidators/__test__/DateRuleValidator.test.ts, packages/pn-validator/src/ruleValidators/__test__/NumberRuleValidator.test.ts, packages/pn-validator/src/ruleValidators/__test__/ObjectRuleValidator.test.ts, packages/pn-validator/src/ruleValidators/__test__/StringRuleValidator.test.ts, packages/pn-validator/src/rules/Required.ts, packages/pn-validator/src/rules/__test__/Required.test.ts, packages/pn-validator/src/utility/IsDefined.ts
Add required rule on pn-validator
- Add rule
- Add tests of rule
=> PN-7276 - Add required rule on pn-validator

packages/pn-commons/src/hooks/index.ts, packages/pn-commons/src/hooks/useDownloadDocument.ts, packages/pn-commons/src/utility/Screenshot/apply-style.ts, packages/pn-commons/src/utility/Screenshot/clone-node.ts, packages/pn-commons/src/utility/Screenshot/clone-pseudos.ts, packages/pn-commons/src/utility/Screenshot/dataurl.ts, packages/pn-commons/src/utility/Screenshot/embed-images.ts, packages/pn-commons/src/utility/Screenshot/embed-resources.ts, packages/pn-commons/src/utility/Screenshot/embed-webfonts.ts, packages/pn-commons/src/utility/Screenshot/index.ts, packages/pn-commons/src/utility/Screenshot/mimes.ts, packages/pn-commons/src/utility/Screenshot/types.ts, packages/pn-commons/src/utility/Screenshot/util.ts, packages/pn-commons/src/utility/date.utility.ts, packages/pn-commons/src/utility/index.ts, packages/pn-pa-webapp/src/components/Statistics/AggregateStatistics.tsx, packages/pn-pa-webapp/src/components/Statistics/DigitalMeanTimeStatistics.tsx, packages/pn-pa-webapp/src/components/Statistics/DigitalStateStatistics.tsx, packages/pn-pa-webapp/src/components/Statistics/FilterStatistics.tsx, packages/pn-pa-webapp/src/components/Statistics/LastStateStatistics.tsx, packages/pn-pa-webapp/src/components/Statistics/TrendStackedStatistics.tsx, packages/pn-pa-webapp/src/pages/Statistics.page.tsx
This code adds the Screenshot module to utility folder (pn-commons) to allow jpeg image generation starting from an html node.
- adds Screenshot module under pn-commons 'utility' folder
- changes Statistics.page adding a global 'export jpeg' button
- removes the download icon from every statistics component
- changes formatDate method in common date.utility to specify a custom separator
- Go to sender dashboard and verify the 'download jpeg' button is visible and there's no download icon on statistics components
- Click on the 'download jpeg' button and verify a jpeg screenshot of every statistics component is generated and available to download.
=> feat/PN-11563 - Add 'download jpeg' button to sender dashboard

packages/pn-commons/src/utility/string.utility.ts, packages/pn-pa-webapp/src/App.tsx, packages/pn-personafisica-login/src/__test__/App.test.tsx, packages/pn-personafisica-login/src/pages/login/Login.tsx, packages/pn-personafisica-login/src/pages/login/__test__/Login.test.tsx, packages/pn-personafisica-login/src/pages/success/Success.tsx, packages/pn-personafisica-login/src/pages/success/__test__/Success.test.tsx, packages/pn-personafisica-webapp/src/App.tsx, packages/pn-personafisica-webapp/src/__test__/App.test.tsx
Handle multi language on PF and PF Login. Also store lang on session storage of PA in order to make footer works properly
- Add lang on success URL of PF Login
- Read lang from URL on PF
- Store lang on session storage of PA
On PF, use a direct access link and append a lang query parameter with a language (e.g. &lang=en) to it. Verify that the page is translated into the selected language. Also, try refreshing the page and check that the selected language is retained
=> PN-11747 - Handle multi language on PF

packages/pn-commons/src/utility/string.utility.ts, packages/pn-personafisica-login/src/pages/success/Success.tsx
Restore `sanitizeString` function without `escapeMetaCharacters`
- Edit `sanitizeString`
On PG, edit the organization name in sessionStorage and add special characters (such as &, <, >, ...) to verify that they are displayed properly.
=> PN-12118 - Escape meta characters

packages/pn-personafisica-webapp/src/components/Contacts/DigitalContactElem.tsx, packages/pn-personafisica-webapp/src/components/Contacts/EmailContactItem.tsx, packages/pn-personafisica-webapp/src/components/Contacts/PecContactItem.tsx, packages/pn-personafisica-webapp/src/components/Contacts/SmsContactItem.tsx, packages/pn-personafisica-webapp/src/components/Contacts/SpecialContactElem.tsx, packages/pn-personafisica-webapp/src/components/Contacts/__test__/CourtesyContacts.test.tsx, packages/pn-personafisica-webapp/src/components/Contacts/__test__/EmailContactItem.test.tsx, packages/pn-personafisica-webapp/src/components/Contacts/__test__/LegalContacts.test.tsx, packages/pn-personafisica-webapp/src/components/Contacts/__test__/PecContactItem.test.tsx, packages/pn-personafisica-webapp/src/components/Contacts/__test__/SmsContactItem.test.tsx, packages/pn-personafisica-webapp/src/components/Contacts/__test__/SpecialContactElem.test.tsx, packages/pn-personafisica-webapp/src/components/Contacts/__test__/SpecialContacts.test.tsx, packages/pn-personafisica-webapp/src/pages/__test__/Contacts.page.test.tsx, packages/pn-personafisica-webapp/src/utility/contacts.utility.ts, packages/pn-personagiuridica-webapp/src/components/Contacts/DigitalContactElem.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/EmailContactItem.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/PecContactItem.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/SmsContactItem.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/SpecialContactElem.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/CourtesyContacts.test.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/EmailContactItem.test.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/LegalContacts.test.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/PecContactItem.test.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/SmsContactItem.test.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/SpecialContactElem.test.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/SpecialContacts.test.tsx, packages/pn-personagiuridica-webapp/src/pages/__test__/Contacts.page.test.tsx
Use single contact compoent into SpecialContactElem
- Updated PecContactItem, EmailContactItem, SmsContactItem to manage special contact case
- Integrated into SpecialContactElem single contact components
- Updated tests
Login with pf/pg -> go to Recapiti page -> add/edit/remove special contacts and check that everything is ok
=> use single contact compoent into SpecialContactElem - pn-12069

packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/SendDisableIOStrategy.ts, packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/SendEnableIOStrategy.ts, packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/__test__/SendDisableIOStrategy.test.ts, packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/__test__/SendEnableIOStrategy.test.ts
Add track of SEND_APPIO_STATUS super property
- Add SEND_APPIO_STATUS super property
To test this bug, you need to use the Netify Chrome extension.
Intercept the following URL with Netify: https://webapi.dev.notifichedigitali.it/bff/v1/addresses
Use this response body:
```json
[
{
"addressType":"COURTESY",
"senderId":"default",
"channelType":"APPIO",
"value":"ENABLED"
}
]
```
Then, try to deactivate AppIO. You should see two console logs:
`{SEND_APPIO_STATUS: 'deactivated'} profile` and `{SEND_APPIO_STATUS: 'deactivated'} superProperty`.
=> PN-12254 - Add mixpanel track of SEND_APPIO_STATUS super property

packages/pn-commons/src/components/NotificationDetail/NotificationPaymentF24Item.tsx
lateral  scroll in notification detail
- add sx overflow wrap = "anywhere"  in f24 title
Documentation of overflow-wrap : https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
set mobile view with at least 330px on x axis
For verify every cases use this notification iun on develop enviroment and cesare as user : 
VEKV-UEZM-LUDJ-202408-W-1 for basic case
WERP-PEQV-LKDW-202408-W-1 for payment with only F24 without costi notifica label
KDER-ZDKL-GZGH-202408-Q-1 for payment with pagopa avviso and F24
Testing with netify exstension of google for failure case of download F24
=> Fixed lateral scroll when title of F24 is too much long

packages/pn-pa-webapp/src/services/configuration.service.ts, packages/pn-personafisica-webapp/src/pages/PrivacyPolicy.page.tsx, packages/pn-personafisica-webapp/src/pages/TermsOfService.page.tsx, packages/pn-personafisica-webapp/src/services/configuration.service.ts, packages/pn-personagiuridica-webapp/src/pages/PrivacyPolicy.page.tsx, packages/pn-personagiuridica-webapp/src/pages/TermsOfService.page.tsx, packages/pn-personagiuridica-webapp/src/services/configuration.service.ts
When the user navigates to sercq send tos and privacy pages, it sees an empty pages. This is due to a wrong id in the html.
- Parametrized main div id in tos and privacy pages (pf/pg)
Login with pf/pg -> go to tos and privacy pages and check that correct pages are shown
Login with pfpg -> go to sercq send tos and privacy pages and check that correct pages are shown
=> fixed tos and privacy pages - pn-12661

packages/pn-pa-webapp/openapitools.json, packages/pn-personafisica-webapp/openapitools.json, packages/pn-personagiuridica-webapp/openapitools.json, packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/SercqSendContactItem.test.tsx, packages/pn-personagiuridica-webapp/src/redux/contact/actions.ts
When a PG enables the SERCQ SEND, it has to accept the linked tos and privacy. For the PG there are specific api to call
- Updated bff dependencies
- Updated api called during retrieve and acceptance of tos and dataprivacy
Login with PG (no DivinaCommedia) -> enable SERCQ SEND -> check everything is ok
=> Migrated to pg api for tos retrieve and acceptance - pn-12392

packages/pn-personafisica-webapp/src/components/Contacts/SercqSendContactItem.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/SercqSendContactItem.tsx
When Sercq SEND is enabled ad default address, the disabling action must be blocked if a PEC or a Sercq SEND address is added as special contact
- Updated SercqSendContactItem
Login with pf/pg -> go to recapiti -> add PEC as default address -> add SERCQ SEND as special address -> activate SERCQ SEND as default address -> try to disable the default SERCQ SEND -> the action must be blocked
=> fix disabling SERCQ SEND when special address is added - pn-12424

packages/pn-personafisica-webapp/src/components/Contacts/SpecialContacts.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/SpecialContacts.tsx
Section "Recapiti personalizzati". When user click on button "personalizza recapiti" and go forward to code modal, clicking on cancel button doesn't reset the AddSpecialContactDialog's state.
- Updated SpecialContacts (pf/pg)
Login with pf/pg -> go to "Recapiti" page -> add a default legal address and click on "personalizza recapiti" -> go forward to the code modal dialog -> click on cancel button -> click on "personalizza recapiti" -> check that the opened modal hasn't the fields filled with the previous values
=> reset modal state when cancel is clicked - pn-12394

packages/pn-personafisica-webapp/src/components/Contacts/PecContactItem.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/PecContactItem.tsx
Sercq enabled. When user adds a PEC and it goes under validation, sercq and pec are shown under the same card.
- Updated PecContactItem
Login with pf/pg -> enable DoD -> add a PEC -> check that until the PEC is validated, two cards are shown
=> fixed layout when pec is in validation state - pn-12537

packages/pn-personafisica-webapp/src/components/DomicileBanner/DomicileBanner.tsx
Show AppIO banner when dod feature is disabled and user has AppIO installed but SEND service disabled.
- Updated DomicileBanner.tsx
- Add in configuration file "DOD_DISABLED": true -> login with pf -> with netify simulate an user with a pec, a courtesy contact and AppIO installed but disabled -> check that the AppIO banner is shown
- Add in configuration file "DOD_DISABLED": true -> login with pf -> with netify simulate an user with a pec, a courtesy contact and AppIO installed and enabled -> check that the AppIO banner is not shown
- Remove the DOD_DISABLED -> login with pf -> with netify simulate an user with DoD, a courtesy contact and AppIO installed but disabled -> check that the AppIO banner is shown
- Remove the DOD_DISABLED -> login with pf -> with netify simulate an user with …
=> show AppIO banner when dod feature is disabled - pn-12538

packages/pn-personagiuridica-webapp/src/components/IntegrazioneApi/VirtualKeyContextMenu.tsx, packages/pn-personagiuridica-webapp/src/components/IntegrazioneApi/VirtualKeysTable.tsx
…keys
This PR fixes a bug causing the inability, for a admin with groups, to view and rotate his/her own personal keys
Run pn-personagiuridica-webapp and log as admin with groups. Create a personal key and verify the context menu shows the rotate/view actions.
=> Fix/PN-12969: Admin with groups is not able to view/rotate his/her own virtual keys

packages/pn-commons/src/models/NotificationDetail.ts, packages/pn-commons/src/utility/__test__/notification.utility.test.ts, packages/pn-commons/src/utility/notification.utility.ts
Insert correct copy when timeline status is analog failure workflow
in notification utilities file delete control on generetadAarUrl
login with PF, username: leonardo in dev enviroment and go on notification with iun : 
YDWX-JQGA-XVTL-202410-H-1
and visualize in timeline correct copy
=> Fixed wrong copy

packages/pn-pa-webapp/src/__mocks__/Statistics.mock.ts, packages/pn-pa-webapp/src/components/NewApiKey/SyncFeedbackApiKey.tsx, packages/pn-pa-webapp/src/pages/NewApiKey.page.tsx, packages/pn-pa-webapp/src/pages/__test__/NewApiKey.page.test.tsx
This PR fixes a bug which was causing to show api key id instead of its value after key creation for PA, adds the code to test this behaviour and fixes an switches from static to dynamic dates for statistics mock to avoid too old dates to cause tests about quick filters to fail.
- SyncFeedbackApiKey.tsx: change prop name to clarify its content and other minor changes
- NewApiKey.page.tsx: pass the right value to the SyncFeedbackApiKey component
- NewApiKey.page.test.tsx: add the code to check the right value is showed after api key creation
- Statistics.mock.ts: make dates dynamic to fix 'quick filters' test failure
Log in as PA administrator, create a new API key and verify the value showed inside the response page is the key value.
=> fix/PN-13045 - New API key confirmation component wrongly shows key id instead of its value (PA)

packages/pn-personagiuridica-webapp/src/components/Contacts/SercqSendContactItem.tsx
This PR fixes a bug on PG (PF was already working fine) which was showing the modal window allowing the user to set a courtesy contact after enabling SERCQ for a specific party (special contact)
Follow the steps detailed on the corresponding Jira task to verify the issue is solved
=> fix/PN-12934 - Hide "add courtesy contact" modal after enabling SERCQ as special contact for PG

packages/pn-pa-webapp/public/locales/it/notifiche.json, packages/pn-pa-webapp/src/components/NewNotification/Attachments.tsx, packages/pn-pa-webapp/src/components/NewNotification/__test__/Attachments.test.tsx, packages/pn-pa-webapp/src/pages/NewNotification.page.tsx
An info banner is shown in attachments tab when PA user creates a manual notification with an additional language 
Start pa-webapp and login with a PA user. 
Create manual notification with an additional language. In attachment tab, check the banner
=> feat/PN-13044: info banner in attachments tab

packages/pn-personafisica-webapp/public/locales/it/recapiti.json, packages/pn-personafisica-webapp/src/components/Contacts/IOContact.tsx
This code shows success message when appIO is enabled/disabled ad courtesy contact
Log as pf user on uat and verify a success message is shown every time the appIO contact is enabled/disabled
=> Fix/PN-13070 - add successful messages on appIO enable/disable (PF)

packages/pn-personagiuridica-webapp/src/components/IntegrazioneApi/VirtualKeysTable.tsx
Shows owner's denomination instead of key name on virtual key table
Login as PG Admin and verify virtual key owner's denomination is shown for every item of the virtual key table
=> fix/Pn-12968: replace key name with user denomination in virtual key table for PG

packages/pn-pa-webapp/src/App.tsx, packages/pn-pa-webapp/src/__mocks__/NewNotification.mock.ts, packages/pn-pa-webapp/src/__test__/App.test.tsx, packages/pn-pa-webapp/src/components/NewNotification/PreliminaryInformations.tsx, packages/pn-pa-webapp/src/components/NewNotification/__test__/PreliminaryInformations.test.tsx, packages/pn-pa-webapp/src/pages/Dashboard.page.tsx, packages/pn-pa-webapp/src/pages/__test__/Dashboard.page.test.tsx, packages/pn-pa-webapp/src/redux/newNotification/__test__/reducers.test.ts, packages/pn-pa-webapp/src/redux/newNotification/reducers.ts
- Move call api in App.ts
Start pa-webapp. Go to "notifications" page and set an additional language from settings drawer.
Now go to the manual notification creation page and check selection of additional language.
=> Feat/PN-13043: pre-select additionalLanguage from settings

packages/pn-commons/src/components/FileUpload.tsx, packages/pn-pa-webapp/src/components/NewNotification/Attachments.tsx
Fix field "documents" in form of manual notification creation after upload a file.
- remove `setFieldTouched` and set `shouldValidate` on `setFieldValue`
Start pa-webapp. Login and create manual notification. In 3rd step upload a file and check that `send` button is enabled
=> Fix/PN-13256: validate documents form

packages/pn-commons/src/components/CodeModal/CodeModal.tsx
This code sets the overflow-wrap property on CodeModal title to grant very long pec/mail addresses are shown.
Follow the steps described on the relative Jira task, check it works on both PF and PG webapps
=> fix/PN-12735 -  Very long PEC/Email address not fully shown on code confirmation modal window

packages/pn-personafisica-webapp/public/locales/de/common.json, packages/pn-personafisica-webapp/public/locales/en/common.json, packages/pn-personafisica-webapp/public/locales/fr/common.json, packages/pn-personafisica-webapp/public/locales/it/common.json, packages/pn-personafisica-webapp/public/locales/sl/common.json, packages/pn-personafisica-webapp/src/components/Contacts/DefaultDigitalContact.tsx, packages/pn-personafisica-webapp/src/utility/contacts.utility.ts, packages/pn-personagiuridica-webapp/public/locales/de/common.json, packages/pn-personagiuridica-webapp/public/locales/en/common.json, packages/pn-personagiuridica-webapp/public/locales/fr/common.json, packages/pn-personagiuridica-webapp/public/locales/it/common.json, packages/pn-personagiuridica-webapp/public/locales/sl/common.json, packages/pn-personagiuridica-webapp/src/components/Contacts/DefaultDigitalContact.tsx, packages/pn-personagiuridica-webapp/src/utility/contacts.utility.ts
The proposed code adds a control to the yup validation schema of the digital contacts to show a specific error message when blank spaces are added before/after the value (PF and PG)
Verify on both PF and PG webapps the user is not allowed to add spaces before/after any digital contact
=> feat/PN-13174: Add blank spaces validation to digital contact input field (PF and PG)

packages/pn-commons/src/components/TitleBox.tsx
fix how render title of notification
- insert css of viewport and wrap in title box component
go in PA, UAT with ggiorgi user and go in notification with iun YVTG-WVRL-XWMW-202409-J-1
=> (fix-pn/12727) Fix of render a long title of notification

packages/pn-commons/src/components/CustomTooltip.tsx, packages/pn-commons/src/components/Notifications/StatusTooltip.tsx, packages/pn-commons/src/components/Notifications/__test__/StatusTooltip.test.tsx, packages/pn-commons/src/components/__test__/CustomTooltip.test.tsx
delete default role in chip for status of notification
- insert role cell for StatusTooltip component
in table of notification, with voice over activeted , voice over read status of notification and description explained in the tooltip, only description is clickable
=> fix(PN-13212)  chip stato notifica/pagamenti

packages/pn-commons/src/components/NotificationDetail/NotificationDetailDocuments.tsx, packages/pn-commons/src/models/NotificationDetail.ts, packages/pn-commons/src/models/PaymentCache.ts, packages/pn-commons/src/utility/notification.utility.ts, packages/pn-pa-webapp/openapitools.json, packages/pn-pa-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-pa-webapp/src/pages/__test__/NotificationDetail.page.test.tsx, packages/pn-personafisica-webapp/openapitools.json, packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx, packages/pn-personagiuridica-webapp/openapitools.json, packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personagiuridica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
This PR makes use of the lates changes in bff response to properly manage the translation of the `Notifications of receipt` shown inside the notification detail page. It fixes both PN-13269 and PN-13132 bugs.
- NotificationDetail.ts model
- NotificationDetailDocuments.tsx
This PR should be tested on PF, PG and PA (single and multi-recipient notifications) using netify to mock the notification detail response. The `otherDocuments` array inside the original response should be modified removing, from everyone of contained elements, the `title` property and adding a recipient object as in the following example:
```
"recipient": {
"denomination": "Cristoforo Colombo",
"taxId": "CLMCST42R12D969Z"
}
```
=> fix/PN-13269: Manage Notification of receipt translation

packages/pn-personafisica-webapp/src/components/Deleghe/ConfirmationModal.tsx, packages/pn-personagiuridica-webapp/src/components/Deleghe/ConfirmationModal.tsx
Fix aria-labelledby on modal revoca
Start PF app and create delegation. Start voiceover and click "revoke" on contesxual menu. ScreenReader must read correct title
=> fix/PN-13255: aria-labelledby on modal "revoca delega"

packages/pn-commons/src/components/NotificationDetail/NotificationDetailTimelineStep.tsx, packages/pn-commons/src/components/NotificationDetail/__test__/NotificationDetailTimelineStep.test.tsx
fix SEND-477 focus on dowload-legal-micro Same logic as the main timeline documents inserted
- change TextField with tabindex and insert style for focus
-check that the See more details button in the timeline is clickable and interactable with the tab
-check that exploding the previous button opens the details and that the documents are reachable with the card
- check that they have the correct focus, when you get there with the tab a blue border appears as in the other links
- check that the Canceled status chip cannot be clicked or interacted with the mouse or keyboard
=> (PN-13215) Lettura timeline

packages/pn-commons/src/components/CustomTagGroup/CustomTagGroup.tsx, packages/pn-commons/src/components/CustomTagGroup/__test__/CustomTagGroup.test.tsx, packages/pn-commons/src/components/Data/PnTable/PnTableHeaderCell.tsx, packages/pn-personafisica-webapp/src/components/Deleghe/Delegates.tsx, packages/pn-personafisica-webapp/src/components/Deleghe/DelegationsElements.tsx, packages/pn-personagiuridica-webapp/src/components/Deleghe/DelegatesByCompany.tsx, packages/pn-personagiuridica-webapp/src/components/Deleghe/DelegationsElements.tsx
This PR adds an ariaLabel to `CustomTagGroup` that reads content of tooltip for a11y
Start and login PF app. Go to "Deleghe" page and create a delegation with more than 3 `enti selezionati`. Go back and start voiceover. Navigate with keyboard on chips in column "Permessi"
=> Fix/PN-13598: tooltip deleghe

packages/pn-pa-webapp/src/components/Statistics/DigitalErrorsDetailStatistics.tsx, packages/pn-pa-webapp/src/models/Statistics.ts
Update error graph colors on Statistics page according to design [Figma](https://www.figma.com/design/VCVk6WrSwxuTuw0lZEzPw5/PA-Mittenti?node-id=2501-4400&p=f&t=6Uog93XLP6LdBJ8A-0)
- Add new colors
=> feat: update error graph colors

packages/pn-pa-webapp/public/locales/de/notifiche.json, packages/pn-pa-webapp/public/locales/en/notifiche.json, packages/pn-pa-webapp/public/locales/fr/notifiche.json, packages/pn-pa-webapp/public/locales/it/notifiche.json, packages/pn-pa-webapp/public/locales/sl/notifiche.json, packages/pn-pa-webapp/src/__mocks__/NewNotification.mock.ts, packages/pn-pa-webapp/src/components/NewNotification/Attachments.tsx, packages/pn-pa-webapp/src/components/NewNotification/DebtPosition.tsx, packages/pn-pa-webapp/src/components/NewNotification/__test__/Attachments.test.tsx, packages/pn-pa-webapp/src/components/NewNotification/__test__/DebtPosition.test.tsx, packages/pn-pa-webapp/src/components/NewNotification/__test__/Recipient.test.tsx, packages/pn-pa-webapp/src/models/NewNotification.ts, packages/pn-pa-webapp/src/pages/NewNotification.page.tsx, packages/pn-pa-webapp/src/redux/newNotification/__test__/reducers.test.ts, packages/pn-pa-webapp/src/redux/newNotification/reducers.ts, packages/pn-pa-webapp/src/utility/__test__/notification.utility.test.ts, packages/pn-pa-webapp/src/utility/__test__/validation.utility.test.ts, packages/pn-pa-webapp/src/utility/notification.utility.ts
Create new step on New Notification process to handle the debt position of every recipient.
- Add new step
- Moved attachments step to the end 
- Create utility to handle payments when debtPosition change
- Run tests and checks that passes
- Start PA and try to create a new notification, you should see a new step called "Posizione debitoria"
- Check that payment methods step is skipped if debt position is set to `Nessun pagamento`
=> PN-13999 - Create debt position step on new notification

packages/pn-commons/src/components/NotificationDetail/NotificationPaymentRecipient.tsx, packages/pn-commons/src/components/NotificationDetail/__test__/NotificationPaymentRecipient.test.tsx, packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personafisica-webapp/src/utility/MixpanelUtils/PFEventStrategyFactory.ts, packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/UXPspActionStrategy.ts, packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/__test__/UXPspActionStrategy.test.ts, packages/pn-personafisica-webapp/src/utility/MixpanelUtils/__test__/PFEventStrategyFactory.test.ts
Added property `psp` in SEND_START_PAYMENT event. 
Possible values: `pagopa` or specific tpp name. 
- Create new strategy for UX Action with psp property
Login in PF with rapid access with retrievalId. Click on payment button with bank.
=> feat/PN-13894: [MIXPANEL]: add property "psp" in event SEND_START_PAYMENT 

packages/pn-pa-webapp/src/components/NewNotification/DebtPositionDetail.tsx, packages/pn-pa-webapp/src/components/NewNotification/PaymentMethods.tsx, packages/pn-pa-webapp/src/utility/validation.utility.ts
Update formik recipient key to handle numeric CF by adding `recipientType` before `taxId`
- Edit formik `initialValues` and `validationSchema`
- Start PA
- Create a new notification with only a PG as recipient (or a PF and a PG)
- Select PagoPA as debt position for both recipients
- Try to insert the same `noticeCode` and check that error is show. Same for the applyCost switch
=> PN-14148 - Update formik recipient key to handle numeric CF

packages/pn-pa-webapp/src/redux/newNotification/reducers.ts, packages/pn-pa-webapp/src/utility/notification.utility.ts
Clear payment fields (`paFee`, `vat`, and `pagoPaIntMode`) when setting the debt position to NOTHING. Also, set `notificationFeePolicy` to FLAT_RATE when no `notificationFeePolicy` is set
- Clear the fields (`paFee`, `vat`, and `pagoPaIntMode`) when the debt position is set to NONE in the reducer
- Provide a default value for `notificationFeePolicy`
1. Start PA
2. Create a new notification with some payments and proceed to the last step
3. From the last step, go back to the Debt Position step and select "Nessuna posizione debitoria"  
4. Then, move forward, send the notification, and verify that `paFee`, `vat`, and `pagoPaIntMode` are not present in the request payload
=> PN-14166 - Clear payment fields when set debt position to NOTHING

packages/pn-personafisica-webapp/src/components/Contacts/DigitalContactActivation.tsx, packages/pn-personafisica-webapp/src/components/Contacts/EmailContactItem.tsx, packages/pn-personafisica-webapp/src/components/Contacts/EmailSmsContactWizard.tsx, packages/pn-personafisica-webapp/src/components/Contacts/LegalContactAssociationDialog.tsx, packages/pn-personafisica-webapp/src/components/Contacts/PecContactWizard.tsx, packages/pn-personafisica-webapp/src/components/Contacts/SercqSendContactWizard.tsx, packages/pn-personafisica-webapp/src/components/Contacts/SmsContactItem.tsx, packages/pn-personafisica-webapp/src/pages/Contacts.page.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/DigitalContactActivation.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/LegalContactAssociationDialog.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/PecContactWizard.tsx
This PR fixes the following bugs reported on Digital Domicile feature: PN-14103, PN-14104, PN-14111, PN-14115, PN-14116.
- add from_sercq_send property to SEND_ADD_EMAIL_UX_SUCCESS and SEND_ADD_SMS_UX_SUCCESS registering a new email/sms contact during sercq activation/transfer wizard
- trigger SEND_YOUR_CONTACT_DETAILS when the user navigates to contacts page
- set the correct source for the events SEND_ADD_PEC_START and SEND_ADD_EMAIL_START
- with FF to false (SERCQ_SEND disabled) now the wizard directly shows the PecContactWizard with the input to specify the PEC address and without the stepper above the component
- the LegalContactAssociationDialog now properly shows the new and old address values instead of their placeholders
=> Fix/pn-14111 - Digital Domicile bug fixes

packages/pn-commons/src/utility/notification.utility.ts, packages/pn-pa-webapp/public/locales/it/notifiche.json, packages/pn-personafisica-webapp/public/locales/it/notifiche.json, packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json
This changes italian translation for analog failure delivery in timeline when recipient is unreachable
- PA: login as 'Comune di Palermo' and search for a notification having IUN 'DQTM-XPVY-KAEV-202408-H-1'
- PF: Login as 'Alessandro Manzoni' and search for the notification having IUN 'DQTM-XPVY-KAEV-202408-H-1'
- PG: Login as any user, access a notification and mock the response to return the same response obtained above for PF
Look at the timeline and verify the text for analog failure delivery is correct.
=> fix/PN-14201 - Fix copy in timeline

packages/pn-pa-webapp/src/components/NewNotification/F24PaymentBox.tsx, packages/pn-pa-webapp/src/components/NewNotification/__test__/F24PaymentBox.test.tsx, packages/pn-pa-webapp/src/components/NewNotification/__test__/PagoPaPaymentBox.test.tsx
Hide Installment alert on F24 payment box when fee policy is `FLAT_RATE`
- Edit logic on F24PaymentBox
- Add some unit tests 
- Start PA
- Create a new notification
- On debt position step select F24
- Select `Incluso nell’atto (forfettario)` as notification fee policy
- Try adding multiple F24 and verify that no alert is displayed
=> PN-14326 - Hide Installment alert on F24 payment box when fee policy is FLAT_RATE

packages/pn-personagiuridica-webapp/src/components/IntegrazioneApi/VirtualKeysTable.tsx
Hide 'name' field for personal keys when the user is entitled to only view his/her own keys (non-admin)
On PG webapp verify that only admin can see the 'name' column inside the API Integration section but admin with groups and operator cannot
=> fix/PN-13660 - Hide 'name' column on VirtualKeyTable for non-admin users (PG)

packages/pn-pa-webapp/public/conf/config-dev.json, packages/pn-pa-webapp/public/locales/it/notifiche.json, packages/pn-pa-webapp/src/components/NewNotification/Recipient.tsx, packages/pn-pa-webapp/src/components/NewNotification/__test__/Recipient.test.tsx, packages/pn-pa-webapp/src/models/NewNotification.ts, packages/pn-pa-webapp/src/services/configuration.service.ts, packages/pn-pa-webapp/src/setupTests.tsx
Add feature flag for manage this PR https://github.com/pagopa/pn-frontend/pull/1523
- `PHYSICAL_ADDRESS_LOOKUP` takes 3 possibile values `on`, `off`, `down`
Add `PHYSICAL_ADDRESS_LOOKUP` in your configurations.
Start PA and check form in second step of manual notification creation with these scenarios:
`on`: radio group is shown
`off`: radio group is not present and physical form is "as is"
`down`: radio group is shown but physical address is required (national registry radio button is disabled)
=> Feat/PN-14280: feature flag for optional physical address

packages/pn-commons/src/components/NotificationDetail/NotificationPaymentF24Item.tsx, packages/pn-commons/src/components/NotificationDetail/NotificationPaymentPagoPAItem.tsx, packages/pn-commons/src/components/NotificationDetail/__test__/NotificationPaymentF24Item.test.tsx, packages/pn-commons/src/components/NotificationDetail/__test__/NotificationPaymentPagoPAItem.test.tsx
restore label included-costs
- add label included-costs in pagopa payment
- add label included-costs in f24 payment
Login as cristoforocolombo and check label is present. Use [these notifications](https://pagopa.atlassian.net/wiki/spaces/PN/pages/1630208256/Esiste+un+utenza+che..) for `dev`
=> fix(PN-14852): restore label included-costs

packages/pn-pa-webapp/public/locales/it/statistics.json, packages/pn-pa-webapp/src/__mocks__/Statistics.mock.ts, packages/pn-pa-webapp/src/components/Statistics/DeliveryModeStatistics.tsx, packages/pn-pa-webapp/src/components/Statistics/DigitalStateStatistics.tsx, packages/pn-pa-webapp/src/components/Statistics/FiledNotificationsStatistics.tsx, packages/pn-pa-webapp/src/components/Statistics/LastStateStatistics.tsx, packages/pn-pa-webapp/src/components/Statistics/__test__/DeliveryModeStatistics.test.tsx, packages/pn-pa-webapp/src/components/Statistics/__test__/DigitalStateStatistics.test.tsx, packages/pn-pa-webapp/src/components/Statistics/__test__/FiledNotificationsStatistics.test.tsx, packages/pn-pa-webapp/src/components/Statistics/__test__/LastStateStatistics.test.tsx, packages/pn-pa-webapp/src/models/Statistics.ts, packages/pn-pa-webapp/src/redux/statistics/reducers.ts, packages/pn-pa-webapp/src/utility/StatisticsData/DeliveryModeStatisticsData.ts, packages/pn-pa-webapp/src/utility/StatisticsData/DigitalMeanTimeStatisticsData.ts, packages/pn-pa-webapp/src/utility/StatisticsData/DigitalStateStatisticsData.ts, packages/pn-pa-webapp/src/utility/StatisticsData/FiledStatisticsData.ts, packages/pn-pa-webapp/src/utility/StatisticsData/LastStateStatisticsData.ts
Added `RETURNED_TO_SENDER` notification status to the statistics page. Also handled unknown values (`-`) for `notification_request_status`, `notification_delivered`, and `notification_viewed`.  
Additionally, renamed some types by adding a `Statistics` prefix.
- Fixed missing notification status and handled unknown values
- Renamed types
- Start PA and log in with `grossini` - `Comune di Palermo`
- Use Netify to mock this endpoint: `https://webapi.dev.notifichedigitali.it/bff/v1/sender-dashboard/dashboard-data-request/PA/5b994d4a-0fa8-47ac-9c7b-354f1d44a1ce?startDate=2024-05-08&endDate=2025-05-07` and return the JSON attached to the JIRA bug
- Verify that the page doesn't crash and that `Returned to sender` is shown on the `Notifiche inviate per stato` chart
=> fix(PN-14877): add RETURNED_TO_SENDER status on statistics page and rename some types

packages/pn-pa-webapp/public/locales/it/notifiche.json, packages/pn-personafisica-webapp/public/locales/it/notifiche.json, packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json
This PR includes the changes required for CAD/ARCAD attachment in timeline
Environment: DEV
PA: Login as grossini (Sappada) and access notifications having IUN 'TWJP-NWPW-MQTU-202505-L-1' and 'VGHR-VJPD-AGUZ-202505-L-1'. Verify the timeline shows the CAD/ARCAD attachment as expected.
PF: login using the notifications' recipient and search for the same IUN. Verify the timeline.
PG: Create a new mandate and verify the feature works properly for PG too
=> feat(PN-14807): add copy for CAD/ARCAD in timeline

packages/pn-commons/src/components/CustomDropdown.tsx, packages/pn-personafisica-webapp/public/locales/de/recapiti.json, packages/pn-personafisica-webapp/public/locales/en/recapiti.json, packages/pn-personafisica-webapp/public/locales/fr/recapiti.json, packages/pn-personafisica-webapp/public/locales/it/notifiche.json, packages/pn-personafisica-webapp/public/locales/it/recapiti.json, packages/pn-personafisica-webapp/public/locales/sl/recapiti.json, packages/pn-personafisica-webapp/src/components/Contacts/AddSpecialContact.tsx, packages/pn-personafisica-webapp/src/components/Contacts/LegalContacts.tsx, packages/pn-personafisica-webapp/src/components/Contacts/PecContactWizard.tsx, packages/pn-personafisica-webapp/src/components/Contacts/__test__/AddSpecialContact.test.tsx, packages/pn-personafisica-webapp/src/components/Contacts/__test__/PecContactWizard.test.tsx, packages/pn-personagiuridica-webapp/public/locales/it/recapiti.json, packages/pn-personagiuridica-webapp/src/components/Contacts/AddSpecialContact.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/LegalContacts.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/PecContactWizard.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/AddSpecialContact.test.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/PecContactWizard.test.tsx
Restored disclaimer for pec.
- Added new control during the PEC insertion
- Added new disclaimer in the main section of the domicile contacts
- Updated tests
Login with pf -> go to contacts page -> add a PEC as a legal contact and check that the user must to confirm a disclaimer -> after check that a disclaimer is shown in the main section of the domicile contacts
Login with pf -> go to contacts page -> add a PEC as a legal contact linked to a specific sender and check that the user must to confirm a disclaimer
Login with pg -> do the same tests done for the pf
=> fix(pn-14941): restored disclaimer on digital domicile

packages/pn-personafisica-webapp/public/locales/it/common.json, packages/pn-personafisica-webapp/public/locales/it/deleghe.json, packages/pn-personafisica-webapp/src/utility/AppError/DeliveryMandateNotFoundAppError.ts, packages/pn-personafisica-webapp/src/utility/AppError/__test__/DeliveryMandateNotFoundAppError.test.ts
This PR moves the error message translation from ns 'deleghe' to 'common' one for DeliveryMandateNotFoundAppError to allow showing the correct copy outside the mandates page, fixing a bug which was causing showing untranslated error trying to access a notification for which the mandate is expired/revoked.
- move translation
- change tests
Follow the steps described in the Jira task to replicate the error and verify the bug is fixed
=> fix(pn-15230): move DeliveryMandateNotFoundAppError translation to 'common' ns

packages/pn-personafisica-webapp/src/App.tsx, packages/pn-personafisica-webapp/src/__test__/App.test.tsx, packages/pn-personafisica-webapp/src/api/auth/Auth.api.ts, packages/pn-personafisica-webapp/src/api/auth/auth.routes.ts, packages/pn-personafisica-webapp/src/redux/auth/actions.ts
API logout to invalidate token
- Call api /auth/logout
Login in PF and logout
=> Feat/PN-15327: PF call api logout before redirect

packages/pn-personafisica-webapp/public/locales/it/recapiti.json, packages/pn-personafisica-webapp/src/components/Contacts/DigitalContactActivation.tsx, packages/pn-personafisica-webapp/src/components/Contacts/SercqSendContactWizard.tsx, packages/pn-personafisica-webapp/src/components/Contacts/__test__/DigitalContactActivation.test.tsx, packages/pn-personafisica-webapp/src/components/Contacts/__test__/SercqSendContactWizard.test.tsx, packages/pn-personafisica-webapp/src/pages/DigitalContact.page.tsx, packages/pn-personafisica-webapp/src/redux/contact/__test__/reducers.test.ts, packages/pn-personafisica-webapp/src/redux/contact/reducers.ts, packages/pn-personagiuridica-webapp/public/locales/it/recapiti.json, packages/pn-personagiuridica-webapp/src/components/Contacts/DigitalContactActivation.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/SercqSendContactWizard.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/DigitalContactActivation.test.tsx, packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/SercqSendContactWizard.test.tsx, packages/pn-personagiuridica-webapp/src/pages/DigitalContact.page.tsx, packages/pn-personagiuridica-webapp/src/redux/contact/__test__/reducers.test.ts, packages/pn-personagiuridica-webapp/src/redux/contact/reducers.ts
This PR adds the last step of SERCQ activation/transfer wizard
- DigitalContactActivation.tsx: add logic to manage the new step and change the way showIOStep is calculated to avoid inconsistent state on refresh
- SercqSendContactWizard.tsx: add contacts recap list and the disclaimer checkbox
- DigitalContactActivation.test.tsx and SercqSendContactWizard.test.tsx: add/refactor tests to verify the new features work correctly
- redux/contact/reducers.ts: add code to update the 'loading' state. This state is used to grant the contacts have been loaded inside DigitalContactActivation component and prevent inconsistent behaviour, expecially when used to calculate the 'showIOStep' value. Added tests to check new code.
- recapiti.json: add/edit localization text
Run both PF and PG webapps and …
=> refactor(pn-15400): add recap step for SERCQ activation wizard

packages/pn-personafisica-webapp/src/navigation/SessionGuard.tsx
Use `exp` token date value from api response instead of `exp` value from redux that it's not ready.
=> fix(PN-15517): use actual expiry token date from api response

packages/pn-commons/src/components/InactivityHandler.tsx, packages/pn-commons/src/components/__test__/InactivityHandler.test.tsx, packages/pn-pa-webapp/public/conf/config-dev.json, packages/pn-pa-webapp/src/navigation/SessionGuard.tsx, packages/pn-pa-webapp/src/services/configuration.service.ts, packages/pn-pa-webapp/src/setupTests.tsx, packages/pn-personafisica-webapp/public/conf/config-dev.json, packages/pn-personafisica-webapp/src/navigation/SessionGuard.tsx, packages/pn-personafisica-webapp/src/services/configuration.service.ts, packages/pn-personafisica-webapp/src/setupTests.tsx, packages/pn-personagiuridica-webapp/public/conf/config-dev.json, packages/pn-personagiuridica-webapp/src/navigation/SessionGuard.tsx, packages/pn-personagiuridica-webapp/src/services/configuration.service.ts, packages/pn-personagiuridica-webapp/src/setupTests.tsx
With this PR, user inactivity is handled for a time (in minutes) specified in the configurations. For screen readers, the focus event is used.
- Add INACTIVITY_HANDLER_MINUTES in config 
Add `INACTIVITY_HANDLER_MINUTES` config. Start the app and remain inactive for the configured number of minutes.
=> fix/pn(14794): handle user inactivity

packages/pn-commons/src/components/InactivityHandler.tsx, packages/pn-personafisica-webapp/src/navigation/SessionGuard.tsx
If config `INACTIVITY_HANDLER_MINUTES` is `0` pndialog component is not rendered
=> fix/PN-14794: do not render component if inactivity handler is disabled

packages/pn-pa-webapp/src/components/NewNotification/Recipient.tsx
Add max length validation to house number and foreignState fields
- Fix yup validations
- Start PA
- Open new notification form
- On Recipient steps try to insert more than 1024 characters on `houseNumber` (numero civico) and `foreignState` (stato) fields and check that error is displayed
=> fix(PN-15847, PN-15848): add max length validation to house number and foreignState fields

packages/pn-personafisica-webapp/src/components/Contacts/AddSpecialContact.tsx, packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/SendAddSercqUxSuccessStrategy.ts
Add contacts to Mixpanel event when adding special contact in order to avoid application crash
- Add required properties to mixpanel event
- Start PF
- Add a PEC as main contact
- Add a special contact with SEND as contact type and check that works correctly
=> fix(PN-16362): add contacts to Mixpanel event when adding special contact

packages/pn-pa-webapp/src/components/Notifications/NotificationDetailTableSender.tsx, packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx, packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx
This PR includes the changes needed to remove the `amount` and `paymentExpirationDate` fields from `NotificationDetail` component.
PF:
- user: garibaldi - env: TEST
- IUN: PQKM-EGNQ-QKZG-202509-N-1
PA:
- user: grossini/Test 2 (Comune di Sappada) - env: TEST
- IUN: same as above
PG:
- user: Dante Alighieri / Divina Commedia) - env: TEST (create a new mandate if the current one has already expired)
- IUN: same as above
=> fix(PN-16180): Remove amount and paymentExpirationDate on NotificationDetail (PF, PG, PA)

packages/pn-commons/src/components/Header/Header.tsx, packages/pn-pa-webapp/public/locales/de/common.json, packages/pn-pa-webapp/public/locales/en/common.json, packages/pn-pa-webapp/public/locales/fr/common.json, packages/pn-pa-webapp/public/locales/it/common.json, packages/pn-pa-webapp/public/locales/sl/common.json, packages/pn-personafisica-webapp/public/locales/de/common.json, packages/pn-personafisica-webapp/public/locales/en/common.json, packages/pn-personafisica-webapp/public/locales/fr/common.json, packages/pn-personafisica-webapp/public/locales/it/common.json, packages/pn-personafisica-webapp/public/locales/sl/common.json, packages/pn-personagiuridica-webapp/public/locales/de/common.json, packages/pn-personagiuridica-webapp/public/locales/en/common.json, packages/pn-personagiuridica-webapp/public/locales/fr/common.json, packages/pn-personagiuridica-webapp/public/locales/it/common.json, packages/pn-personagiuridica-webapp/public/locales/sl/common.json
This PR translates the header labels when the language is changed from the footer.
- add string translation for `header.login` and `header.assistance` and pass as prop in mui component [Header](https://github.com/pagopa/mui-italia/blob/develop/src/components/HeaderAccount/HeaderAccount.tsx#L51)
Start app PA/PF/PG and login in SEND. Change lang in footer and check that labels in header are translated
=> Fix(PN-16259): pass translated label in Header component
